### ISSUE TITLE
attempt to index global 'actions' (a nil value)

### ISSUE THREAD

**Issue by euglevi** [ibhagwan/fzf-lua#10]
If I introduce the default config in one of the configuration files in the plugin directory, I get the error of the title each time I start neovim.

I have packer (plugins' configuration is not in the packer config variable but in separate files in the plugins directory) and the nightly version of neovim. This happened also with the stable 0.5 version. 

Then, and I'm not sure it is related, I have trouble making the ctrl-t key work. But again, I'm not sure it is related because this second issue started happening only recently.

**Comment by ibhagwan** [comment]
> If I introduce the default config in one of the configuration files in the plugin directory, I get the error of the title each time I start neovim.

Does this happen only with the default config (copied from the README) or also with an empty config? Does it also provide a line number where the error occurs?

> Then, and I'm not sure it is related, I have trouble making the ctrl-t key work. But again, I'm not sure it is related because this second issue started happening only recently.

Prior to yesterday’s update the plug-in would modify `vim.env.FZF_DEFAULT_OPTS`, that could potentially have conflicts with Ctrl-t **but only inside a neovim term**, it shouldn’t have affected the shell version but in anyways since yesterday that changed as well.

So I guess this question applies to both issues: is your plug-in fully updated?

**Comment by vijaymarupudi** [comment]
The default instructions for vim-plug do not include `nvim-fzf`, it is possible that it is the cause for this issue.

**Comment by ibhagwan** [comment]
> The default instructions for vim-plug do not include `nvim-fzf`, it is possible that it is the cause for this issue.

Good catch! I’ll fix that but the OP mentions he has `packer.nvim`.

**Comment by vijaymarupudi** [comment]
Ah good point, missed that!

**Comment by ibhagwan** [comment]
Alright that was an easy fix, the README was missing the action reference at the top, just add the below line above the setup function:
```lua
local actions = require "fzf-lua.actions"
require'fzf-lua'.setup {
<your config here>
}
```

**Comment by euglevi** [comment]
Thank you very much! That was it!
