### ISSUE TITLE
With path_shorten on, I can't find files by typing their full names

### ISSUE THREAD

**Issue by amagee** [ibhagwan/fzf-lua#1009]
### Info

- Operating System: Ubuntu 23.10
- Shell: zsh
- Terminal: kitty
- `nvim --version`:
Using Node v18.18.0
NVIM v0.10.0-dev-1809+g529498685
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
- `fzf --version`:
0.45.0 (202401011)

- [x] The issue is reproducible with `mini.sh`

### Description 

With `path_shorten=true`, I need to type the shortened paths to find the files I want; typing the original paths does not find the files.

For example, if my repository contains

`/setup/client/somefile1.txt`
`/setup/server/somefile1.txt`

And I do `:lua require("fzf-lua").git_files({path_shorten=true})`

Then `s/s` and `s/c` will find files, but `setup` will find nothing.

It's not clear to me if this is intentional, but it's not what I would expect. I see the path shortening as a rendering / output setting, not one that would affect the fuzzy search behaviour.

**Comment by ibhagwan** [comment]
> It's not clear to me if this is intentional, but it's not what I would expect.

This is intentional, with fzf the data is passed to an outside process (fzf), without hidden metadata, there is no way for fzf to match based on the full path as it does not exist.

Currently I have no plans on adding hidden metadata with full paths for path shorten as this will slow down considerably and consume too much memory on large repos.

**Comment by amagee** [comment]
Ok, fair enough. I will see if I can hack it on the fzf side.
