### ISSUE TITLE
[Question]: Exact match

### ISSUE THREAD

**Issue by ovidius72** [ibhagwan/fzf-lua#1058]
Sorry to ask maybe a stupid question.
I used to use AG with the classic fzf.nvim plugin and when I needed to do an exact match i prefixed the string to search with a single quote `'stringToSearch`. 
I've tried to do the same with FzfLua replacing Rg with Ag, but I couldn't figure out how. 
How would I configure a command to do what i want?
thanks in advance.

**Comment by ibhagwan** [comment]
You can still do exactly that, you were probably using `live_grep`which is already regex search (exact march, sort of), however, live grep does not use the fuzzy interface, use `:FzfLua grep_project` and all rhr project lines will be fed into fzf for searching, you can then use the exact match syntax with `'`.

Read the wiki to understand more, specifically the difference between live grep and grep
https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob

If you wish to use `ag` instead of `rg` you can easily change that by setting the `grep.cmd` opt during setup or even directly by calling `:lua require'fzf-lua'.grep({ cmd = 'ag …'. })`.

**Comment by ovidius72** [comment]
Wow, wonderful. That's exactly what I was searching for. Thank you very much.

**Comment by ibhagwan** [comment]
Ty for the update @ovidius72, closing, feel free to reopen if you need more help.
