### ISSUE TITLE
Bug: long input lines get truncated

### ISSUE THREAD

**Issue by patnr** [ibhagwan/fzf-lua#1125]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

Bash

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.43.0 (MacPorts)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

set to empty for test purpose

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

Many thanks for this great plugin!

To reproduce, run `:lua require('fzf-lua').files({ cmd = "python -c 'print(list(range(10000)))'" })`
and input query `'841` (or any number above 840) . Doing so should yield a match but returns empty.

The issue also happens for other providers, like `grep`.

It does not arise with pure fzf, i.e. `python -c 'print(list(range(10000)))' | fzf`

**Comment by ibhagwan** [comment]
Hi @patnr, this limitation is by design when processing commands via the fzf-lua command proxy, the reason is that in order to process items by line (prefixing with icons, etc), the line data has to be saved in between FPC calls until a `\n` is found, this causes significant delay, take a look at #185 and #211.

This is the code that truncated the line:
https://github.com/ibhagwan/fzf-lua/blob/f430c5b3b1d531cff8d011474461ea3090e932e2/lua/fzf-lua/libuv.lua#L240-L250

This can be avoided by disabling all icons (using `live_grep_native` for example), the command will then avoid the processing and pass the data as is to fzf.

Unfortunately I couldn’t find a better solution to the above other than truncating the line (mind you at 65k bytes), I’d welcome any ideas/PRs that don’t destroy performance completely.

**Comment by ibhagwan** [comment]
> Many thanks for the quick reply and clarification. I disabled those options and now it works!

Great, Ty for the update!

> Unfortunately I couldn’t find a better solution to the above other than truncating the line (mind you at 68k bytes), I’d welcome any ideas/PRs that don’t destroy performance completely.

My offer still stands, improvements are welcome if you can think of such :)
