### ISSUE TITLE
Customization options not taking effect?

### ISSUE THREAD

**Issue by haze** [ibhagwan/fzf-lua#115]
Sorry to jumble two issues into one but I feel like some options aren't being taken into consideration here during the plugin's setup phase.

Here is my current configuration:

```lua
require'fzf-lua'.setup {
  winopts = {
    split = 'new',
    win_row = 1,
  },
  preview_border = 'noborder',
}
```

Yet, when opening any FZF buffer (mainly live_grep & files) it looks like this:

<img width="1346" alt="CleanShot 2021-09-07 at 17 04 47@2x" src="https://user-images.githubusercontent.com/15584994/132410760-8d96ba1c-bba5-4546-bd01-8fadf946da3c.png">

I'm wondering if I'm even setting the right options here. Here is what I'd like:

1. The FZF preview/window to create a new split at the **bottom**, not the top
2. The preview window to not have a border

**Comment by ibhagwan** [comment]
Yes, it’s a bit confusing because fzf-lua has many different options as well as different previewer options, to achieve the same result using the nvim previewer or the fzf previewer will take different options.

ok so first things first when you set `winopts.split` most other window options are ignored, it just runs the command as a replacement for window creation so in your case running `new` will depend on your neovim setup where the new window goes, if you want to be more specific you can set `split` to `aboveleft new` or `belowright new`.

The above sorts out the fzf window location, now regarding the previewer: the default previewer is not the fzf previewer and draws the window and border manually using the `win_border` characters, take a look at its options under `previewers.builtin`, however if you set `default_previewer = "bat"` (or `cat` if you don't have `bat` installed) that will use the `preview_border` setting and will be applied.

To summarize, you have 2 options to achieve what you want, one will use the builtin previewer with neovim syntax highlighting and the other will use `bat` for syntax highlighting, try both of these setups and choose whichever works best for you:

First option with the default previewer (neovim syntax highlighting):
```lua
  require'fzf-lua'.setup({
    winopts = {
      split            = "belowright new",
      win_border       = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
    },
  })
```

Second option with `bat` as previewer:
```lua
  require'fzf-lua'.setup({
    winopts = {
      split            = "belowright new",
    },
    preview_border     = 'noborder',
    default_previewer  = "bat",
  })
```

I apologize for the confusion I added so much code recently and so much functionality and I can't find the time to get to the wiki part of the project :-)

**Comment by haze** [comment]
Wonderful! Thanks so much for the hasty response, it means a lot.

**Comment by ibhagwan** [comment]
You're welcome :-)
