### ISSUE TITLE
Bug: No matching autocommands: filetypedetect BufRead

### ISSUE THREAD

**Issue by homerours** [ibhagwan/fzf-lua#1166]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

0.9.5

### Fzf version (`fzf --version`)

0.48.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

Hello,
First of all, thank you for maintaining this wonderful plugin !
I am experiencing some issues using `fzf_live`. When running
```
:lua require('fzf-lua').fzf_live(function(q) return {"hello"} end, {exec_empty_query = true})  
```
fzf-lua opens its usual search window, with an entry "hello" (as expected), but with an error
```
No matching autocommands: filetypedetect BufRead
```
right below. Am I doing something wrong here? Thank you!

**Comment by ibhagwan** [comment]
This seems to be an upstream ussue when using `vim.g.did_load_filetypes=1` on load, using `0.9.5` I am getting the same warning as you but with the latest nightly it works as expected.

I modified https://github.com/ibhagwan/fzf-lua/commit/5104ac1744b92f888ef9f1d4bb6ff14e700c7a37 introduced by #1089 to be included only when neovim >= v0.10.

With https://github.com/ibhagwan/fzf-lua/commit/cb208cd24bacac5893249ea3a8624d705d2135f9, it should work as expected, lmk if otherwise.

**Comment by homerours** [comment]
Thank you very much, your commit fixed it 🎉

**Comment by ibhagwan** [comment]
> Thank you very much, your commit fixed it 🎉

Ty for the update and the kind words @homerours!
