### ISSUE TITLE
Bug: Formatted `path.filename_first` not working with profile "max-perf"

### ISSUE THREAD

**Issue by adambarjo** [ibhagwan/fzf-lua#1178]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.51 (0.51.0)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

n/a

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
  "max-perf",
  defaults = {
    formatter = "path.filename_first",
  },
})
```

### Describe the bug / steps to reproduce

![image](https://github.com/ibhagwan/fzf-lua/assets/47948089/13b1cbf1-ddd2-45ef-8256-083e207f1800)

Using the "max-perf" profile with the new "path.filename_first" formatter shows ANSI escape codes in the file path where it would usually show italic text.

Without max-perf:
![image](https://github.com/ibhagwan/fzf-lua/assets/47948089/7c00d583-9ef5-4d8a-bc63-820e5a758b49)

**Comment by ibhagwan** [comment]
This is somewhat by design, max perfomance disables anything that would introduce an overhead, no icons, no colors, no ansi escape sequences, IMHO it doesn’t make any sense to use max perf and then add additional string manipulations.

If you still want to make this work, either disable the directory part highlight group `FzfLuaDirPart` (therefore disabling the ansi escape sequence), you can test it with:
```lua
:FzfLua files hls.dir_part=false
```

Alternatively, you can restore ansi for files with:
```lua
require("fzf-lua").setup({
  "max-perf",
  defaults = {
    formatter = "path.filename_first",
  },
  files = { fzf_opts = { ["--ansi"] = true } },
})
```
