### ISSUE TITLE
Bug: Can’t go back to file start with `preview-page-up`

### ISSUE THREAD

**Issue by boltlessengineer** [ibhagwan/fzf-lua#1220]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-93+g1c73bd7d2

### Fzf version (`fzf --version`)

0.29

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

I can’t go up to file start again after scrolling down a bit.

1. find any file with scrollable amount of lines with `:FzfLua files`
1. scroll down with `preview-page-down`
2. try scroll up to file start with `preview-page-up`

**Comment by ibhagwan** [comment]
Does it scroll up a bit and just doesn’t go to the file start or the `shift-up` keybind doesn’t work at all?

**Comment by boltlessengineer** [comment]
It does go up a bit and stuck at some point. `shift-up` keybind is working.
Seems like it can’t go up more if there are less than half page lines left.

**Comment by ibhagwan** [comment]
> It does go up a bit and stuck at some point. `shift-up` keybind is working. Seems like it can’t go up more if there are less than half page lines left.

The preview scroll is performed by sending ctrl-f/ctrl-b for page and ctrl-d/u for half page, it’s probably related to the editor’s behavior in such cases, I’ll check what can be done (maybe `scrolloff`).

**Comment by ibhagwan** [comment]
@boltlessengineer, in the past the code used only `ctrl-u|d` to scroll by half pages, recently a PR (#1150) by @toupeira changed this the default to full pages up/down `ctrl-b|f`, turns out `ctrl-b` is not like ctrl-u, try to ctrl-b at the first page of any buffer, it goes to the bottom of the page and never goes up to line 1.

This is now handled in https://github.com/ibhagwan/fzf-lua/commit/b92220ec838c195eb1c711daa69c905b1d7b8d8c and should work as expected, ty for the report!
