### ISSUE TITLE
Bug: Toggle Ignore Flag does not work as expected

### ISSUE THREAD

**Issue by phongnh** [ibhagwan/fzf-lua#1257]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.53.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=16

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  files = {
    toggle_ignore_flag = "--no-ignore-vcs"
  }
})
```

### Describe the bug / steps to reproduce

Step to reproduce:
- First, open files popup it respects .gitignore correctly
- Press <C-g>, files popup is now disable .gitignore
- Press <C-g> again, files popup it stills disable .gitignore (this should toggle ignore flat correctly)
- Press <C-g> again, files popup it respect .gitignore 

Here are debug logs when opening files popup

![image](https://github.com/ibhagwan/fzf-lua/assets/438791/c3ad4c36-da1a-413f-a6fd-738b859a17a7)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/946ec5936f41142c9cac3d5437a9901bad55ff59

Ty for the report @phongnh, yet another `gsub` tuple return value woe, shoud be fixed with the above commit, tested with:
```lua
:FzfLua files toggle_ignore_flag=--no-ignore-vcs debug_cmd=false debug=true
```

Switch works properly now:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/bbcaa389-d43d-4314-a54e-ed7a1395b2cd)

One `ctrl-g`:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/3e9011d2-93ef-4254-8674-96e502496b26)

Two `ctrl-g`'s:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/a338808f-3415-4550-9f9f-dd8d8fac8d4a)
