### ISSUE TITLE
Jump to LSP definition when there is only one definition

### ISSUE THREAD

**Issue by Iron-E** [ibhagwan/fzf-lua#13]
When using `require('fzf-lua').lsp_references`, `lsp_definitions`, etc, sometimes there is (correctly) only one entry in the fuzzy-finder window. Rather than have users press `<CR>` on this singular entry, can we make it so that the entry is automatically selected?

For example, this `DynError` only has one definition across my project:

![single-entry-example](https://user-images.githubusercontent.com/36409591/126536820-362ffdee-a043-4eb9-8c90-e214d94c1e76.png)

When using `lsp_definitions`, is it possible to skip the fuzzy-finder window and jump to the definition?

**Comment by ibhagwan** [comment]
It’s actually on my TODO list. Since all my LSP calls are asynchronous (including definitions) the fzf term window is already open and the jump to definition was causing some issues, looks the [comment on lsp.lua:18](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L18).

You just gave me the push I need to solve it, I’ll keep you posted :)

**Comment by ibhagwan** [comment]
For the sake of consistency I left the default behavior as is, I added the option to jump to a single result in `lsp_references`, `lsp_definitions`, `lsp_declarations`, `lsp_typedefs` and `lsp_implementations`, use the below option to enable it:

```lua
:lua require('fzf-lua').lsp_definitions({ jump_to_single_result = true })
```

**Comment by Iron-E** [comment]
This is great! Thank you.
