### ISSUE TITLE
Feature: add ability to pass options to lsp_code_actions

### ISSUE THREAD

**Issue by quolpr** [ibhagwan/fzf-lua#1307]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I want to be able to pass params to this line
https://github.com/ibhagwan/fzf-lua/blob/41ea49cfc1b3f0586753bbeb7850474f28dc22cf/lua/fzf-lua/providers/lsp.lua#L940

I stumbled with these 2 bugs https://github.com/neovim/neovim/issues/21985 + https://github.com/neovim/neovim/issues/29500 and I am fixing it with this approach:

```
map('<leader>ca', function()
  vim.lsp.buf.code_action {
    context = {
      diagnostics = get_diagnostic_at_cursor(),
    },
    filter = function(action)
      if string.find(action.title, 'to user settings') then
        return false
      end

      return true
    end,
  }
end, '[C]ode [A]ction')
```

Plus, I also use filter.

So, when I change it to `require('fzf-lua').lsp_code_actions {`, nothing works. Is it possible to add ability to pass params?

**Comment by quolpr** [comment]
Oh, and seems this part:
```
if not registered then
  -- irrelevant for code actions and can cause
  -- single results to be skipped with 'async = false'
  opts.jump_to_single_result = false
  opts.lsp_params = vim.lsp.util.make_range_params(0)
  opts.lsp_params.context = {
    -- Neovim still uses `vim.lsp.diagnostic` API in "nvim/runtime/lua/vim/lsp/buf.lua"
    -- continue to use it until proven otherwise, this also fixes #707 as diagnostics
    -- must not be nil or some LSP servers will fail (e.g. ruff_lsp, rust_analyzer)
    diagnostics = vim.lsp.diagnostic.get_line_diagnostics(core.CTX().bufnr) or {},
  }

  -- make sure 'gen_lsp_contents' is run synchronously
  opts.async = false

  -- when 'opts.async == false' calls 'vim.lsp.buf_request_sync'
  -- so we can avoid calling 'ui_select.register' when no code
  -- actions are available
  local _, has_code_actions = gen_lsp_contents(opts)

  -- error or no sync request no results
  if not has_code_actions then
    return
  end
end
```

Contains two bugs too that I described above. I am curious if it is possible to fix them too, or add arg option to work around this

**Comment by quolpr** [comment]
So, as a quick fix I made this changes:
```
opts.lsp_params.context = {
  -- Neovim still uses `vim.lsp.diagnostic` API in "nvim/runtime/lua/vim/lsp/buf.lua"
  -- continue to use it until proven otherwise, this also fixes #707 as diagnostics
  -- must not be nil or some LSP servers will fail (e.g. ruff_lsp, rust_analyzer)
  diagnostics = opts.context.diagnostics or vim.lsp.diagnostic.get_line_diagnostics(
    core.CTX().bufnr
  ) or {},
}
```
Plus
```
vim.lsp.buf.code_action(opts)
```

**Comment by ibhagwan** [comment]
I can change this line:
https://github.com/ibhagwan/fzf-lua/blob/41ea49cfc1b3f0586753bbeb7850474f28dc22cf/lua/fzf-lua/providers/lsp.lua#L940

To:
```lua
  vim.lsp.buf.code_action(opts.lsp_params)
```

And you can add whatever you want there, will that solve your issue?

**Comment by quolpr** [comment]
> And you can add whatever you want there, will that solve your issue?

I still also need these changes:
```
  diagnostics = opts.context.diagnostics or vim.lsp.diagnostic.get_line_diagnostics(
    core.CTX().bufnr
  ) or {},
```

Cause otherwise some LSP doesn't work if it will receive all code actions. 

As for
> query='!tousersettings '

That will for for me 👍

**Comment by ibhagwan** [comment]
> I still also need these changes:

You don’t need these changes, you are sending a new context which you construct yourself, that would include the `diagnostic` value in it which you should craft yourself:
```lua

require'fzf-lua'.lsp_code_actions({
    lsp_params = {
      diagnostics = <your code here>,
    },
  })
```

Which brings me to another question, `:FzfLua lsp_code_actions` is merely a shortcut to `vim.lsp.buf.code_action`, why aren’t you using `:FzfLua register_ui_select` and then you can `vim.lsp.buf.code_action` with whatever parameters you wish, since fzf-lua is registered for `ui.select` it will then be used.

> Just checked it in my config, and this setting didn't work for me

Maybe you’re misunderstanding the purpose of this and how this works, it prefills  fzf’s query with a string to be filtered, maybe you need to adjust your string? See below what should happen:

> Note the prefilled prompt text (I.e. query):

![IMG_2238](https://github.com/ibhagwan/fzf-lua/assets/59988195/2a0e3e65-69cc-43c2-8672-ca4347a5aa24)

> note the exclusion of code actions with the word `line`:

![IMG_2239](https://github.com/ibhagwan/fzf-lua/assets/59988195/020e6672-36cd-4005-aebb-3bd2ce8426a9)

**Comment by quolpr** [comment]
> You don’t need these changes

Maybe we misunderstand each other :) Without these changes, code action will not be working for me. I made screenshot with explanations, hope this will help:
<img width="780" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/7958527/2c9c0cdf-ba73-4b94-8e88-06c8423d66d9">

> Which brings me to another question, :FzfLua lsp_code_actions is merely a shortcut to vim.lsp.buf.code_action, why aren’t you using :FzfLua register_ui_select and then you can vim.lsp.buf.code_action with whatever parameters you wish, since fzf-lua is registered for ui.select it will then be used.

If you think it will be cleaner way, I will do. I was thinking about this path too, but didn't want to copy all the code, and thought that changes of 2 lines will be easier thing + will give extendibility for fzf. But if you think that this change will not work well for fzf, I will choose the register_ui_select way 🙂 

> Maybe you’re misunderstanding the purpose of this and how this works, it prefills fzf’s query with a string to be filtered, maybe you need to adjust your string? See below what should happen:

Oh, yeah, got it! I didn't notice that it is added to the input. And didn't work for me, cause actually should be `!to\ user\ settings `

**Comment by ibhagwan** [comment]
> Maybe we misunderstand each other :) Without these changes, code action will not be working for me. I made screenshot with explanations, hope this will help:

I see what you mean now

> If you think it will be cleaner way, I will do. I was thinking about this path too, but didn't want to copy all the code, and thought that changes of 2 lines will be easier thing + will give extendibility for fzf. But if you think that this change will not work well for fzf, I will choose the register_ui_select way 🙂

Technically `register_ui_select` is the “right way”,  said code (where the issue lies) is only there to check if there’s code actions in order to avoid a use case where fzf-lua automatically registers but is unable to de-register since there’s no code actions (and thus ui.select is never called), it’s basically a sort of a hack.

But why will using `register_ui_select` require you to copy code? The issue is only in the manual LSP call to `textDocument/codeAction`, if you’re calling `vim.lsp.buf.code_action` directly you avoided the issue, no?

**Comment by ibhagwan** [comment]
@quolpr, with https://github.com/ibhagwan/fzf-lua/commit/0e1ff6042ec5c033fd054148ae9f5fbd68d2d69e you can seamlessly replace your call to `vim.lsp.buf.code_actions` with `fzf_lua.lsp_code_actions`, that inclues both `context` and `filter`.

```lua
map('<leader>ca', function()
  require("fzf-lua").lsp_code_actions {
    context = {
      diagnostics = get_diagnostic_at_cursor(),
    },
    filter = function(action)
      if string.find(action.title, 'to user settings') then
        return false
      end
      return true
    end,
  }
end, '[C]ode [A]ction')
```

Note this comes with a small caveat, since LSP parameters don't support `filter` (it's a parameter only for `lsp.buf.code_action`), if your filter function ends up filtering all the actions, fzf-lua will register itself for `ui.select` but won't de-register as the interface will never open and you'll see `No code actions available`.

However, this shouldn't be an issue since my understanding you're only filtering some of the action and you can always use the `query="!to\\ user\\ settings" instead.
