### ISSUE TITLE
Feature: add support for mini.icons plugin

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1319]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-icons.md

**Comment by ibhagwan** [comment]
Already on my TODO list since I saw @echasnovski‘s  post yesterday :)

**Comment by kaiphat** [comment]
So funny community:)

**Comment by ibhagwan** [comment]
FYI, code is [almost done](https://github.com/ibhagwan/fzf-lua/tree/mini_icons) but there's an issue that requires either resolution or acceptabnce as a "known limitation", more information here: https://github.com/echasnovski/mini.nvim/issues/1007#issuecomment-2242073343

**Comment by echasnovski** [comment]
As relying on `vim.filetype.match()` won't go anywhere unfortunately (see https://github.com/echasnovski/mini.nvim/issues/1007#issuecomment-2242499529), some black magic hacker seems to be indeed needed here.

As the code is somewhat complex and I am no expert in separate libuv threads, I am afraid I can't help much. As far as I understand, the following is the main issue:

> `get_icon` call happening inside a libuv process loop, the call to `vim.filetype.match` fails with:
> ```
> Error executing luv callback:
> vim/_options.lua:150: E5560: Vimscript function must not be called in a lua loop callback
> ```
> 
> The above isn't easy to work around from the external process with `vim.schedule` and I'm not sure if there's another workaround aside > from replicating the `vim.filetype.match` code inside fzf-lua.

Here are some possible ideas on how to resolve this:
- Update upstream to either not use `vim.fn` inside `vim.filetype.match()` (like the case with [using `vim.env`](https://github.com/neovim/neovim/blob/f93ecd2760f5859fd5eeec28c7c2196ece98e9a1/runtime/lua/vim/filetype.lua#L2524), which [relies on `vim.fn.getenv()`](https://github.com/neovim/neovim/blob/f93ecd2760f5859fd5eeec28c7c2196ece98e9a1/runtime/lua/vim/_options.lua#L149)) or allow several some Vimscript functions to run in fast context (like [it was done for `vim.fn.executable()`](https://github.com/neovim/neovim/pull/28492)). The latter would need to allow at least `expand()`, `fnameescape()`, `fnamemodify()`, `did_filetype()`, `substitute()` (as far as I can tell from searching source code).
- Monkey patch `vim.filetype.match()` to perform some sort of similar actions (at least to a certain degree).
- Separate items computation and their drawing: the first might be done in separate thread while the second one - in main thread with full access to `get()` function. This might reduce the need of manually tracking both 'mini.icons' and 'nvim-web-devicons'.

**Comment by ibhagwan** [comment]
Ty @echasnovski for the insights and suggestions.

> (1) Update upstream to either not use `vim.fn` inside `vim.filetype.match()`

Given the heavy use of `vim.fn` I don’t think this is viable and I don’t see the upstream removing the fast event requirement to satisfy this issue so I think it’s pretty safe to say this option isn’t viable.

> (2) Monkey patch `vim.filetype.match()` to perform some sort of similar actions (at least to a certain degree).

I don’t like the idea of runtime hacks, it’s prone to failure on updates and additional unexpected woes. Might as well write a copy of the function with detection only by filename/ext at this point.

> (3) Separate items computation and their drawing: the first might be done in separate thread while the second one - in main thread with full access to get() function.

This will be horrendous for performance which kind of defeats the purpose of using fzf-lua, unfortunately `vim.schedule` with a coroutine is also not possible due to coroutines also not available within a luv callback.

Unfortunately, none of the available options seem attractive ATM as I do not wish to maintain a list of extensions/filenames and a copy of `vim.filetype.match` inside fzf-lua.

I guess I’ll have to do some more thinking on this issue or release it with a known limitation (which would be similar to using the devicons mock functions).

**Comment by ibhagwan** [comment]
Needs more testing but the below seems to do the trick of enabling `vim.filetype.match` without E5560:
https://github.com/ibhagwan/fzf-lua/blob/3120b96639af9a12e8a2b8bac279c89cc3c20561/lua/fzf-lua/path.lua#L535-L571

![IMG_2342](https://github.com/user-attachments/assets/96d47476-55e1-45bc-93b5-2e646851b392)

**Comment by echasnovski** [comment]
> Given the heavy use of `vim.fn` I don’t think this is viable and I don’t see the upstream removing the fast event requirement to satisfy this issue so I think it’s pretty safe to say this option isn’t viable.

It's worth at least asking if it is even on the table. I'll try at least that.

> This will result in horrendous performance which kind of defeats the purpose of using fzf-lua ...

In my experience with 'mini.pick' drawing only items that should be on the screen is pretty fast enough. It usually means drawing about 30-50 lines which is a matter of 10-100 microseconds with all highlighting (at least after 'mini.icons' caches it's results). The downside is that it needs separate scroll implementation, but maybe there already is one in 'fzf-lua'.

**Comment by ibhagwan** [comment]
> In my experience with 'mini.pick' drawing only items that should be on the screen is pretty fast enough. It usually means drawing about 30-50 lines which is a matter of 10-100 microseconds with all highlighting (at least after 'mini.icons' caches it's results). The downside is that it needs separate scroll implementation, but maybe there already is one in 'fzf-lua'.

That’s not the issue, fzf-lua isn’t responsible for drawing, fzf (the binary) is, having to halt the process for a query would result in significant delays.

**Comment by echasnovski** [comment]
> That’s not the issue, fzf-lua isn’t responsible for drawing, fzf (the binary) is, having to halt the process for a query would result in significant delays.

Ah, I see. Then indeed it is reasonable to expect that making the drawing use Neovim's plugin that tracks icons would require some dark magic.

**Comment by ibhagwan** [comment]
> > That’s not the issue, fzf-lua isn’t responsible for drawing, fzf (the binary) is, having to halt the process for a query would result in significant delays.
> 
> Ah, I see. Then indeed it is reasonable to expect that making the drawing use Neovim's plugin that tracks icons would require some dark magic.

I’m quite content with the solution I came up with, a bit of a monkey patch but not overly complex that it would be a problem, I started adding some testing for it in `minicons_spec.lua` and it works S expected. Tomorrow I’ll do some more extensive testing and hopefully release it.

**Comment by ibhagwan** [comment]
Took longer than expected due to `vim.filetype.match` shenanigans which made this a bit more complicated, especially from the external process, seems to be working well, similarly to `mini.icons` the first time new files are being detected with `vim.filetype.match` there might be a noticeable lag depending on the extension (try it out with `foo.old` fike which exhausts all pattern matching interanlly) but after the first time the extension/filename is cached and should be faster.

To use, set `file_icons="mini"` where applicable, e.g:
```lua
require("fzf-lua").setup({
  files = { file_icons = "mini" },
})
```

To set as default for all file pickers:
```lua
require("fzf-lua").setup({
  defaults = { file_icons = "mini" },
})
```

Or set temorarily set via call args:
```lua
:lua require("fzf-lua").files({ file_icons = "mini" })
:FzfLua files file_icons=mini
```

**Comment by echasnovski** [comment]
Thanks for the colossal amount of work!

I tested on latest `main` and it indeed seems to work better than with `MiniIcons.mock_nvim_web_devicons()`.

However... The past week I was implementing/profiling/reimplementing/and so on a sequence of updates, most of them slightly change how "file" icon is resolved. There will be two major changes:
- Full input path will be used in `vim.filetype.match()`, not only basename. This is to allow some complex cases which depend on parent directories, like echasnovski/mini.nvim#1017.
- Users will be able to control whether extension should be considered or not. This is again to fully allow previous use case.
- Path extensions will be tried directly via `MiniIcons.get()` and accepted only if output is some recognized extensions (i.e. not a fallback icon). This will (mostly) improve overall speed due to caching *all* possible extensions, not only manually tracked ones.

I'll add a link to more details/commits when they are released (hopefully today).

**Comment by echasnovski** [comment]
Changes are now on latest `main`. Here is [a bit more info](https://github.com/echasnovski/mini.nvim/issues/1007#issuecomment-2252493138). With them, `:FzfLua files` uses only extension to determine icon data and does not recognize `config.use_file_extension`.

You can test it like this:

- Have [this 'mini.icons' setup](https://github.com/echasnovski/mini.nvim/blob/fb2cbeb4bff225e3c7907cfcd95ebf2a4492f8b6/doc/mini-icons.txt#L263-L266).
- Create 'queries/hello.scm' file and another 'hello.scm' file not in 'queries/' directory. Try using `:FzfLua files` to see what icons they use.
 
Here is how it looks in 'mini.pick' (and similarly in 'mini.files'):

![screenshot_2024-07-26_14:16:29](https://github.com/user-attachments/assets/c6b85bc0-2082-4f33-9189-9dae105b5b1e)

And here is how it looks with latest 'fzf-lua':

![screenshot_2024-07-26_14:16:44](https://github.com/user-attachments/assets/b1d34e5f-cace-42be-9717-b27e36c39924)

------

In the end, this is not big deal, just a cherry on top to allow more targeted icon definition. Having extension icon used is not wrong per se here.

**Comment by ibhagwan** [comment]
> I tested on latest main and it indeed seems to work better than with `MiniIcons.mock_nvim_web_devicons()`

Correct, since fzf-lua uses its own query logic/code mock could only be considered an interim solution, it wil only be able to resolve known extensions and files returned from `MiniIcons.list` and does not have the `vim.filetype.match` fallback.

I read the changes you’ve done in details, here’s my 2 cents about it in regards to fzf-lua ( it’s important to remember fzf-lua never calls `MiniIcons.get` but rather has its own implementation):

> Full path support now not only for user convenience but also has a meaningful outcome: it will be used in vim.filetype.match() as is (not only basename, as was before)

While I can easily do the same in fzf-lua, as you also wrote in the commit messages, each additional call to `vim.filetype.match` is an additional performance hit (quite apparent btw) and if using fullpath caching it’s also an additional memory hog, for now my logic is somewhat simple, check the base name / extension and cache if found, if not found I also cache the extension with the default icon to prevent more calls to vim.filetype.match.

I don’t think this would be a big deal but I would have to test this for the performance impact first.

> - Extension detection now is done directly via MiniIcons.get('extension', ext): if it is a recognized extension (i.e. not fallback)

Due to the reasons I mentioned above this was already implemented in fzf-lua to begin with.

> - Users can now have full control over which extensions will be even considered during file resolution. This can be done through [config.use_file_extension](https://github.com/echasnovski/mini.nvim/blob/fb2cbeb4bff225e3c7907cfcd95ebf2a4492f8b6/doc/mini-icons.txt#L239)

From all the listed changes this is the one I have most qualms about, the headless fzf-lua wrapper doing the icon matching never calls `MiniIcons.get` and has no awareness of this custom function, while I can potentially pass the function byte code (using `string.dump`) over RPC this would bring about other issues and limitations (not being able to require other modules in the function, etc).

> In the end, this is not big deal, just a cherry on top to allow more targeted icon definition, Having extension icon used is not wrong per se here.

I agree and therefore I believe in the context of fzf-lua it is best to **not support `config.use_file_extension` and leave it as a known limitation**.
