### ISSUE TITLE
lsp_live_workspace_symbols error

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#137]
Receiving this error when utilizing lsp_live_workspace_symbols

```
Error executing vim.schedule lua callback: ...s/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:391: bad argument #1 to 'ipairs' (table expected, got function)
```

This is when browsing C code with `clang`

**Comment by ibhagwan** [comment]
> Receiving this error when utilizing lsp_live_workspace_symbols
> 
> ```
> Error executing vim.schedule lua callback: ...s/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:391: bad argument #1 to 'ipairs' (table expected, got function)
> ```
> 
> This is when browsing C code with `clang`

I don’t think this is specific to C or `clang`, seems like the code is going through the wrong route and I’m not sure why.

While I’m trying to figure this out can you post the lsp section of your config from `setup()`? Also, do you call live symbols with any added parameters?

**Comment by ibhagwan** [comment]
Ok turns out it was a C specific issue, that is due to the fact that (apparently) C language servers (I used ccls for my test) return an empty result set for workspace symbols with an empty query, that in turn was confusing my code :-)

It should be ok now, note that `live_lsp_workspace_symbols` opens with an empty result set but should start populating once you start typing, this is the equivalent to Telescope's `lsp_dynamic_workspace_symbols`

**Comment by ldelossa** [comment]
Youre too fast, didnt even get a chance to respond ;). Thanks!

**Comment by ibhagwan** [comment]
I hate bugs :-)
