### ISSUE TITLE
Bug: `toggle_ignore` action on `live_grep` clears the input

### ISSUE THREAD

**Issue by s1n7ax** [ibhagwan/fzf-lua#1385]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

NixOs

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.1

### Fzf version (`fzf --version`)

sk 0.10.4

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{
  grep = {
    actions = {
      ['ctrl-g'] = { require('fzf-lua.actions').toggle_ignore },
    },
  },
  winopts = {
    preview = {
      delay = 0,
    },
  },
  fzf_bin = 'sk',
  keymap = {
    fzf = {
      ['ctrl-e'] = 'up',
      ['ctrl-n'] = 'down',
    },
  },
}
```

### Describe the bug / steps to reproduce

When using `live_grep`, I have set `toggle_ignore` action. When using the same feature in `files` search it switches the serching mode but keep the currently entered text. However, live grep clears the user entered text while switching to no gitingnore mode.

https://github.com/user-attachments/assets/23851bdf-b7bb-41b9-9774-5cfba8b9540a

**Comment by ibhagwan** [comment]
That’s because you’re using `sk` as the binary, with skim, live grep has to use `--interactive` which prints the wrong query on output (bug) so it cannot be saved.

You’re welcome to open a bug upstream but it seems like an abandoned project, more so, there are many great features added in the last year that make the UX more enjoyable (seamless reloads, etc), I recommend switching back to fzf, there is not a single area where sk supreceds fzf.

**Comment by ibhagwan** [comment]
Here’s where this bug is mentioned in code comments:
https://github.com/ibhagwan/fzf-lua/blob/bb52eebe56c5248b80899748b2dbdefdd513cade/lua/fzf-lua/core.lua#L446-L452
