### ISSUE TITLE
Bug: fzf accept action binded to custom key doesn't work

### ISSUE THREAD

**Issue by monkoose** [ibhagwan/fzf-lua#1404]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.54.3

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--pointer=● --marker=▶ --bind "ctrl-/:toggle-preview,alt-i:toggle-all,ctrl-n:preview-page-down,ctrl-p:preview-page-up,ctrl-l:accept,ctrl-r:clear-screen,alt-k:next-history,alt-j:previous-history,ctrl-alt-j:page-down,ctrl-alt-k:page-up" --height 40% --layout=reverse --tabstop=2 --color=hl:#f158a6,fg+:#b8af96,hl+:#f158a6,bg+:#3b312b,border:#40362f,gutter:#1f1a17,pointer:#d3c94b,prompt:#838bb4,marker:#d24b98,info:#70a17c,spinner:#e35b4b,query:#c57c41 --info=inline --margin=0,1,0,0 --prompt=">> " --history=/home/monkoose/.cache/.fzf_history --history-size=100

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
Reproducible with mini.sh, so not related.
```

### Describe the bug / steps to reproduce

My FZF_DEFAULT_OPTS using --bind "ctrl-l:accept", after some multiline commits 9ecc8f6a6555cd3988c21480069aa5da001cd9df it doesn't accept the entry and echoes with `[Fzf-lua] unsupported action: 'news                                                  news.txt /usr/share/nvim/runtime/doc/news.txt', type:nil` (as example for searching neovim help for "news" query). Seems like following commit 993fce4991b28064eb3f34146c51ee85ca808135 doesn't fix the issue either.
Last working commit is 2e88254c2045e14c712ee09f1e461c6056a2b18c

Also`lua print(vim.env.FZF_DEFAUL_OPTS)` is more correct than `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`, because personally as the habit from vim days I change vim.env.FZF_DEFAULT_OPTS in my config and later doesn't detect this.

**Comment by ibhagwan** [comment]
> My FZF_DEFAULT_OPTS using `--bind "ctrl-l:accept"`

The changes in the commits you’ve linked enable finer level of customization which is needed for actions that contains prefix / postfix (e.g. `select-all+`)  but unfortunately I couldn’t use `--expect` anymore which would have prevented this issue due to changes upstream that were later reverted, see https://github.com/junegunn/fzf/issues/3810.

The fix in https://github.com/ibhagwan/fzf-lua/commit/993fce4991b28064eb3f34146c51ee85ca808135 will only work if you add `['ctrl-l'] = 'accept'` to `keymap.fzf`, if this isn’t an acceptable solution I can add the same fix to editing the variable I send to the fzf process (which is already edited due to preview conflicts):
https://github.com/ibhagwan/fzf-lua/blob/8423be12f3c1f190792e0f529dbfaf63e4816d3e/lua/fzf-lua/fzf.lua#L243-L259

> Alsolua print(vim.env.FZF_DEFAUL_OPTS) is more correct than :lua print(os.getenv('FZF_DEFAULT_OPTS')), because personally as the habit from vim days I change vim.env.FZF_DEFAULT_OPTS in my config and later doesn't detect this.

Are you certain about this? My testing shows these are interchangeable as one changes the other but I might be wrong (I’ll have to fix the code I liked as it’s also using `os.getenv`).

**Comment by monkoose** [comment]
> Are you certain about this? My testing shows these are interchangeable as one changes the other but I might be wrong (I’ll have to fix the code I liked as it’s also using os.getenv).

Oh, you are right. Seems like I overlooked a few options the first time I used this two commands. So nevermind, sorry for false statement.

**Comment by ibhagwan** [comment]
> Feel free to close this issue, if you haven't found better solution.

Already adding the code to parse `FZF_DEFAULT_OPTS` not a big deal.

**Comment by ibhagwan** [comment]
Actually, there are so many edge cases with this... `accept` in the same `--bind` string, does it have a `print` action before, etc, etc - I don't think it's worth it for such a simple fix.

Closing
