### ISSUE TITLE
Bug: grep_CWORD not finding relevant results for word when used in PHP synatx

### ISSUE THREAD

**Issue by chrissound** [ibhagwan/fzf-lua#1432]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Nixos

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.7.0

### Fzf version (`fzf --version`)

0.30.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)
```

### Describe the bug / steps to reproduce

If I use `:FzfLua grep_cWORD` I don't see the expected results if it's to search the word under the cursor being `MappingProductMeta`.

If I enable regex mode it seems to look for the following:
(^|\s)MappingProductMeta($|\s)

This does not seem to find results if is used in PHP code like `new ExtraTypes\MappingProductMeta();`.

**Comment by chrissound** [comment]
```
M.grep_cWORD = function(opts)
  if not opts then opts = {} end
  opts.no_esc = true
  -- match neovim's WORD, match only surrounding space|SOL|EOL
  opts.search = [[(^|\s)]] .. utils.rg_escape(vim.fn.expand("<cWORD>")) .. [[($|\s)]]
  return M.grep(opts)
end
```

Seems to work by instead just doing 
```
  opts.search =  utils.rg_escape(vim.fn.expand("<cWORD>"))
```

**Comment by ibhagwan** [comment]
This isn’t a bug but rather by design, the fact there isn’t a backspace before the start of the searched word makes it so the regex won’t match, this was a compromise that works for 99% of the cases to mimic the behavior of `grep_cword` which uses word boundaries with `\b<word>\b` (which would similarly fail in your case).

Both grep cword/cWORD are simple synonyms to grep with the regex set as the search term, if you don’t want to use the regex delimiters set your key map to this instead:
```lua
:lua require'fzf-lua'.grep({ search = vim.fn.expand("<cWORD>") })
```
