### ISSUE TITLE
Handling long filenames with preview

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#151]
Hello, 

When file name is a bit long it can cut off symbol searches. See screenshot. 
![image](https://user-images.githubusercontent.com/5642902/134422977-0d65d5fe-da34-437a-bb2a-5fdb6ed26c10.png)

Any ideas on how to handle this better? I'd like to see the symbols all the time regardless of the length of the filepath.

**Comment by ibhagwan** [comment]
This behavior is controlled by fzf, perhaps there is an fzf flag to disable this?

Otherwise I’d have to shorten the file names and then try to expand them again on preview/selection, too much work for this minor inconvenience honestly.

**Comment by ibhagwan** [comment]
Didn’t try it but how does this behave?

```lua
lsp_workspace_symbols({ fzf_opts = { ['—keep-right'] = '' } })
```

**Comment by ldelossa** [comment]
@ibhagwan that fails to open the fzf dialogue. 

I understand this is minor. Curious if placing the preview window *always* on the bottom is the easy solution?

**Comment by ibhagwan** [comment]
> @ibhagwan that fails to open the fzf dialogue.

That's because I posted from mobile and the `--` turned out to be something else, just tried this and it does the job:
```lua
:lua require('fzf-lua').lsp_workspace_symbols({ fzf_opts = { ['--keep-right'] = '' } })
```

![screenshot-1632351163](https://user-images.githubusercontent.com/59988195/134432471-3a38ccbe-970a-4696-a355-7999fd7c55d6.png)


> I understand this is minor. Curious if placing the preview window _always_ on the bottom is the easy solution?

You could easily do that by sending `preview_layout = 'vertical'`, that will force the previewer to be at the bottom (`flexible` is controlled by nvim width).

**Comment by ldelossa** [comment]
Okay, I think this is a fine solution. Unless there is a way to use "flex" and have it take path length into account?

**Comment by ibhagwan** [comment]
> Okay, I think this is a fine solution. Unless there is a way to use "flex" and have it take path length into account?

That can be done but IMO it's a very non-intuitive behavior, plus I'll have to delay rendering until all entries are displayed as I'd have to check first that the longest entry isn't longer than a certain length, causing a UI hang until all lines are rendered, or alternatively triggering a layout change mid way, far from optimal.

I think the `--keep-right` does the job no?

**Comment by ldelossa** [comment]
better, but always vertical is better. Here is screenshot with `--keep-right`

![image](https://user-images.githubusercontent.com/5642902/134436871-a5d6cb80-b9ff-4809-aa01-01e0036ccbd7.png)

**Comment by ibhagwan** [comment]
I see, seems functional enough.

**Comment by ibhagwan** [comment]
Btw, I noticed you’re using `bat` previewer, out of curiosity, do you prefer that to the built in?

**Comment by ldelossa** [comment]
@ibhagwan I don't really know the difference between them. Is there a reason to prefer the built in?

**Comment by ibhagwan** [comment]
> @ibhagwan I don't really know the difference between them. Is there a reason to prefer the built in?

The main reason would be treesitter highlights, the syntax highlighting would be done by nvim and match your current color scheme other than using the bat color scheme.

in addition it as the ability to expand to max size by pressing (default bind `F2`).

**Comment by ldelossa** [comment]
thanks! just switched over and everything works great. Having the preview match my theme is much better.

**Comment by ibhagwan** [comment]
> thanks! just switched over and everything works great. Having the preview match my theme is much better.

Great! Forgot to mention you also get the benefit of highlighting the exact column where the match hits (not just the line), if you’d like to change these colors look for `hl_cursor` and `hl_cursorline` under `previewers.builltin`.

**Comment by ibhagwan** [comment]
FYI, incase you're interested the last few commits added new functionalities that would help you with the above issue in an indirect manner.

The new functionalities enable you to do 2 things:
- Toggle the preview window **and fzf window** fullscreen
- Rotate the preview window clockwise/counter-clockwise

So if you prefer you can stay in horizontal layout and when the lines are long and require more screen real-estate you can rotate it clockwise (`<F6>` by default) to switch the preview up (or `<F5>` to switch the preview down).

Note that if you wish to changes those, the keybinds were migrated and are now specified in `keymap.builtin` (instead of `previewers.builtin.keymap`).

**Comment by ldelossa** [comment]
This is great. The rotate functionality will work for m issue.
