### ISSUE TITLE
Provide option for creating and switching to a new buffer when searching from unsaved buffer.

### ISSUE THREAD

**Issue by winston0410** [ibhagwan/fzf-lua#156]
Right now fzf-lua will not create and switch to the buffer of the search result, when the search is started from an unsaved buffer. Just read the code there and I am unable to find something like `:buffer` to override, so I will open an issue here for help.  Not sure if it is an upstream issue.

**Comment by ibhagwan** [comment]
I'm not sure what you mean, I just tried running a live grep from an unsaved buffer and it worked, perhaps I'm misunderstanding the issue?

What the output of `:set hidden?` in your nvim? if the result is set to `nohidden` this might explain it as it will try to unload the buffer which it cannot do since it is unsaved which can cause this issue (I have `vim.o.hidden = true` set in my `init.lua`).
