### ISSUE TITLE
:Lines searches through open windows not buffers

### ISSUE THREAD

**Issue by CuriousSyrup** [ibhagwan/fzf-lua#159]
Seems like 'lines' only searches through visible buffers not through all open buffers. If you don't have a buffer in a split, it doesn't search through it. 
I like this functionality, because sometimes this is what I want. 
But it would be nice to have a possibility to search through all open buffers, regardless if they are visible on the screen or not.
Maybe some kind of switch would be useful, or maybe another command...

**Comment by ibhagwan** [comment]
It should work similar to `fzf.vim` `:Lines`, if it doesn’t show hidden buffers this is an error, I’ll check.

**Comment by ibhagwan** [comment]
Will you help me reproduce this? I just tried running lines with a single window, I see all the hidden buffers with no issue:

![screenshot-1633125538](https://user-images.githubusercontent.com/59988195/135690660-5393b360-70d2-49d1-9831-0c1a14485f8f.png)

**Comment by CuriousSyrup** [comment]
`nvim --version` = NVIM v0.5.0

Minimal vimrc to reproduce the issue:
```vim
call plug#begin(stdpath('data'))
Plug 'vijaymarupudi/nvim-fzf'
Plug 'ibhagwan/fzf-lua'
call plug#end()
```

1. Create 2 identical files in the test dir.
2. Open both files with vim.
3. With only the first file visible execute `:FzfLua lines` or `:lua require('fzf-lua').lines()`
4. Show the second file in the split and execute `:FzfLua lines` or `:lua require('fzf-lua').lines()`
5. Close the window with the first file and execute `:FzfLua lines` or `:lua require('fzf-lua').lines()`

Here is the video of the screen.
![fzf-lua_lines](https://user-images.githubusercontent.com/77532080/135716486-e64281c6-e980-4433-a733-552805d89b7f.gif)

**Comment by ibhagwan** [comment]
Ty!

The issue here seems to be that you're using (the default) `nohidden` option, meaning buffers that are switched out of are unloaded so fzf-lua cannot get the buffer lines into fzf, in order to solve this you need to enable the hidden option in your config using `:set hidden`.

Here's the explanation from nvim help file:
```help
'hidden' 'hid'          boolean (default off)
                        global
        When off a buffer is unloaded when it is abandoned.  When on a
        buffer becomes hidden when it is abandoned.  If the buffer is still
        displayed in another window, it does not become hidden, of course.
        The commands that move through the buffer list sometimes make a buffer
        hidden although the 'hidden' option is off: When the buffer is
        modified, 'autowrite' is off or writing is not possible, and the '!'
        flag was used.  See also windows.txt.
        To only make one buffer hidden use the 'bufhidden' option.
        This option is set for one command with ":hide {command}" :hide.
        WARNING: It's easy to forget that you have changes in hidden buffers.
        Think twice when using ":q!" or ":qa!".
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9a24d8e4660b9f2e9f20dbb5464468884bbd1889

This adds the option for `lines` to work even with `set nohidden`, instead of reading the lines from the buffer (impossible since it's unloaded) fzf-lua will read the lines from the file on disk.

With `nohidden` set, it's impossible to switch from buffers in a "dirty" state (the buffer must be written to disk first with `:w` or `:update`) so this should work fine regardless of what option you use.

As a side note, unless you have severe memory limitation I don't see any downside to using `set hidden` and it's pretty much common practice - [an interesting discussion regarding the `hidden` option](https://www.reddit.com/r/vim/comments/kg3q9h/do_you_use_set_hidden_or_not/).

**Comment by CuriousSyrup** [comment]
even with `:set hidden` option, when I open 2 identical files and immediately start searching, it will display results only from the 1st one.
And only when I display the second buffer it will start searching through the second buffer. After these actions I can display only the first buffer and it continues to search through all 2 buffers.
To conclude - I have to display each buffer at least once for `lines` to start searching in these buffers.
I can make another video of the screen if the above is not very clear.

**Comment by ibhagwan** [comment]
> even with `:set hidden` option, when I open 2 identical files and immediately start searching, it will display results only from the 1st one. And only when I display the second buffer it will start searching through the second buffer. After these actions I can display only the first buffer and it continues to search through all 2 buffers. To conclude - I have to display each buffer at least once for `lines` to start searching in these buffers. I can make another video of the screen if the above is not very clear.

Did you try the latest commit?

**Comment by CuriousSyrup** [comment]
Decided not to wait with the video. Here it is:
![fzf-lua_lines_hidden](https://user-images.githubusercontent.com/77532080/135741411-506790b3-2089-4ee2-a50f-2a60adba23a5.gif)

**Comment by CuriousSyrup** [comment]
> > even with `:set hidden` option, when I open 2 identical files and immediately start searching, it will display results only from the 1st one. And only when I display the second buffer it will start searching through the second buffer. After these actions I can display only the first buffer and it continues to search through all 2 buffers. To conclude - I have to display each buffer at least once for `lines` to start searching in these buffers. I can make another video of the screen if the above is not very clear.
> 
> Did you try the latest commit?

Latest commit fixes the issue for me. Though I'm not so sure if I support the idea of constantly reading all open buffers from disk each time I use `lines`.

**Comment by ibhagwan** [comment]
> > > even with `:set hidden` option, when I open 2 identical files and immediately start searching, it will display results only from the 1st one. And only when I display the second buffer it will start searching through the second buffer. After these actions I can display only the first buffer and it continues to search through all 2 buffers. To conclude - I have to display each buffer at least once for `lines` to start searching in these buffers. I can make another video of the screen if the above is not very clear.
> > 
> > 
> > Did you try the latest commit?
> 
> Latest commit fixes the issue for me. Though I'm not so sure if I support the idea of constantly reading all open buffers from disk each time I use `lines`.

The fact that the latest commit works for you tells me that something is unloading your buffers, given that you're on a minimal `init.vim` I would assume it's the `hidden` option as I was able to reproduce the exact issue and solve it with `:set hidden`, I was even tried using the same neovim version as you (official 0.5 app image) using [this minimal_init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua) (which is now uploaded to main as well so you can try with the same exact init).

The below are the commit lines that solved the issue for you:
https://github.com/ibhagwan/fzf-lua/blob/7a554bb2b2aeeaa45c418d51bff10fdedcae4b59/lua/fzf-lua/providers/buffers.lua#L219-L223

As you can see it only reads the file if the buffer is not loaded, there's not much I can do against this issue if neovim unloads your buffers (if this is not due to `nohidden` I wonder what else can cause that?), I even tried to skip the check and force the `nvim_buf_get_lines` - the call succeeds but returns an empty table, if the lines aren't found in neovim's memory there really isn't much that I can do about it.

**Comment by ibhagwan** [comment]
I just tried again, the same exact scenario as you, apparently when opening files using the arglist with `nvim *` only the first buffer is loaded, try the below and see for yourself (both scenarios with `set hidden` enabled):

After running `:e file1.txt` followed by `:e file2.txt`:
```lua
:lua print(vim.api.nvim_buf_is_loaded(1))
true
:lua print(vim.tbl_isempty(vim.api.nvim_buf_get_lines(1, 0, -1, false)))
false
:lua print(vim.api.nvim_buf_is_loaded(2))
true
:lua print(vim.tbl_isempty(vim.api.nvim_buf_get_lines(2, 0, -1, false)))
false
```

After running `nvim *` in the folder with the files:
```lua
:lua print(vim.api.nvim_buf_is_loaded(1))
true
:lua print(vim.tbl_isempty(vim.api.nvim_buf_get_lines(1, 0, -1, false)))
false
-- 2nd buffer is not loaded
:lua print(vim.api.nvim_buf_is_loaded(2))
false
-- and returns an empty dataset
:lua print(vim.tbl_isempty(vim.api.nvim_buf_get_lines(2, 0, -1, false)))
true
```

At least we now know that after the next time you'll open the buffer it won't be read from the disk again (assuming you're running `:set hidden`).

**Comment by CuriousSyrup** [comment]
Ok, ok, now I understand.
Neither of these loads the second buffer:
- `nvim *`
- `nvim file1.txt file2.txt`
- `:n file1.txt file2.txt`

Now it's clear.

Thanks for the fix and your support. 
Fantastic plugin.
