### ISSUE TITLE
Built-in preview syntax off not working anymore?

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#169]
I didn't change my config. https://github.com/mcchrish/dotfiles/blob/2546ab460c26aa8dfe120a63c00f0b5d54107f24/vim/Library/Preferences/nvim/plugin/vendor/fzf.lua#L29-L29

**Comment by mcchrish** [comment]
Actually, it only happens with `buffers`.
<img width="1036" alt="Screen Shot 2021-10-06 at 3 07 17 PM" src="https://user-images.githubusercontent.com/7200153/136156047-08c7cec1-e9b9-4b17-9b2f-c354cee242d7.png">
<img width="1036" alt="Screen Shot 2021-10-06 at 3 06 54 PM" src="https://user-images.githubusercontent.com/7200153/136156060-83912608-17b2-40ef-a73b-7f574a48be4b.png">

I assume for buffers, it's reusing the actual buffer?

**Comment by mcchrish** [comment]
I do wonder though if it's possible to turn off the syntax for the window, or is it a buffer-local only config?

**Comment by ibhagwan** [comment]
> Sounds reasonable. Last thing before I close, is the bg highlight suppose to be lighter? I'd like it to be the same as the rests.

It should match, both windows have the `Normal` highlight set using `winopts.hl_normal`, what happens if you set `hl_normal = 'Error'` (under `winopts`)? do both windows now have the same background and red text? if the preview background doesn't change you probably have some other setting overriding it's bg.

>I do wonder though if it's possible to turn off the syntax for the window, or is it a buffer-local only config?

I just tried having the same buffer open in a split and then running `:setlocal ft=""`, it turns the syntax off for both of them.

**Comment by mcchrish** [comment]
<img width="1032" alt="Screen Shot 2021-10-06 at 3 28 06 PM" src="https://user-images.githubusercontent.com/7200153/136158774-006b7920-29d6-4363-a9b9-efea9ddbd39c.png">
I tried using "Search". What happens is the the preview window flashing purple then replaced with the buffer. It seems to be using the `FloatBorder` hl.

**Comment by ibhagwan** [comment]
It's probably something with your config/colorscheme, I just tried with both my own config and the minimal `init.lua` I linked earlier in the thread with the below settings:
```lua
      require'fzf-lua'.setup({
        winopts = {
	    hl_normal = 'Search',
	    hl_border = 'IncSearch',
        }
      })
```

With my own config:
![screenshot-1633505959](https://user-images.githubusercontent.com/59988195/136161100-2998fb17-8591-44e0-93a7-45bca6773a54.png)

With the minimal `init.lua`:
![screenshot-1633506120](https://user-images.githubusercontent.com/59988195/136161118-d087e469-88da-4810-a354-298f6ac0c101.png)

**Comment by mcchrish** [comment]
I can confirm that the background is being applied correctly except for `buffers`. `files`, `grep` etc are working fine.
In those screenshots, it looks like you are using `files`?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/56885088e98e8d6aa1888c5f226a90d7513bf931 should solve it.

This bug was introduced due to the preview delay option, to increase scrolling performance a delay of 100ms was added before previewing the buffer so the highlights were being applied before the buffer was actually set in the preview window.

**Comment by mcchrish** [comment]
Confirmed to be fixed! Thanks.

**Comment by ibhagwan** [comment]
> Confirmed to be fixed! Thanks.

Ty for letting me know :-)
