### ISSUE TITLE
live_grep cause Out of memory errot

### ISSUE THREAD

**Issue by sun617** [ibhagwan/fzf-lua#185]
if execute live_grep on a folder that includes big svg file, it cause out of memory error then exit neovim
[sample file](https://upload.wikimedia.org/wikipedia/commons/7/77/North_Rhine-Westphalia_Topography_01.svg)

![image](https://user-images.githubusercontent.com/1286238/137417281-a80ec62e-ca72-4e80-848e-e5072feb26c9.png)

**Comment by ibhagwan** [comment]
> `live_grep` worked!
> and also tried `grep`, but this failed as same error

In order to fix that I’ll have to replace `nvim-fzf`’s `cmd_line_transformer`, I’m not exactly sure yet what’s causing the memory to run out but it seems that the lua function parsing newlines (from the rg output) is the cause.

While I can replicate the the fix I used for `live_grep` that would mean I can’t parse newlines and won’t be able to add icons.

Perhaps @vijaymarupudi will have some input here as this bug is coming (most likely) from the below:
https://github.com/vijaymarupudi/nvim-fzf/blob/e270279a3112ae502e788d34499b776f9fe66f9d/lua/fzf/helpers.lua#L16-L18

I suspect the parsing will have to be replaced with something more robust than lua `gsub`.

**Comment by ibhagwan** [comment]
I found the crux of the issue, line 13763 of [the sample file](https://upload.wikimedia.org/wikipedia/commons/7/77/North_Rhine-Westphalia_Topography_01.svg) is a whopping `15515784` characters, that line alone causes a noticeable delay in a couple of operations:
- `find_last_newline`
-  `str:gsub("[^\n]+", ...`

I'm still working on a more robust line parser but for now you can easily solve this by adding `--max-columns=512` to your `rg_opts`, I cannot think of any reason anyone would want `rg` to output extremely long lines:

```lua
require'fzf-lua'.setup {
  grep = {
    rg_opts = "--column --line-number --no-heading --color=always --smart-case --max-columns=512",
  }
}
```

**Comment by ibhagwan** [comment]
I did a major refactor of the async commands, it should work better now, I also added `--max-columns=512` by default to `rg_opts` so unless you changed the defaults the latest update should give you smooth performance all around in `grep` and `live_grep`.

Let me know if this works well for you?
