### ISSUE TITLE
Global setting to disable icons

### ISSUE THREAD

**Issue by astier** [ibhagwan/fzf-lua#188]
Hello. Is there a global setting to disable icons like file_icons and git_icons? Right now the user has to set it manually for every single command which is quite a lot and not very elegant. Also it seems the setting `preview_opts` is not documented in the readme. I stumbled by accident on it in some other issue. I set it to `hidden`. Is the preview-window still generated in the background but just not visible?

**Comment by ibhagwan** [comment]
No global option for the icons, someone asked to add it in the past but I opted against it as not all providers support icons and I thought it was confusing, it's basically only files/git/grep.

The reason `preview_opts` has no documentation is because it was removed and is now supported only through backward comparability code, the correct option to use would be under `winopts.preview.hidden`, when set to `hidden` preview window isn't generated at all, it will only be visible if you press the `toggle-preview` keybind (default `<F4>`).

**Comment by astier** [comment]
>What may seem not necessary for you may seem necessary for someone else, for example, what if someone wants to disable git icons for files and enable them only for git_files?

I understand that it would be useful if somebody for some reason would want to have context-dependent icons but anybody could want anything and than every plugin would have to be turing-complete. I am just wondering why somebody would want that. All other plugins and programs I ever encountered usually only have one option. Icons on or icons off. And I never saw anybody complain. But more than one people complained about not having a global setting. Just wanted to explain my reasoning. But I respect your decision. Thanks for the great plugin.

**Comment by ibhagwan** [comment]
I understand your reasoning too and it might as well be the case but since it's already been available I can't take this functionality away, especially since it's not really an issue but rather just a minor inconvenience on the first setup (in case you do not want icons).

If you can think of a way to add global option that would not be confusing or inconsistent with overriding "finer tuned options" feel free to open this again and we can discuss it.

**Comment by kristijanhusak** [comment]
> If you can think of a way to add global option that would not be confusing or inconsistent with overriding "finer tuned options" feel free to open this again and we can discuss it.

i think we could go with something like `disable_all_file_icons` that defaults to `false`, with a note that setting it to true disables fine grained control.
I just wanted to disable icons on all sources, but there are 17 places (In https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/config.lua) where I would need to explicitly set this to false. Having this option would help a lot.

**Comment by kristijanhusak** [comment]
Awesome, thanks!
