### ISSUE TITLE
Sort buffer by MRU order like fzf.vim

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#208]
Similar to https://github.com/junegunn/fzf.vim/issues/100

**Comment by ibhagwan** [comment]
I looked at [the commit in the linked ussue](https://github.com/junegunn/fzf.vim/commit/852cfa0c11d5661d79ed1faf1cc211b3c6ef7b00) and I don't really like the solution, it uses an autocmd that maintains a map and updates the timestamp each time a buffer is entered, never been a big fan of depending functionality on autocmd as they're prone to errors/failures/conflicts with other plugins in my experience.

I'll look if there's another way to figure this out in a simpler way inside neovim but if it comes down to an autocmd I'm not overly excited to do this and doing this internally is also not worth it as uses have many different ways of switching buffers outside of the plugin ecosystem.

**Comment by mcchrish** [comment]
How about this from telescope? https://github.com/nvim-telescope/telescope.nvim/pull/1028

**Comment by ibhagwan** [comment]
> How about this from telescope? [nvim-telescope/telescope.nvim#1028](https://github.com/nvim-telescope/telescope.nvim/pull/1028)

This one is great, I was going to look later if `getbufinfo()` has a timestamp, turns out it has!

I’ll implement this one in the next commit.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/07010f74c6b22343f88ab1c62c686762fce464f0 added, I modified the current `sort_lastused` parameter (default:true) for the new behavior (proper sort), prior to this commit it would only  put the current buffer (`%`) and last used buffer (`#`) at the top, now it does proper sort based on access time.

Turned out to be a bit more complex than the Telescope commit as the buffer previewer was attaching the actual buffer to the preview window and that was modifying the `lastused` timestamp which was messing up the order. The buffer lines are now read instead into the preview buffer (same as Telescope).

As a "bonus" I had an entire workaround made for scrolling a terminal buffers which is not required anymore, but the terminal syntax highlight now does not match the actual terminal, not a big deal to pay as I prefer proper buffer sorting over this minor inconvenience, I noticed Telescope does the same (I guess for the same reasons) and doesn't have syntax highlighting at all for terminal buffers.
