### ISSUE TITLE
weird behavior in fish shell

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#210]
minimal config 
``` lua
local actions = require("fzf-lua").actions
require("fzf-lua").setup({
    winopts = {
        split = 'belowright new',
        fullscreen = false,
        preview = {
            default = 'bat_native',
            horizontal = 'right:50%',
            vertical = 'down:50%',
            layout = 'horizontal'
        },
        on_create = function()
            vim.opt_local.buflisted = false
        end
    },
    keymap = {
        fzf = {
            ['ctrl-a'] = 'select-all',
            ['ctrl-d'] = 'deselect-all'
        }
    },
    fzf_opts = { ['--layout'] = 'default' },
    files = {
        cmd = 'rg --files --follow --smart-case --hidden --no-ignore -g "!{.DS_Store,.cache,venv,.git,.clangd,.ccls-cache}" 2> /dev/null',
        actions = {
            ['default'] = actions.file_edit,
            ['ctrl-x'] = actions.file_split,
            ['ctrl-v'] = actions.file_vsplit,
            ['ctrl-q'] = require('utils').qf_populate
        }
    },
    buffers = {
        actions = {
            ['default'] = actions.buf_edit,
            ['ctrl-x'] = actions.buf_split,
            ['ctrl-v'] = actions.buf_vsplit
        }
    }
})
```

- `files` and `buffers` commands work perfectly (most of the time), there is some launch lag but Im satisfied with it for now. Sometimes after a fresh launch, I trigger the files keymap, and fish shell freezes. This freeze can be seen even in new terminal windows, and doesnt go away till you exit/wait. 
- `live_grep`, `live_grep_native`, `grep` all show weird lag most of the time, which I presume is caused by the same fish-freeze issue. Results dont show up and the screen freezes. When you do something like `ctrl-c` or `:q` on that grep split/window, command exits, but leaves a terminal buffer open. And any calls you make after that to fzf-lua, dont follow window configs, and even crash vim sometimes

**Investigation:**
- the lag is better in zsh, but still there

**Related feature-requests:**
- the split/windows should be `nobuflisted` and `bufhidden="wipe"`. We can achieve this currently using the `on_create` config. This would solve the bug where you can jump back into the closed terminal buffer using `o` (ie fzf-lua windows end up in the jump list right now)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/62937db2dbfb34639d8da61c595c7d33bf7c8769

The above commit orces `fzf` to run within the confines of `sh -c`, it's very possible this can solve the issue - can you try and let me know?

Before pushing this change I did install `fish` and tried on my machine with `vim.opt.shell = "/sbin/fish"` with your exact setup, weirdly enough everything works fine.

Hopefully the above commit solves your issue but just in case, I have a few questions that may help get to the bottom of this:

- What is your `nvim --version`?
- What is your `fish --version`?
- Are you on Linux/Mac?

Is it possible this issue is related to something in your config? would you be willing to try with this [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua)?

Even better if you can try with the [official 0.5.1 release appimage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage).

**Comment by ibhagwan** [comment]
FYI to anyone reading, this turned out to be a different issue, myself and @ViRu-ThE-ViRuS tried to run a simple shell script that does almost exactly what `live_grep` (in the shell, not in neovim) and the fzf reload command was failing and printing `"pyenv: cannot rehash: {HOME DIR}/.pyenv/shims/.pyenv-shim exists"` after a huge delay.

After uninstalling `pyenv` fzf `change:reload` started working properly and `fzf-lua` started working as well.

I'll leave it for @ViRu-ThE-ViRuS  to add any commentary after he investigates what was happening on his machine :-)

**Comment by ViRu-ThE-ViRuS** [comment]
Like commented above,
it turned out that FZF was stuck processing shim folders inside `$HOME/.pyenv` which caused it to stall and often exit with weird exit codes. Solution includes fixing `pyenv` installs, adding the dir to FZF ignore rules, or just uninstalling pyenv. 

Huge thanks to @ibhagwan, this man is a beast!
