### ISSUE TITLE
Manually loaded fzf-lua

### ISSUE THREAD

**Issue by Pirols** [ibhagwan/fzf-lua#212]
I have just updated to the latest commit (9065fdf) and every time I launch neovim (v0.5.1) I get the following message:

`[Fzf-lua] manually loaded 'path/to/fzf-lua.vim'`

I didn't find a way to prevent such message (other than removing [this line](https://github.com/ibhagwan/fzf-lua/blob/9065fdf1bb7ee01391a0988d49f108d025999bdf/lua/fzf-lua/init.lua#L23) from my fzf-lua files) from appearing. Was this just a forgot print statement or is it going to stick?

Thanks

**Comment by leiserfg** [comment]
Yes, this is very annoying, seems like it's a workaround for a nvim issue, we as users should not be punished by that.

**Comment by leiserfg** [comment]
By the way, I'm using nightly and I see  `fzf-lua.vim` being called without the workaround (I disabled the workaround by hand and echoed in the `.vim` file).

**Comment by ldelossa** [comment]
+1 I'm seeing this as well with latest pull.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cb526dbb0c3af7f5e32011e7b7698b3168ce44a6 removed.

I'm still confused as to why this is happening, I thought this would be much more rare so very few people would see this, seems not the case.

@leiserfg:

>By the way, I'm using nightly and I see fzf-lua.vim being called without the workaround (I disabled the workaround by hand and echoed in the .vim file).

It wasn't happening consistently for me too and now I'm even more confused as it was happening to @Pirols on 0.5.1.

On the plus side, the workaround seems to be working as nothing broke (aside from being annoying lol).

**Comment by Pirols** [comment]
Thanks for the fix.

Sounds very weird, unfortunately I don't have enough insight on the issue to help you. Regardless, this is how I enabled `fzf-lua`, using `packer.nvim`:

``` lua
-- Fzf-lua: Lua port of fzf.vim
use {
    'ibhagwan/fzf-lua',
    requires = {
        'vijaymarupudi/nvim-fzf',
        'kyazdani42/nvim-web-devicons',
    },
    config = function()
        require('plugins/fzf')  -- this file contains the initialization as described in the customization section of your README.md.
    end,
}
```
Since I don't define it as an optional package it is stored inside `~/.local/share/nvim/site/pack/packer/start`

Hope this helps. Keep it up!

**Comment by ldelossa** [comment]
@ibhagwan I  re-source my fzf.lua config file after my themeing bits load (to set the correct fzf colors and what not) maybe this is why it show?

**Comment by ibhagwan** [comment]
Ty @Pirols, @ldelossa 

I do something similar with Packer (although I lazy-load), I was experiencing a random error where the plugin would load but the  plugin’s `.vim` file wasn’t getting called, I assumed it was the nightly as it wasn’t happening prior to that, @Pirols also eliminates this happening due to lazy load.

When this was happening I noticed `g:nvim_fzf_directory` was nil preventing fzf-lua preview actions from working and also `:FzfLua` command was missing (since it’s loaded in the `.vim` file), the former was actually causing an error opening fzf-lua providers with previews so I had to fix it (and that was happening only on the nightly for me).

I’m thinking maybe the script loading order is random and `fzf-lua.vim` is sometime called after `fzf-lua/init.lua` which why this was appearing for more users than I expected.
