### ISSUE TITLE
git_files does not show all files in a git repository

### ISSUE THREAD

**Issue by mctwynne** [ibhagwan/fzf-lua#22]
Since the default command for git_files is `git ls-files`, it will only search the current directory (recursively). Because of my experience with other similar plugins I was expecting to be able to search for *any* file in the git repo, rather than only ones in the my cwd, and below. I attempted to set the `cwd` option to the root of my project, and changed the `cmd` to use `git ls-tree`, but neither achieved the intended result.

Using `git ls-tree HEAD -r --full-tree --name-only` gives me all the files I'd like, but the preview shows the following error, and the selected file will not open: `head: cannot open 'FILENAME' for reading: No such file or directory`

Any suggestions? Love the plugin! Great work!

**Comment by ibhagwan** [comment]
Unfortunately I still use the previewer as you would in the shell (I.e. sending fzf a command with the `—preview` option), in order to make it work I prefix the command file spec with the current working directory, unfortunately that means it cannot preview any files outside the cwd.

The semi-workaround is to send `cwd=nil` but that would make the plug-in show full paths inside your repo which is undesirable.

In the near future I plan to rework the previewer to stream contents (instead of sending fzf a command to run), that will solve this issue as well as allow me to send treesitter supported preview content if the user prefers that over bat.

Hopefully that explains it.

**Comment by mctwynne** [comment]
@ibhagwan Makes sense. Thanks for the response!

**Comment by ibhagwan** [comment]
The title is a bit misleading now since this issue is mostly about the preview not working correctly, since we now have issue #24 I will update the preview progress there.

**Comment by ibhagwan** [comment]
Previewing files with absolute path should be fixed in the latest commit.
