### ISSUE TITLE
Git status cannot preview Chinese filename

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#221]
As title. With image:

<img src="https://user-images.githubusercontent.com/24765272/142752221-b337c540-dc23-4d59-98df-1f3cdb13f942.png" width="500">

**Comment by ibhagwan** [comment]
The problem here is that your git doesn't display proper UTF-8, as apparent with the `translation/\344\270\255\346\226\207.md`.

Fzf-lua runs `git status -s` and parses the output which is then also sent to `git diff` for the preview which doesn't like the quoted octal notation.

I found the solution in: [How to make Git properly display UTF-8 encoded pathnames in the console window?](https://stackoverflow.com/questions/22827239/how-to-make-git-properly-display-utf-8-encoded-pathnames-in-the-console-window)

Added the below to my `~/.config/git/config`:
```
[core]
  ; git prints non-ASCII file names in quoted octal notation,
  ; i.e. "\nnn\nnn...", disable to display UTF-8 chars
  quotepath    = off
```
Which is equivalent to running (in the shell):
```sh
# drop the '--global' flag if you want to set this for a sigle repo
git config --global core.quotepath off
```

**Comment by nyngwang** [comment]
It works! Thank you
