### ISSUE TITLE
icons look quite small

### ISSUE THREAD

**Issue by darzok0914** [ibhagwan/fzf-lua#229]
hi, 

I just had a question regarding the size of icons associated with files, for example, telescope icons are quite big and close to the text:

![image](https://user-images.githubusercontent.com/72544332/144451703-bb567c2f-4801-41ff-95fc-35e6ddb673dd.png)

but with fzf.lua icons looks smaller and farther away from the text:

![image](https://user-images.githubusercontent.com/72544332/144452344-b7a0f732-e48b-436d-9de6-75a3203c9843.png)

I know it is just a cosmetic issue but out of curiosity do you know what would cause this? I already had a look at the padding setting but it didn't change anything.

**Comment by ibhagwan** [comment]
I'm not sure about the size issue, this might be related to the fact Telescope runs inside a normal vim buffer and neovim renders the icons, in `fzf-lua` the rendering of the icon is done by `fzf` in a terminal buffer.

As for the spacing that's because you have `git_icons` enabled which leaves space for the git icon indicators, for exmaple see the below `M` for `modified`:

![screenshot-1638459518](https://user-images.githubusercontent.com/59988195/144453696-ec71e5ef-0224-48e5-9a83-e37d90060fbe.png)

If you wish to have the spacing reomoved and don't care about the git indicators run `lua require'fzf-lua'.git_files({ git_icons = false })` (or `:FzfLua git_files git_icons=false`) which will result in:

![screenshot-1638459670](https://user-images.githubusercontent.com/59988195/144454136-3c6b8465-bda4-4f11-88a0-48b2b495e45d.png)

**Comment by ibhagwan** [comment]
Quick note regatding the icon size, I think this has something to do with your terminal, I use alacritty and my icon size are the same in both Telescope and fzf-lua (Telescope on the right):

![screenshot-1638469150](https://user-images.githubusercontent.com/59988195/144480356-bed8f62e-52a6-4774-a65c-7c6f4aaf38c5.png)


Which terminal are you using?

**Comment by darzok0914** [comment]
ok thanks for the tips, I'm using kitty, I'll try to investigate a bit on my side this issue. It's a minor issue that you can't do a lot about it. I'm closing this issue
