### ISSUE TITLE
[dashboard compatibility] lsp_document_diagnostics window closes automaticaly after opening.

### ISSUE THREAD

**Issue by Elorolf** [ibhagwan/fzf-lua#23]
When I try to open lsp_document_diagnostics or lsp_workspace_diagnostics, the window closes automatically. 

Using the following setup: 

``` 
Plug 'glepnir/dashboard-nvim'
Plug 'ibhagwan/fzf-lua'
Plug 'ibhagwan/nvim-fzf'
```
This occurs only when dashboard is enabled.

**Comment by ibhagwan** [comment]
Hmmm, this is the 3rd dashboard compatibility issue in 3 days lol

I’m def going to look into this but this has me confused a bit, for the LSP you have to be in a buffer, that means you already left the dashboard intro screen right? What is dashboard’s role past the initial screen?

**Comment by ibhagwan** [comment]
I'll be honest I really have no idea where this is coming from, from what I can tell it happens only if dashboard was active before any file was opened, if you open a code file directly the issue won't occur, more so if you do `workspace_diagnostics` it works which is the exact same code with one different call to the LSP server...

I did some testing with the dashboard code and I'm not sure why some of the autocmd's keep getting called even after dashboard was exited, although not related the `dashboard#close_preview()` keeps getting called even after leaving dashboard, unless I'm misunderstanding, this would be undesirable behavior.

It's a bit hard for me to debug this issue since most of dashboard's code is vimscript and I'm really not enjoying this, if this was lua I'd be much more happy to bisect the code and pinpoint the exact cause.

I already did a couple of workaround just for dashboard due to unexplained behavior and just committed another potential fix which seemed to fix it for me when I was running `skim` as an fzf binary but not when `fzf` was the actual binary, go figure, might fix it for you, try it out and let me know?

For now I recommend opening files directly if you know where you're going and avoiding the dashboard screen altogether. I'm not judging what plugins people choose to use but I really don't like this intrusiveness of the plugin so far, so many weird issues for something that provides an opening screen and keeps running code after leaving the opening screen?

**Comment by Elorolf** [comment]
Thank you for your investigation, it was just to report this other incompatibility issue to let you know and I notice that it's not a fzf-lua's issue. For now I will stop using dashboard until this intrusiveness issue is solved as I was using it just to have a nice start screen.

**Comment by sQVe** [comment]
I think we might be a bit quick putting blame on `dashboard` as it used by many and working nicely together with other other fuzzy finders like `fzf.vim`, `telescope` and `clap`.

I cannot help much with this issue as I'm currently on holiday.

**Comment by ibhagwan** [comment]
> I think we might be a bit quick putting blame on `dashboard` as it used by many and working nicely together with other fuzzy finders like `fzf.vim`, `telescope` and `clap`.
> 
> I cannot help much with this issue as I'm currently on holiday.

By all means, leave this open until we get to the bottom do this as we did with the other issues.

One thing is for sure, dashboard is still running some code after leaving dashboard, I’d you wanna test it yourself, go ahead and and add `echo whatever` after [dashboard.vim#L238](https://github.com/glepnir/dashboard-nvim/blob/master/autoload/dashboard.vim) and watch it being printed many times when you open/close buffers. IMO once you left dashboard, it should unload everything and not have any leftover auto commands or code running.

I don’t know what in fzf causes this incompatibility with dashboard and perhaps there is yet another change I can do on my end to workaround it, but even if I do find such workaround, this issue is most likely coming from dashboard.

**Comment by ibhagwan** [comment]
> I think we might be a bit quick putting blame on `dashboard` as it used by many and working nicely together with other fuzzy finders like `fzf.vim`, `telescope` and `clap`.
> 
> I cannot help much with this issue as I'm currently on holiday.

Seems like there are quite a few non-compatibility issues with telescope  see issue #65](https://github.com/glepnir/dashboard-nvim/issues/65), as well as [issue #88](https://github.com/glepnir/dashboard-nvim/issues/88).

**Comment by ibhagwan** [comment]
I just pushed a commit that might fix this issue, I have no idea why but adding a slight delay to the end loop with `vim.defer_fn` seems to make it better with dashboard, this doesn't make a lot of sense and is a bit of an ugly hack but if this solves it I guess there's no real harm in a 20ms delay on the last result.

Let me know if this solves it for you?

**Comment by gegoune** [comment]
Boo at dashboard for requiring things like this. Way more people won't use it and be now facing artificial slows downs. Perhaps instead of working around those oddities in dashboard make sure it is not due to fzf-lua, add incompatibility notice to README and link to relevant issues on dashboard side?

**Comment by ibhagwan** [comment]
> Boo at dashboard for requiring things like this. Way more people won't use it and be now facing artificial slows downs. Perhaps instead of working around those oddities in dashboard make sure it is not due to fzf-lua, add incompatibility notice to README and link to relevant issues on dashboard side?

It's not a big deal, a single 20ms delay before letting fzf know the last result was delivered (and stopping the loadi indicator) will never be noticeable so it really is a non issue.

As for dashboard, I looked at the code and this is really beyond me what's it's doing this or why it needs to continue running code after you left the dashboard, I have no interest in trying to solve that or open issues on it, if someone uses it and it bothers them they can do that.

**Comment by gegoune** [comment]
I am not using it, also it seems bit unmaintained at the moment. So does saga (which I don't use either). Seems like @glepnir has been very inactive on GH in last months.

**Comment by ibhagwan** [comment]
I am closing this for now, feel free to reopen of this issue needs more help.
