### ISSUE TITLE
`git_files` will go into insert mode, if not inside a git project.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#235]
As title. I think this behaviour is kind of dangerous if type too quickly. And that this problem seems to occur on other `FzfLua` commands.

**Comment by ibhagwan** [comment]
That's certainly not by design, just tried with few different neovim versions (0.5.1, 0.6 and 0.7) and it doesn't happen for me when I run the command directly, it only happens when I first run `:FzfLua builtin` and then choose a command that doesn't have any result (e.g. `git_files` or `lsp_xxx`).

Can you confirm if the same happens for you or does this also happen if you run `:Fzf git_files` directly from the command line?

**Comment by ibhagwan** [comment]
Latest commit should solve this, let me know if otherwise?

**Comment by nyngwang** [comment]
It works now! But now I have another question that: Is it possible to also eliminate the "blink" (A floating window appear-then-disappear in a short moment, but it is noticeable)

**Comment by ibhagwan** [comment]
This is by design, the blink appears because all LSP functions are running asynchrounsouly, they open the UI and then wait for the reply from the server.

If you wish to avoid that chance it to "synchronous instead" (works for all LSP functions):

```lua
:lua require("fzf-lua").lsp_references({ async = false })
```

You can also enable this by default for all LSP functions by adding this to the setup:
```lua
require'fzf-lua'.setup {
  lsp = {
    -- timeout in miliseconds, below is 5 second timeout
    async_or_timeout  = 5000,
  }
}
```
> Note that with "synchrounous" operations the UI can hang until a reply is received from the server (or until 5 seconds passed), it could be an issue if you have a really slow LSP server or if you just started neovim and the LSP isn't ready yet.

**Comment by ibhagwan** [comment]
FYI, the latest commit https://github.com/ibhagwan/fzf-lua/commit/419a57a78f816038be08628b9f648d6a20bb2d4b sets most of the LSP calls to `async = false` so you don't have to do anything anymore, just updated the plugin and the flash will disappear.
