### ISSUE TITLE
[Feature Request] Do `git add` to the selected files in `git_status`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#239]
As title. It will be very helpful for me if I can add some file-update to git without typing `git add`. Currently, I can only use `require'fzf-lua'.git_status()` to open these files, but I will like to `git add` them at ease.

**Comment by ibhagwan** [comment]
The issue here is that it will require much more work than just `git_add` because then I have to refresh the list and add an indicator marking it as "Staged" and then also adding an option for `git_unstage`, that also requires to run a different command than `git status -s` to display staged/unstaged files and may other git intriciacies, then why stop here? why not enable `git_status` between two different commits? it's endless.

Whenever I get to the point I need that type of functionality, I use [vim-fugitive](https://github.com/tpope/vim-fugitive) which can do practically anything with git repos, if I need more fine grained control on the chnges (or wish to compare two different commits) I use [diffview.nvim](https://github.com/sindrets/diffview.nvim), both are geared specifically towards git and are much more suitable tools for the job.

Doing this inside `fzf-lua` requires more work and complexity than I wish to enter ATM, perhaps one day I'll revisit this but for now I consider this out of scope of fzf-lua.

**Comment by nyngwang** [comment]
What if we just close the window (so no need to refresh) and if the user wants to unstage then it should do it by CLI? I'm still somehow hope this can be done.

**Comment by ibhagwan** [comment]
That you can do by yourself, just add a custom action mapping and call `git add` using `vim.fn.system`.

Something like this (make sure to add proper flags, working dir if needed, etc):
```lua
actions = {
  ["ctrl-y"]      = function(selected)
     vim.fn.system('git add  .. 'selected[1])
  end
}
```

**Comment by nyngwang** [comment]
> That you can do by yourself, just add a custom action mapping and call `git add` using `vim.fn.system`.
> 
> Something like this (make sure to add proper flags, working dir if needed, etc):
> 
> ```lua
> actions = {
>   ["ctrl-y"]      = function(selected)
>      vim.fn.system('git add ' .. selected[1])
>   end
> }
> ```

Thank you, let me try it now. I think this is exactly what I need!

**Comment by nyngwang** [comment]
> That you can do by yourself, just add a custom action mapping and call `git add` using `vim.fn.system`.
> 
> Something like this (make sure to add proper flags, working dir if needed, etc):
> 
> ```lua
> actions = {
>   ["ctrl-y"]      = function(selected)
>      vim.fn.system('git add ' .. selected[1])
>   end
> }
> ```

This resolves the issue. Thank you!

**Comment by ibhagwan** [comment]
I'm pretty sure you know this but if you neded to iterate all selected files, this is how it's done in lua:

```lua
for _, file in ipairs(selected) do
  -- do whatever you want with the file
  print(file)
end
```

**Comment by nyngwang** [comment]
This doesn't work anymore. And `selected[1]` seems not able to work when I select multiple files now.

**Comment by nyngwang** [comment]
> I'm pretty sure you know this but if you neded to iterate all selected files, this is (one of the ways) how it's done in lua:

I thought I know what you were talking about. Now I realize I need to fix something, lol.

**Comment by ibhagwan** [comment]
This was just a sketch function, inspect the `selected` table properly, you may need to parse the line and remove parts of it  (the `M` at the start for example`).

I use the below to print objects in neovim `:messages`:
```lua
-- help to inspect results, e.g.:
-- ':lua _G.dump(vim.fn.getwininfo())'
-- use ':messages' to see the dump
function _G.dump(...)
  local objects = vim.tbl_map(vim.inspect, { ... })
  print(unpack(objects))
end
```

**Comment by nyngwang** [comment]
> I'm pretty sure you know this but if you neded to iterate all selected files, this is (one of the ways) how it's done in lua:
> 
> ```lua
> for _, file in ipairs(selected) do
>   -- do whatever you want with the file
>   print(file)
> end
> ```

Indeed your sketch is correct. I just forgot that I need to add this loop for my `actions = { ["ctrl-y"] ...`. (So I encountered an error that I only `git add` one file while I selected multiple.)

**Comment by ibhagwan** [comment]
FYI, since the `resume` made this much easier I decided to add stage/unstage operations, I reworked `git_status` entirely, it now matches the output of `git status -s` where the left markers are staged and right are unstaged.

By default `<left>` will stage a file (move the icon from right to left) and vice versa with `<right>`:

![screenshot-1639906547](https://user-images.githubusercontent.com/59988195/146670274-1dec9b12-7acf-4ef9-8ef3-3bf70a234a13.png)

**Comment by nyngwang** [comment]
@ibhagwan Astonishing! I'm happy to upgrade my editor and try this now!

**Comment by nyngwang** [comment]
This not only makes me feel productive but also provides a fun experience.

<img src="https://user-images.githubusercontent.com/24765272/146679957-90930b9b-c85a-4874-b7a3-29786cabef24.png" width="500">
