### ISSUE TITLE
Feature Request: Git `multiprocess = true` to make all `status`, `commits`, ... etc. `multiprocess = true`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#249]
As title. While adding one for each is more clear. I think this option will be very convenient.

**Comment by ibhagwan** [comment]
I could easily make that a global switch, the issue here is that `multiprocess` is not needed IMO for anything other than `files` and `grep` , other commands are IMO "fast enough".

The issue`multiprocess` is aiming to solve is performance of very large result sets (>100k at least), aside from `git_files` no other command should have result sets that are this large.

I can still make it a global switch to controll all 3 places where it's possible `files`, `grep` and `git.files` - will that help?

**Comment by nyngwang** [comment]
With your kindly reply regarding the context, I think this is a bad request. Let me close it :p
