### ISSUE TITLE
Tags provider displays incorrect line numbers in tags list

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#255]
When using `:FzfLua tags`, the line numbers listed for each tag is always listed as 1. However, the correct line is highlighted in the preview window and pressing **Enter** on the tag will jump to the correct line as well.

## Reproduction

1. First, here's the `init.vim` I was using:
    ```vim
    let g:vimDir = stdpath('config')
    
    call plug#begin(g:vimDir . '/bundle')
    Plug 'ibhagwan/fzf-lua'
    call plug#end()
    
    lua << EOF
    require('fzf-lua').setup{}
    EOF
    ```
2. Create the test file `test.c`:
    ```c
    #include <stdio.h>
    
    int main(void)
    {
        printf("Hello world!\n");
    }
    ```
3. Create tags file: `ctags test.c`
4. Open the test file: `nvim test.c`
5. Run `:FzfLua tags`

    Here's my result: 
![image](https://user-images.githubusercontent.com/37260523/145906176-a3af1d75-94bf-4c8c-b9f5-768c131911e6.png)
    Note how the two circled lines do not match.

## Observations

I remember this used to work correctly. I suspect the change to `tags.lua` in [46c9e2b](https://github.com/ibhagwan/fzf-lua/commit/46c9e2bcd22b40203d3881d37be4d238b8c01530#diff-84f2d1d0d760c9efbd2830174eb8399726bebdbc67060f196cf3704ac866cf36) has something to do with this.

**Comment by ibhagwan** [comment]
You’re correct, that’s “by design” since the performance improvement implementation for #245, I just left it as `1` because there are few functions dependent on having a line number and I didn’t want to experiment at the time how it will behave without it as I was busy with the multi process performance enhancements.

I’ll remove it once I’m done with the other issues, in the meantime if you want to hide it you can do so by supplying the function with `{ fzf_cli_args = 'with-nth=…' }`, the delimiter is `:` so you’d wanna hide field 2. (`man fzf` if you have no idea what I’m talking about, also see #253)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/31a678e4dedb418fd011f31333ff7111e16aaae6 this commit closes this issue.

Note that unless you change the previewer to `bat` it will no longer show line numbers at all, the reason is the `tags` files does not contain numbers (by default) and since #245 the pattern is being used to locate the correct preview (and buffer jumps) instead of line number.

**Comment by shyun3** [comment]
Thanks for the update! However, I noticed that line numbers aren't shown even for the `bat` previewer. This isn't an issue, it's just that your last comment made it seem like line numbers are only hidden for the built-in previewer.

**Comment by ibhagwan** [comment]
> Thanks for the update! However, I noticed that line numbers aren't shown even for the `bat` previewer. This isn't an issue, it's just that your last comment made it seem like line numbers are only hidden for the built-in previewer.

That's because `tags` and `btags` are no longer affected by the default previewer setting, both now use their own specialized tag previewer (that knows how to search for the pattern).

To test the bat previewer with `tags` or `btags` do:
```lua
require'fzf-lua.setup {
  tags = { previewer = "bat" },
  btags = { previewer = "bat" },
}
```
```lua
-- or just call the function direcltly with these options:
:lua require'fzf-lua'.tags({ previewer = "bat" })
```
