### ISSUE TITLE
Adding `--ignore-case` to `files.fd_opts` doesn't work.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#256]
As title. With settings:

```
files = {
  prompt = ' File $ ',
  -- WARNING: Run `brew install fd` to install fd.
  fd_opts =
    "--hidden "..
    "--ignore-case "..
    "--no-ignore "..
    " "..
    "--type f "..
    -- "--max-depth 15 "..
    "--exclude .DS_Store "..
    "--exclude .git "..
    "--exclude node_modules "..
    "--exclude '*-lock.json' "..
    "--exclude '*.lock' "..
    " ",
  actions = {
    -- WARNING: This is required. Or files will be opened in quick-fix list.
    ["default"] = actions.file_edit,
  }
},
```

As img:

<img src="https://user-images.githubusercontent.com/24765272/145959294-64e3cbe5-67e7-4cb5-8e5e-2cde8a1f290b.png" width="500">

<img src="https://user-images.githubusercontent.com/24765272/145960263-85eb3979-9356-4fb0-9bc1-97827e2ff366.png" width="500">

**Comment by ibhagwan** [comment]
That's because `files` isn't "live", the `--ignore-case` is meaningless here,  the `fd`command isn't run again every keystroke, it's `fzf` doing the fuzzy matching for you not `fd`.

If you wanted to ignore case in the search you need to add `-i` to `fzf_cli_args`, from `man fzf`:
```help
       -i     Case-insensitive match (default: smart-case match)
       +i     Case-sensitive match
```

Add this via `fzf_opts` (as a table) or via `fzf_cli_args` (same thing, different way):
```lua
  files = {
    fzf_opts          = { ["-i"] = "" },
    -- fzf_cli_args      = "-i",
  ...
}
```

You can also add this directly to the call:
```lua
:lua require'fzf-lua'.files({ fzf_cli_args="-i" })
```

![screenshot-1639479379](https://user-images.githubusercontent.com/59988195/145985347-aab0de9c-5a13-4713-869d-475e35b5ae5c.png)

**Comment by nyngwang** [comment]
Should I remove some lines from my settings? It doesn't work like the image you have shown.

**Comment by ibhagwan** [comment]
> Should I remove some settings of `fd` lines from my settings? While I use `fzf_cli_args`, It doesn't work like the image you have shown.

By not work do you mean it does not ignore case or fails to work properly at all?

Your settings make no differnce in this case, as long as `fzf` receives the `-i` flag it should be case insensitive, what version of `fzf` are you using? You can try with an empty `setup()` function and see if it makes a difference (it shouldn't but you can try)?


Note that if you opted to use `skim` instead of `fzf` it does not have the `-i` flag, it has `-case` flag instead:
```help
       --case=[smart,respect,ignore]
              To ignore case on matching or not. (default smart)
```

**Comment by nyngwang** [comment]
OK, it works. (I fall asleep so didn't reply immediately) I have tried three versions:

1. Put `fzf_cli_args="-i"` inside `files`:
```
files = { fzf_cli_args="-i" }
```

2. Put `fzf_cli_args="-1"` the same level as `files`:
```
fzf_cli_args="-i"
files = { ... }
```

3. And the cmd version you mentioned:
```
:lua require'fzf-lua'.files({ fzf_cli_args="-i" })
```

I expected 2. to fail, but it works. Or it is because of some kind of cache that causes this. Can you help me confirm this result?

**Comment by nyngwang** [comment]
> [...]
> 
> You can also add this directly to the call:
> 
> ```lua
> :lua require'fzf-lua'.files({ fzf_cli_args="-i" })
> ```
> 
> ![screenshot-1639479379](https://user-images.githubusercontent.com/59988195/145985347-aab0de9c-5a13-4713-869d-475e35b5ae5c.png)

OK, I just reproduce that strange behaivour:

1. Inside `files = { ... }`. Put the `fzf_cli_args="-i"` __after__ the `fd_opts`, then it becomes smart-case like the image in my OP.
2. Now try putting it __before__, then it becomes ignore-case as your image shows.

**Comment by nyngwang** [comment]
It seems that it also works when I put `fzf_cli_args="-i"` the same level as `files`. Is this correct behaviour?

**Comment by ibhagwan** [comment]
> It seems that it also works when I put `fzf_cli_args="-i"` the same level as `files`. Is this correct behaviour?

Yes, that's how it should be, putting it at the setup function at the same level of `files` is equal to sending it like this:
```lua
:lua require'fzf-lua'.files({ fzf_cli_args="-i" })
```

**Comment by nyngwang** [comment]
> Should I remove some settings of fd lines from my settings? While I use fzf_cli_args, It doesn't work like the image you have shown.

This is a misreport. I guess that I was too sleepy and opened `live_grep_resume` when I tested it.

I have no issue with this now. Thank you so much!

**Comment by ibhagwan** [comment]
Btw, I have a suggestion for you, if you want to unerstand what this plugin does and what command gets piped to fzf run `grep`, `live_grep` and `files` with `debug=true` it will now also print the underlying command as the top line of the reults.

This will clarify the difference between `grep` (running a single command and having fzf do the matching):
```lua
:lua require'fzf-lua'.grep({ debug = true, search='pcall' })
```
![screenshot-1639492731](https://user-images.githubusercontent.com/59988195/146019396-081be82d-85ce-4401-a88b-5fad7e25251a.png)

to `live_grep`, which runs a new command based on what you type:
```lua
:lua require'fzf-lua'.live_grep_glob({ debug = true })
```
and then typing the search term `pcall -- *entry*` (you can also see the glob parsing in action here too):
![screenshot-1639492769](https://user-images.githubusercontent.com/59988195/146019429-8316c6b7-904c-4d54-a47d-1a5c446989f7.png)

You will notice that when using `grep` or `files`, **only one command is run**, it gets piped to fzf which then does fuzzy matching, with the `live_xxx` versions each keystrokes runs a new command (which you'll be able to see with `debug=true`).

**Comment by nyngwang** [comment]
it's very clear for me now! Thank you!

**Comment by ibhagwan** [comment]
> it's very clear for me now! Thank you!

Great!

On another issue that you had in the past, I just commited a change to make it clear when your regex is incorrect and needs an escape sequence (`\`), before it would just now show results, now it gives you feedback from `rg` (in the below, in order to search for `[` I needed to enter `\[`):

![screenshot-1639548383](https://user-images.githubusercontent.com/59988195/146132669-1b55ee63-08af-491f-a742-0507ee02e8e9.png)

**Comment by nyngwang** [comment]
Respect your kindness and carefulness! I like this feature!
