### ISSUE TITLE
[Feature Request] Two-step search: `files` follows by `live_grep`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#270]
As title. I think this might be challenging to implement. But if it's possible, this will beat any others existing plugins. Let me describe the current problem of `rg` with my workflow :

1. First I change my current working directory into the folder I want to search a phrase, without typing any command (with a plugin called `nvim-tree.lua`).
2. Then, I will provide more information to limit the results shown in the `FzfLua live_grep_glob`, so I might go back to 1. several times. This is because I haven't been used to the current `live_grep_glob`.(reason described below)
3. Now I run `FzfLua live_grep_glob` and use (usually one, it seems to be buggy when providing many) `-- ...` to further remove some impossible results in the list.

This flow is strange. Some points:

- I feel like that the 1. and 3. can be combined.
- You might ask: "Why not just use `FzfLua live_grep_glob`? It lets you type the keyword first and then put restrictions on the file path of the results". But first "providing path-limitations" and then "provide the keywords" is more ergonomic to me, since the keywords which I will provide are based on the path-limitations!

Regarding the "Two-step" in the title: For example, Say I launch `FzfLua files` and type some keywords to limit the file paths, then I can press some key-comb. to trigger a second level search __based on__ these path-limitations I have typed. It might be something like this:

```
Files > FooDir BarDir src components
   L Grep > the_keyword
   entry1: FooDir/BarDir/src/components/FooBar.ts, line 33, let the_keyword = ... 
   entry2
   entry3
   ...
```

My intuition is that this might not be easy to implement. But I think many people will like this feature (If I remember correctly, there are plugins trying to do this but the configuration is just too hard to setup.)

**Comment by ibhagwan** [comment]
It's probably not that complicated to add but would require lots of little code tweaks as the `rg` filtering would have to be done on the lua side, this is not something I'm interested in doing and/or maintaining once the function is released.

>Now I run FzfLua live_grep_glob and use (usually one, it seems to be buggy when providing many) -- ... to further remove some impossible results in the list.

It shoudn't be buggy, it probably behaves in a way you don't expect, `man rg` and read it thoroughly to understand what happens when multiple `--iglob` exists, the only thing fzf-lua does is add one ``--iglob=` flag for each spaced parameter, the underlying command is then run and you're seeing the results.

Run it with `debug=true` and then run the command in the shell/terminal and see the results, you probably need to tweak your search term to make it do what you expect.

I appreciated your enthusiasm for the project and your suggestions! I do feel that you should benefit greatly from getting deeper into lua and learning how to do this yourself, if you're willing to invest the time in learning lua/neovim I can provide guidelines how I would have gone about implementing this.

**Comment by nyngwang** [comment]
Do worry, I'm just a random plugin user who trying to contribute some idea to the thing I like, and happy to see its growth.

> if you're willing to invest the time in learning lua/neovim I can provide guidelines how I would have gone about implementing this.

Lua is in my study plan now because of NeoVim. And I will ask you when I have a specific problem, so you won't be annoyed.

**Comment by ibhagwan** [comment]
> Lua is in my study plan now because of NeoVim. And I will ask you when I have a specific problem, so you won't be annoyed.

Ty for your ideas and contribution, don’t worry I’m never annoyed :)

**Comment by ibhagwan** [comment]
Closing as I'm probably not going to do this.

**Comment by nyngwang** [comment]
I just realized that `pattern --filename.ext` is enough. I forgot to add `.ext` so no result is shown. Thanks a lot for your detailed comments! Just realized that you have spent a lot of effort answering all my questions.
