### ISSUE TITLE
Lag/flickering when typing too fast

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#271]
Here's a recording. Here's my settings

```lua
local path = require('fzf-lua.path')
local fzf = require('fzf-lua')

fzf.setup({
  winopts = {
    height = 0.85, -- window height
    width = 0.80, -- window width
    row = 0.35, -- window row position (0=top, 1=bottom)
    col = 0.50, -- window col position (0=left, 1=right)
    hl = {
      normal = 'TelescopePromptNormal',
      border = 'TelescopeBorder',
      cursor = 'Cursor', -- cursor highlight (grep/LSP matches)
      cursorline = 'CursorLine', -- cursor line
      search = 'Search', -- search matches (ctags)
      -- title       = 'Normal',        -- preview border title (file/buffer)
    },
  },
  fzf_colors = {
    ['fg'] = { 'fg', 'CursorLine' },
    ['bg'] = { 'bg', 'Normal' },
    ['hl'] = { 'fg', 'Comment' },
    ['fg+'] = { 'fg', 'Normal' },
    ['bg+'] = { 'bg', 'CursorLine' },
    ['hl+'] = { 'fg', 'Statement' },
    ['info'] = { 'fg', 'PreProc' },
    ['prompt'] = { 'fg', 'Conditional' },
    ['pointer'] = { 'fg', 'Exception' },
    ['marker'] = { 'fg', 'Keyword' },
    ['spinner'] = { 'fg', 'Label' },
    ['header'] = { 'fg', 'Comment' },
    ['gutter'] = { 'bg', 'Normal' },
    ['border'] = { 'bg', 'Normal' },
  },
  keymap = {
    builtin = {
      ['<C-d>'] = 'preview-page-down',
      ['<C-u>'] = 'preview-page-up',
    },
  },
  files = {
    git_icons = false,
    multiprocess = true,
  },
  git = {
    files = {
      cmd = 'git ls-files --exclude-standard --cached --others --deduplicate',
      git_icons = false,
      file_icons = false,
      multiprocess = true,
    },
  },
  grep = {
    rg_opts = string.format('%s %s', fzf.config.globals.grep.rg_opts, '--hidden -g "!.git"'),
    git_icons = false,
    multiprocess = true,
  },
  file_icon_padding = '',
})
```

https://user-images.githubusercontent.com/10972027/146738044-9683d8ec-7390-4888-abd4-610e4d43bfe2.mov

**Comment by ibhagwan** [comment]
The video shows a part I have very little control over, fzf is already spawned and the results are all in, let’s try the below and see what causes this:

- What is your `Fzf` version?
- What is your neovim version?
- Can you try with `global_resume = false` (was recently added)?
- Can you try with `files` instead of `git_files`?
- Can you try doing the same in the shell with fzf (just run `git ls-files|fzf`)?
- Can you try the above step inside a neovim term (`:new | term`)?
- Can you run a quick test with [`skim`](https://github.com/lotabout/skim) (need to add `fzf_bin = 'sk'` after installation)?

**Comment by yujinyuz** [comment]
fzf: 0.28.0
neovim: 0.6.0

@ibhagwan There seems to be not much of a problem after adding in the `global_resume = false` and it kinda feels a bit more snappy compared to my screen recording.

Thanks. I tried the other steps but I couldn't reproduce the issue anymore. Although I get this weird behavior when the text is too long. It doesn't happen when `fzf_bin = 'sk'` and also doesn't happen when running fzf in my terminal

<img width="1440" alt="Screen Shot 2021-12-21 at 01 04 54" src="https://user-images.githubusercontent.com/10972027/146804918-d2f71450-6210-43e1-ae11-41e363636a81.png">

**Comment by ibhagwan** [comment]
I see what’s happening, I suspected `global_resume` because it adds a callback that saves your typed query so you can continue where you left of with `:FzfLua resume`, it’s was the only code executed when you’re typing in the original video.

The reason it’s not happening in the terminal or with `sk` is because they don’t have the `change:execute` event set.

We definitely found the issue, I’ll have a fix for it in a couple of hours when I get on the computer.

**Comment by ibhagwan** [comment]
I have a solution for this which is to read the typed query from the terminal buffer (instead of `fzf` firing the `change:` event), what I'm struggling is how to detect the input was changed in the terminal buffer as some events are firing in the neovim terminal, https://github.com/neovim/neovim/issues/5018

I thought about `imap` as well but it doesn't have a way of capturing all keystrokes.

I'm very close to a proper solution but this will require a bit more digging.

**Comment by ibhagwan** [comment]
Turns out that this is not that easy to do with neovim, I'm still not sure how to get this data without using fzf's `change` event, for now I just added another option `global_resume_query` that you can set to `false` to disable the use of the change event which will give you the snappy typing behavior you wanted.

With `global_resume=true` and `global_resume_query=false` you will still be able to call `resume` and get the last window you were working **without the last typed query**.

Note that in regards to the second issue I've seen here which is fzf getting messed up when the query is too long, this seems to be an fzf issue, not much I can do about that other than [opening an issue upstream](https://github.com/junegunn/fzf/issues) (btw, `skim` seems to not have this issue).

The below is from `fzf` in the terminal, outside of neovim:
![screenshot-1640053390](https://user-images.githubusercontent.com/59988195/146860143-f66fa79b-c21d-418c-aca7-c904ce436a55.png)

**Comment by yujinyuz** [comment]
Thanks. I don't really use the global resume feature so I think I'm good with disabling it.

For fzf, it doesn't happen in my terminal for some reason.

https://user-images.githubusercontent.com/10972027/146874319-85ee3977-d07c-4c47-844f-672a85c406de.mov


I want to use skim but it sometimes has different results than fzf. And also the author claims that it is not as fast as fzf on large codebases.

FZF
<img width="720" alt="Screen Shot 2021-12-21 at 13 07 10" src="https://user-images.githubusercontent.com/10972027/146874497-7ef17434-efb9-4136-9a9f-30d58f0a62ef.png">

Skim
<img width="720" alt="Screen Shot 2021-12-21 at 13 08 05" src="https://user-images.githubusercontent.com/10972027/146874596-662fcbaa-4208-45bb-9e52-e5c2fa9d554c.png">

**Comment by ibhagwan** [comment]
>For fzf, it doesn't happen in my terminal for some reason.

The reason it doesn't happen for you is because it only happens with `--info=inline`, in the screenshot you're running the default (which is, not surprisingly, `--info=default`), try with `--info=inline`.

You can change the default in fzf-lua to avoid the bug under `fzf_opts`:
```lua
require'fzf-lua'.setup {
  fzf_opts = {
          ['--info'] = 'default',
  }
}
```

>I want to use skim but it sometimes has different results than fzf. And also the author claims that it is not as fast as fzf on large codebases.

It's possible the default search case senstivity is different with skim, try adding one of the below to `fzf_opts` (from man `sk`):
```help
       --case=[smart,respect,ignore]
              To ignore case on matching or not. (default smart)
```

**Comment by yujinyuz** [comment]
I've played around using the `--case` but I still don't get the same results to fzf.

I really like how it looks like when using skim since there isn't much padding around when used inside neovim

<img width="720" alt="Screen Shot 2021-12-21 at 13 36 45" src="https://user-images.githubusercontent.com/10972027/146877048-d509ac60-d971-4c2c-ae25-0e850a4aa6fa.png">

vs FZF

<img width="720" alt="Screen Shot 2021-12-21 at 13 37 52" src="https://user-images.githubusercontent.com/10972027/146877169-5b10a007-4ff8-467f-b1e1-ebdee4687190.png">



Anyway, thanks for the prompt response! Really appreciate it.

**Comment by ibhagwan** [comment]
FYI, the issue you accidelntally discovered was submitted upstream.

https://github.com/junegunn/fzf/issues/2692

**Comment by ibhagwan** [comment]
FYI, this is now fixed, I had to use two different methods to get the typed query but it works very well now and even works for `skim` even though it doesn't have support for the fzf `change` event.

When `global_resume_query = true` the option `--print-query` will be added to the fzf command line arguments which prints the query as first line when the user selects an item.

That alone did not solve saving the query on `abort` (when pressing `<C-c>` or `<Esc>`) so I created a terminal mapping for the fzf-lua buffer which retreieves the query from the first line of the buffer when either is pressed.

Now you should have both snappy typing and `resume` support :-)

**Comment by ibhagwan** [comment]
FYI, I just tested fzf `0.29.0` - it solves the long query overflow issue.

**Comment by nyngwang** [comment]
@ibhagwan You are the best maintainer I encountered in 2021! Thanks for making this beast that powers up NeoVim!

**Comment by ibhagwan** [comment]
Ty @nyngwang  <3
