### ISSUE TITLE
Window Disappears As Soon As Opening It

### ISSUE THREAD

**Issue by JuniorSuperTux** [ibhagwan/fzf-lua#278]
I tried installing fzf-lua with the instructions provided in README.md, and results turned out to be Packer simply showing a failed to install message:
```
 ✗ Failed to install ibhagwan/fzf-lua
  URL: https://github.com/ibhagwan/fzf-lua
  Commits:
    5396fa1 ctags: do not ignore '$' at the end of the pattern (revisit #219) (2 days ago)
```
Here's the installation config:
```lua
  use { -- FZF
    'ibhagwan/fzf-lua',
    run = './install --bin',
    requires = { {'kyazdani42/nvim-web-devicons'} }
  }
```
Since the instructions say that the **run** part in the config is not necessarily with fzf installed (I interpret this as having a fzf binary in `$PATH`), so I just had it removed and Packer seemed to successfully have fzf-lua installed. ***However, when I tried to use some basic commands, the window whether show for less than a second or doesn't even show.*** My config of fzf-lua is the same as the **Customization** part in README.md.

OS: Ubuntu Server 20.04
Neovim Version:  NVIM v0.5.1

**Comment by ibhagwan** [comment]
> ```lua
> use { -- FZF
>   'ibhagwan/fzf-lua',
>   -- This line is not necessary and not part of the README
>    run = './install --bin',
>    -- Wrapping this with curly brace twice is also not necessary
>    requires = { {'kyazdani42/nvim-web-devicons'} }
>  }
> ```

Your installation is wrong and was not copied properly from the README, you're trying to `run` a command meant for the installation of `fzf` inside `fzf-lua` (which according to your comment is not required for your install).

If you have `fzf` binary installed and in `$PATH` the below is all you need (**exact copy from the README**):
```lua
use { 'ibhagwan/fzf-lua',
  -- optional for icon support
  requires = { 'kyazdani42/nvim-web-devicons' }
}
```

> However, when I tried to use some basic commands, the window whether show for less than a second or doesn't even show

That tells me either `fzf-lua` can't find `fzf` or you misconfigured it, you can probably find the error message telling you what went wrong if you run `:messages`.

You can run a simple check to see if neovim can find your `fzf` by running `:new | term` - this will open a new terminal window inside neovim, try running `fzf` inside it, if you can't - then that's your problem, otherwise you probably misconfigured an option in which case I'd recommend to run an empty `setup({})` and then start adding configuration sections one by one to see what you probably copied wrong from the README.

**Comment by JuniorSuperTux** [comment]
I've tried doing some fixes, and here's the result:

https://user-images.githubusercontent.com/65844719/147398304-3fcf3b55-deb0-4415-8b09-9cc23ca4638b.mp4


I have fzf both installed in $PATH and the plugin way. And the line I selected in my `init.vim` file is just sourcing the file beside it.

**Comment by ibhagwan** [comment]
I can see the error in the `:messages` window, it seems your fzf does not accept the `--preview-window` flag options, this is most likely due to an old version of `fzf` installed on your machine taking precdence in $PATH over the one you installed.

Go to the shell and run `fzf --version` you'll probably see some old version like `0.23.0`, I think the preview window layout options were added around version 0.26.0.

You have a few options here:
- upgrade your OS `fzf`
- remove your OS `fzf` so the one installed from the plugin takes over
- setup the $PATH variable so that the new `fzf` installed by the plugin takes over the OS one

**Comment by JuniorSuperTux** [comment]
Thanks, that did work. What about adding the minimum required fzf version in README.md for less confusion?

Also, as I were trying out more commands, some commands like raw_fzf, fzf, core, ..., it shows the following error:
```
E5108: Error executing lua .../nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/fzf.lua:44: please run function in a coroutine
```

What is the proper way to fix that?

**Comment by ibhagwan** [comment]
> Thanks, that did work. What about adding the minimum required fzf version in README.md for less confusion?

Yes, I should do that.

> What is the proper way to fix that?

These are API functions meant to be used inside a lua coroutine, they aren’t meant to be used standalone, it’s mostly for developers.
