### ISSUE TITLE
When press `<Left>` to `git add` file with `GitStatus`, the cursor will be scrolled to top/first item

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#282]
As title. Is it possible that fzf-lua would be able to keep the cursor in the same position, so I don't have to scroll down again the find the next item I haven't read? The current one is inconvenient to me. I think this is related to that the result list needs to be updated, but the cursor position info. is not restored after I press `<Left>`.

**Comment by ibhagwan** [comment]
Unfortunately not inside fzf, in order to get the icons updated I have to reopen the fzf window from scratch which brings back the cursor to line 1.

I could potentially do it by saving the cursor position inside neovim and then restoring the line to where it was, the issue is the file order changes with certain operations (add->untracked, rename) so it won’t be accurate without further code to fix that.

Overall, I’m not really loving the added complexity to value ratio here so I’m not going to try and achieve that for the time being.

**Comment by nyngwang** [comment]
OK, maybe I should keep small changes in each commit.
