### ISSUE TITLE
getting error when previewer is enabled: No LSP client found that supports vscode.java.resolveJavaExecutable 

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#310]
Hi,

i just switched from telescope to this for testing, since telescope is a bit unusable for large projects, however:

I'm getting an `No LSP client found that supports vscode.java.resolveJavaExecutable` error when the file previewer is enabled. Any idea?

Another thing: an action to send all files and not just selected ones to the qf list would be awesome :-).

Regards

**Comment by ibhagwan** [comment]
> I'm getting an No LSP client found that supports vscode.java.resolveJavaExecutable error when the file previewer is enabled. Any idea?

Haven’t seen this one before, the preview window shouldn’t try to attach an LSP client, does this happen with all previews or just Java files, can you isolate this to certain file extensions or other conditions? Are you using neovim LSP in your project and have `autocmd`s setup for it?

Btw, as a temp workaround you can change the default previewer to `bat` and the issue will go away.

> Another thing: an action to send all files and not just selected ones to the qf list would be awesome :-)

Shouldn’t be a big deal to create a custom action that sends the keybind to `select-all` followed by `send-to-qf`, we can deal with this once this issue is solved :)

**Comment by abenz1267** [comment]
Hi,

this only seems to happen with java files. I'm using nvim-jdtls (with all the other needed things like vscode-java-test and java-debug).

I did not find a "select_all" (or select-all) action in the actions.lua .....that's where i looked at least.

Regards

**Comment by ibhagwan** [comment]
> I did not find a "select_all" (or select-all) action in the actions.lua .....that's where i looked at least.

That's because there isn't any in actions, as I wrote it would have to be a custom one :-)

Since the defult action already sends multiple choice to quickfix this can be easily achieved by creating a new fzf bind (or modifying the existing one) to perform both `select-all` and `accept`, just tested this one and it worked (modify this in your `setup()` function under `keymap.fzf`):
```lua
    fzf = {
      -- your other binds
      ...
      -- modify the current 'toggle-all' bind:
      ["alt-a"]         = "select-all+accept",
    }

```

**Comment by ibhagwan** [comment]
I'm struggling to find a way to disable LSP attachment on the preview buffer that isn't tied to your actual config, can you post your neovim LSP config? I'm mostly interested in your `on_attach` function, perhaps we can exclude  fzf-lua preview buffer there?

**Comment by abenz1267** [comment]
Sure, here you go (the relevant part): https://github.com/abenz1267/nvim/blob/master/ftplugin/java.lua

The on_attach function is in line 62.

**Comment by ibhagwan** [comment]
Can you try modifying it as per the below?

```lua
    on_attach = function(client, bufnr)
        if vim.api.nvim_buf_get_option(bufnr, 'bufhidden') == 'wipe' then return end
        require('jdtls').setup_dap({hotcodereplace = 'auto'})
        require('jdtls.dap').setup_dap_main_class_configs()
    end,
```

**Comment by abenz1267** [comment]
yes, this solved the problem

**Comment by ibhagwan** [comment]
> yes, this solved the problem

Great! I guess we can close this for now maybe one day I’ll find a way to disable LSP for preview buffers without involvement in the user’s config.
