### ISSUE TITLE
Feature Request: still list all git commits after checkout to an old one?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#312]
As title. My current scenario is the following:

1. I checkout to an old commit with `FzfLua git_commits`(by confirming the prompt with a `y`).
2. then I want to use `FzfLua git_commits` again to go back to the `origin/HEAD`, but found that the newest commit in the list is the current one.

Any idea? I think it would be more good when it's not a one-way tour.

**Comment by ibhagwan** [comment]
AFAIK that's not possible with `git` I tried to resolve this issue with `--reflog` but that creates additional issues, the checkout of old commit technically takes you back "to the past" of the git repo, that's why the old commit appears first, as the future wasn't written at that point in time.

The way I solve this is just run `git_branches()` and select `main` (or `master`) and you're back where you wanted :-)

**Comment by ibhagwan** [comment]
Forgot to mention if you do wanna play with it, you can just add `--reflog` to the git cmd, the issues I mentioned above are:
- when you get back to the topmost commit you're still in `detached` mode
- you also see rebase'd commits that would otherwise be hidden

If you still want to have this functionality just add `--reflog` to the command:
```lua
  git = {
    commits = {
      prompt = 'Commits❯ ',
      cmd = "git log --pretty=oneline --abbrev-commit --color --reflog"
    },
  }
```

**Comment by nyngwang** [comment]
I take your `git_branches()` method, thank you :)
