### ISSUE TITLE
How do I set the `btags` command specific directories or file?

### ISSUE THREAD

**Issue by ztoiax** [ibhagwan/fzf-lua#322]
`:lua require'fzf-lua'.btags({ cwd = "~/.cache/ctags/"})` is not work

**Comment by ibhagwan** [comment]
2 issues here (on my end), improper documentation and not properly expanding a custom ctags file (so `~` can work).

If I'm understanding your issue correctly your `tags` file is located in a different path than `<cwd>/tags`, to use a different ctag file you need to specify the option `ctags_file`.

The `cwd` option, as it's name suggestes, is used to specify the current working directory in the case it's different than the current one.

The command in your case should be:
```lua
:lua require'fzf-lua'.btags({ ctags_file = '~/.cache/ctags/tags' })
```

Coupled with `cwd` you can run the command anywhere regardless of nvim's `pwd`, for example:
```lua
-- assuming you have a project named 'project1' located at '~/project1'
-- and it's tags file is located at '~/.cache/ctags/project1/tags'
:lua require'fzf-lua'.btags({ ctags_file = '~/.cache/ctags/project1/tags', cwd='~/project1' })
```

Make sure to update to the latest commit https://github.com/ibhagwan/fzf-lua/commit/0f4ca97bb7063c73897b8c55204456bb88cddc3b so that `~` can be expanded properly to `/home/...`.
