### ISSUE TITLE
Tags may not jump to correct location for very long tag patterns

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#323]
If a tag's search pattern can yield multiple results and the pattern itself is long enough, `:FzfLua tags` may not jump to the correct location.

This is related to #219.

## Reproduction

1. Create the following file named `test.c` in its own directory:
    ```c
    #include <stdio.h>
    
    static void long_function_prototype(int parameter1, float parameter2, double parameter3, int*** triple_pointer);
    
    int main()
    {
    }
    
    static void long_function_prototype(int parameter1, float parameter2, double parameter3, int*** triple_pointer)
    {
    }
    ```

2. Save the file, then go to the containing directory and generate tags: `ctags -R`

    The following was my result using Universal Ctags:
    ```
    !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    !_TAG_PROGRAM_VERSION	0.0.0	//
    long_function_prototype	test.c	/^static void long_function_prototype(int parameter1, float parameter2, double parameter3, int*** /;"	f	typeref:typename:void	file:
    main	test.c	/^int main()$/;"	f	typeref:typename:int
    ```

3. Run `:FzfLua tags` and highlight the tag for `long_function_prototype`.
4. Press `Enter` to jump to the tag. Note that the cursor is moved to line 3 instead of line 9 as expected.

**Comment by ibhagwan** [comment]
Ty for the detailed report!

I'm not sure there's a solution to this, the pattern saved in the tags file is : 
```c
static void long_function_prototype(int parameter1, float parameter2, double parameter3, int***
```
which is then searched with `vim.fn.search()` the equivalent of running `/<pattern>`.

Running `/<pattern>` matches both the function declration and definition, since the declration is earlier in the file it is matched first and that's where the preview and the default action go to.

I do not wish to get into parsing of the post pattern info `f	typeref:typename:void	file`, that will add (what is IMO) unecessary complexity for a realteively small subset of edge cases.

If our end goal is to get to the function definition (without using LSP) it's not far, `2w` gets us to the function name then `:FzfLua grep_cword` 2 arrows down and and `<CR>` and you're there :-)

**Comment by shyun3** [comment]
Oh, I didn't notice the generated pattern itself was the issue. Looks like recent versions of Universal Ctags have a `--pattern-length-limit` option to control this behavior.
