### ISSUE TITLE
fzf-lua files leaves dangling neovim /tmp directories when executed in a git repository

### ISSUE THREAD

**Issue by gravndal** [ibhagwan/fzf-lua#329]
Steps to reproduce:
1. `$ mkdir -p fzf-lua-repro/.config/nvim`
2. `$ cd fzf-lua-repro`
3. `$ curl https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/minimal_init.lua > .config/nvim/init.lua`
4. `$ git init`
5. `$ env HOME=$(pwd) nvim`
6. `:FzfLua files`
7. `<ESC>`
8. `:quit`
9. Observe dangling `/tmp/nvim*/0` socket and directory.

Neovim version: `c5ac04331`
Nixos version: `22.05.20220127.d01b2cc (Quokka)`
Git version: `git version 2.34.1`
Fzf version: `0.29.0 (0.29.0)`

**Comment by ibhagwan** [comment]
That’s because of how `tempname` works, as you can see below I’m deleting the temp file at the end but the directory is probably going to stay dangling, not sure how to address this as the directory might contain other temp files unrelated to `fzf-lua`:

https://github.com/ibhagwan/fzf-lua/blob/0f4ca97bb7063c73897b8c55204456bb88cddc3b/lua/fzf-lua/fzf.lua#L24-L37

In any event, directory pollution inside `/tmp` shouldn’t be a big deal, they don’t take space and get cleared on boot.

**Comment by ibhagwan** [comment]
Found the issue, when `multiprocess=true` (the default), the command runs inside a wrapped neovim "headless" instance, when the command ends the code issues `os.exit` with the external program exit code, turns out neovim will not delete the temporary directory this way.

Solved in https://github.com/ibhagwan/fzf-lua/commit/4040e33683041c942f92a395fe5147ac704d4588

Ty for the report!
