### ISSUE TITLE
Opening files using fzf does not return to last edit position

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#339]
I have an autocmd

```vim
augroup ReturnToLastEditPosition
  autocmd!
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
    \ |   exe "normal! g`\""
    \ | endif
augroup END
```

and when I open files using `:FzfLua files` it does not jump to the last edit position.

However, the normal `:e **/plugins<TAB><CR>` works

[![asciicast](https://asciinema.org/a/dNt2bVjZReHC7yRnPJ86MIDi9.svg)](https://asciinema.org/a/dNt2bVjZReHC7yRnPJ86MIDi9)

**Comment by ibhagwan** [comment]
Maybe because of the below as this happens after `BufReadPost`:
https://github.com/ibhagwan/fzf-lua/blob/34281e4d8800a1c6ff2e7fd89d62368e9fa26127/lua/fzf-lua/actions.lua#L114-L116

Which moves the cursor to line 1 on files with no matches (I.e. not a `grep`), I think this is the issue, I’ll do some testing and revert.

**Comment by yujinyuz** [comment]
Thanks @ibhagwan
