### ISSUE TITLE
'files' command add strange symbols to file name

### ISSUE THREAD

**Issue by damanis** [ibhagwan/fzf-lua#347]
- `nvim --version`:
NVIM v0.7.0-dev+1093-g9ef569613
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az68-680

Features: +acl +iconv +tui

<details>

```lua
require('fzf-lua').setup({
    files = {
      fd_opts           = "--color=never --type f --hidden --follow --exclude .git, --exclude CVS --strip-cwd-prefix",
    },
})
```

</details>

### Description 
Usually (e.g., in my work tree), it works properly.
In nodejs git tree strange symbols added to files names, so Fzflua can't open selected file.
![2022-02-16_13h28_02](https://user-images.githubusercontent.com/65733488/154256683-9f9dfca9-2338-489d-8987-93511ab44fa8.png)

**Comment by ibhagwan** [comment]
This seems like an issue rendering the files/git icons, what terminal / font are you using?

Can you try running the below (no icons) and let me know if this works for you?

```lua
:lua require'fzf-lua'.files({ file_icons=false, git_icons=false })
```

**Comment by ibhagwan** [comment]
> Tested in neoray with two fonts: Go-Mono and Lucida Console.

What is `neoray`?

In order to have icons properly rendered you need to use a patched font such as [nerdfont](https://www.nerdfonts.com/), otherwise you will have issues rendering fonts with any plugin that uses [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) (nvim-tree, telescope, etc).

**Comment by ibhagwan** [comment]
I think this might also be related to your font/terminal interpretation of the `nbsp` character used by `fzf-lua` and is related to #326.

>Usually (e.g., in my work tree), it works properly. In nodejs git tree strange symbols added to files names, so Fzflua can't open selected file.

The reason is probably that your `nodejs` has a `.git` folder and fzf-lua is attempting to add the git icons, if none exists (i.e. no modifications) an empty space is drawn instead but the empty space is fzf-lua's `nbsp`.

You can try to change it to regular space instead, as suggested in #326:
```lua
:lua require'fzf-lua.utils'.nbsp = ' '
```

**Comment by ibhagwan** [comment]
Added the option to override the NBSP character via the initial setup:

```lua
require('fzf-lua').setup({
  nbsp = '\xc2\xa0',
})
```

This should solve your issue.
