### ISSUE TITLE
Edit search string for grep_cword and grep_visual 

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#348]
### Info
Hi, Thank you for the great plugin. I'm pretty happy with my current fzf-lua setup. I have 1 config that I think it would be nice to share with everyone. 

When we do grep_cword, or grep_visual, the search string is fixed. In my setup, I populated the search string after the fzf window is created, so that we can edit the search string as we want. If you find this behavior useful, I think we can make it the default for grep_cword and grep_visual

<details>
<summary>fzf-lua configuration</summary>

```lua
function _G.get_visual_selection()
  local _, csrow, cscol, cerow, cecol
  local mode = vim.fn.mode()
  if mode == 'v' or mode == 'V' or mode == '' then
    -- if we are in visual mode use the live position
    _, csrow, cscol, _ = unpack(vim.fn.getpos '.')
    _, cerow, cecol, _ = unpack(vim.fn.getpos 'v')
    if mode == 'V' then
      -- visual line doesn't provide columns
      cscol, cecol = 0, 999
    end
  else
    -- otherwise, use the last known visual position
    _, csrow, cscol, _ = unpack(vim.fn.getpos "'<")
    _, cerow, cecol, _ = unpack(vim.fn.getpos "'>")
  end
  -- swap vars if needed
  if cerow < csrow then
    csrow, cerow = cerow, csrow
  end
  if cecol < cscol then
    cscol, cecol = cecol, cscol
  end
  local lines = vim.fn.getline(csrow, cerow)
  local n = vim.fn.len(lines)
  if n <= 0 then
    return ''
  end
  lines[n] = string.sub(lines[n], 1, cecol)
  lines[1] = string.sub(lines[1], cscol)
  return table.concat(lines, '\n')
end

vim.cmd [[
  nnoremap <silent> <expr> <leader>d "\<cmd>lua require('fzf-lua').grep_project()\<cr>" . expand('<cword>')
  nnoremap <silent> <expr> <leader>D "\<cmd>lua require('fzf-lua').grep_project({ cwd = vim.fn.expand('%:p:h') })\<cr>" . expand('<cword>')
  nnoremap <silent> <expr> <leader>k "\<cmd>lua require('fzf-lua').blines()\<cr>" . expand('<cword>')

  xnoremap <silent> <expr> <leader>d ":\<c-u>lua require('fzf-lua').grep_project()\<cr>" . v:lua.get_visual_selection()
  xnoremap <silent> <expr> <leader>D ":\<c-u>lua require('fzf-lua').grep_project({ cwd = vim.fn.expand('%:p:h') })\<cr>" . v:lua.get_visual_selection()
  xnoremap <silent> <expr> <leader>k ":\<c-u>lua require('fzf-lua').blines()\<cr>" . v:lua.get_visual_selection()
]]

```

</details>

**Comment by ibhagwan** [comment]
Ty @sandangel  for the great suggestion, my comments below.

First, instead of duplicating the code of the `get_visual_selection` you can reference the existing one from [utils.lua](https://github.com/ibhagwan/fzf-lua/blob/f3857a98a7cd230448b6f3ec6117a699a39f1164/lua/fzf-lua/utils.lua#L300-L332):

```lua
_G.get_visual_selection = require'fzf-lua.utils'.get_visual_selection
```

Second, while I like the suggestion it could prove problmeatic as a default setting, the reason is that `grep_project` is equivalent to `grep` with an empty string which feeds **all lines of the project** into fzf, in large projects this could be a performance issue.

On the contrary when you `grep_cword|cWORD|visual` you're limiting the result set by sending the search string to `rg`, only then you're fuzzy matching the result set, it's fundementally different than running `rg ''` (empty string) and then doing the fuzzy matching.

**Comment by sandangel** [comment]
@ibhagwan Hi, I tried that already. But your utils will send the term code and quit the fzf window. That's why I had to duplicate the code and remove send term code. I also improved it a bit by using vim.fn.len instead of your M.tbl_length . 😁

**Comment by sandangel** [comment]
> On the contrary when you grep_cword|cWORD|visual you're limiting the result set by sending the search string to rg, only then you're fuzzy matching the result set, it's fundementally different than running rg '' (empty string) and then doing the fuzzy matching.

yeah I totally agree. If there is a way to edit search string (like using actions?) I would happy to go that way.

**Comment by ibhagwan** [comment]
>@ibhagwan Hi, I tried that already. But your utils will send the term code and quit the fzf window. That's why I had to duplicate the code and remove send term code. I also improved it a bit by using vim.fn.len instead of your `M.tbl_length`.

gotcha :-)

>yeah I totally agree. If there is a way to edit search string (like using actions?) I would happy to go that way.

That's called `live_grep` which utilizes fzf's `change` event to perform a `reload` (of the query), the difference is that once you do that you're no longer able to fuzzy match but only regex match (the results of the underlying `rg` query).

Run both `grep` and `live_grep` commands with `debug=true` and you'll be able to see what is the underlying query constructed by fzf-lua, eg`live_grep` with the query `now`:
>`:lua require'fzf-lua'.live_grep({ debug=true, search='now' })`
![image](https://user-images.githubusercontent.com/59988195/154781349-a1a345f9-9893-41f3-9daa-54197358b64f.png)

Unfortuntely there's no way with `fzf` to switch between the two (fuzzy to query reload) so you have to choose one or the other, [`skim`](https://github.com/lotabout/skim) has this option with `ctrl-q` to switch between fuzzy mode and "interactive command" mode but since it doesn't seem to be actively maintained and wasn't updated for a while I refrain from recommending it.

**Comment by ibhagwan** [comment]
I think I might have a solution for you, what about a bind (action) that closes the current window and switches from `grep` to `live_grep` and vice versa?

Try it out first, use `grep_project` with any string and close the window with `Esc` or `ctrl-c`, then open `live_grep({ continue_last_search=true })` when you are honed in on the term you wish to search exit the window and use `grep_last` which should open a fuzzy search for the results of the last `live_grep` command.

If this works well for you I can easily add a custom action that does that automatically.

**Comment by sandangel** [comment]
> Btw, forgot to mention one more thing, if you do wish to remain with the current setup it's probably better to use fzf's --query flag to feed initial query input without modifying the underying rg command,
I believe it's more consistent than feeding the argument through an expr=true mapping

I think this option provide a better result. The second option I can switch to the edit mode for search string, but when I switch back, the search string didn't change. Also the fzf window was flickering during the switch.

**Comment by ibhagwan** [comment]
> Also the fzf window was flickering during the switch.

This is easy to solve (with the `autoclose` option).

> The second option I can switch to the edit mode for search string, but when I switch back, the search string didn't change.

That’s because the search string is different than the Fzf query prompt, let’s assume that you do a `grep_cword` on the word `foo`, fzf-lua will construct an `rg` query for `foo` and feed the results into fzf. Now you search for `bar` and switch to `live_grep` - what should the underlying `rg` search be? Should it stay `foo` (as the custom action did), should it change to `bar` or should it be `foobar`? fuzzy matching`bar` on the result set of `rg 'foo'` is completely different than running `rg 'foobar'` or `rg 'bar'`.

As you see this is very personalized to what you’re actually after with many possible edge case scenarios so I tend to agree that perhaps for your needs the best results are with `grep_project` and the `query` flag.

**Comment by sandangel** [comment]
yeah, thank you very much for checking. I really appreciate the effort you put into the plugin, and also the time you spend to give me such detailed answer. ❤️
