### ISSUE TITLE
Support omnifunc / nvim-cmp completion

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#352]
### Description 
Hi, I would like to use fzf-lua like a source of completion items via omnifunc. Currently fzf does support it. Is there any plan to support this feature in fzf-lua?

**Comment by ibhagwan** [comment]
No such option unfortunately.

Personally, I wouldn’t bother with omnifunc, why not use (or write an extension for) [`nvim-cmp`](https://github.com/hrsh7th/nvim-cmp)?

**Comment by sandangel** [comment]
@ibhagwan Yeah I want to use `fzf` as the completion source for `nvim-cmp`. I'm checking its doc and found it does support `omnifunc` source, and I know that you can add completion items with fzf via omnifunc. So I just want to ask if fzf-lua also supports `omnifunc`. If we can have `cmp-fzf` completion source, that would be great.

**Comment by ibhagwan** [comment]
>Is there an API in fzf-lua for doing that without constructing fzf and rg command manually (reuse the config parsing code...)?

FzfLua is a wrapper around the `fzf` binary, it runs `fzf` with different arguments in a neovim terminal window, the fzf alogrithm is implemented inside the fzf binary, there's no API or direct access to the sorter/matcher.

Unless I'm misunderstanding the request there's no option to do what you want with `fzf` or `fzf-lua`, if you wish to create a fuzzy matching completion source you can use the C source code from [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim), if all you want is fuzzy completion for paths take a look at [cmp-fuzzy-path](https://github.com/tzachar/cmp-fuzzy-path) which does exactly that.

**Comment by ibhagwan** [comment]
I took a quick look at the code of `fzf#complete`, I personally find this out of scope of this plugin, IMHO making a proper completion source would require a bit more than just one function and obviously lots of customization, for example, it has hard coded commands for `find`, what if someone wants to use `rg` or use different flags?

```vim
inoremap <expr> <plug>(fzf-complete-path)      fzf#vim#complete#path("find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'")
inoremap <expr> <plug>(fzf-complete-file)      fzf#vim#complete#path("find . -path '*/\.*' -prune -o -type f -print -o -type l -print \| sed 's:^..::'")
 ```

Bottom line, I feel this type of functionality should be done as an afterthought inside this plugin but rather a plugin of its own.

**Comment by sandangel** [comment]
@ibhagwan quick question, can I reuse some of your functions here: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/libuv.lua to get a list of words from the coroutine that run `rg + fzf` command without interrupting the UI? Like running as sub-process under the hood, get the result and feed it to `cmp`?

**Comment by ibhagwan** [comment]
@sandangel, the code in `libuv.lua` contains helper functions to run and processs shell commands either inside your neovim instance or as a standalone lua file, for exmaple, in order to speed up performance and "multi-thread" lua, fzf-lua uses this file as a proxy to shell commands, for example, when using `multiprocess=true` (the default), files/grep/git will run an `nvim --headless` instance (different process), load the `libuv.lua` file and exeute the command (`rg`, `fd`, etc) and then process the results in the headless instance keeping the main instance UI responsive and lag free.

If you wish to see how the underlying headless command is constructed use `debug=true`:
```lua
:FzfLua files debug=true
```

>run `rg + fzf` command without interrupting the UI?

Now back to your question, I'm not sure what you're trying to do exactly, `fzf` is an interactive command with UI that doesn't provide instant feedback to the shell, `libuv.lua` can only handle commands that provide `stdio/stderr` output, you can only run non-interactive commands like `rg`, `fd`, `ls`, `cat`, etc.

If you can provide a bit more detail on what you wish to do with `libuv.lua` I'll be able to better help.

**Comment by sandangel** [comment]
hi  @ibhagwan thank you very much for the details. In that case I would like to spin up a headless neovim instance and run `rg`, then get the result as a list of completion items for nvim-cmp. I will try to use telescope-fzf-native to apply filters to the result later. Could you help me with this first step?

**Comment by sandangel** [comment]
Hi,  would like to see the generated command from `FzfLua grep_project debug=true`, but I guess it's only available with `FzfLua files debug=true`. 

> Now, what I'm not sure I understand is why do you even need this? if you wish to run and process the output of rg (or any command) you can use vim.fn.systemlistor if you need more control use libuv's vim.loop.spawn.

My plan is using the output of the above command (without icons) to create a completion source for `nvim-cmp`

**Comment by ibhagwan** [comment]
> My plan is using the output of the above command (without icons) to create a completion source for `nvim-cmp`

You definitely don’t need `libuv` for that, all you need is the code that generates the commands, it’s a much better approach than having to run through the entire Fzf + preview generation code only to get the underlying shell commands.

For `files`:
https://github.com/ibhagwan/fzf-lua/blob/f915ba0e9ab338f382cabcb6eebe98a4a0c93f96/lua/fzf-lua/providers/files.lua#L17-L34

**Comment by sandangel** [comment]
@ibhagwan after getting the command, I would like to use the code from `fzf-lua` to run the command in a performant way that doesn't block the UI. so I thought I would use the same approach that you did, spin up a new nvim instance in headless mode, run that command and get the result back to the main instance. I thought libuv is the place where you are doing that. I saw coroutine code... there

**Comment by ibhagwan** [comment]
> spin up a new nvim instance in headless mode, run that command and get the result back to the main instance.

The only reason it’s working this way with fzf-lua is because the nvim headless command is then piped into fzf inside a neovim term.

The only purpose of the libuv wrapper is to construct the entries for fzf with icons, colors, etc.

Since you mentioned you don’t need the icons why would you add the overhead of the headless instance, in your case the output of the headless command should be equal to the output of `fd` - you’re going to have to write proper code to parse the output on your main instance (with coroutines if you wish for it to be responsive) regardless, wrapping  it in a neovim headless instance adds nothing but overhead in your case.

**Comment by ibhagwan** [comment]
>`coroutinify` and run

You're missing a crucial part, `coroutinify` what? you need to decided how you want to run the `rg` command, as I mentioned in previous comments you can use `vim.fn.systemlist` or `vim.loop.spawn` (libuv).

If you wish to run things asyncrhounously you pretty much have to use `libuv` but the `coroutinify` in my code won't help much here, it's somewhat specialized towards the `fzf-lua.libuv` (with params, etc) and besides it's not a magic bullet, you can't just put something in a coroutine and expect it to be async and lag free, lua is single threaded and if you have blocking code you're going to have issues unless your code is structured properly.

Depending on the way you structure your code and the requirements of the other parts of your project **you may not even need coroutines** as [`libuv.spawn`](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit) is already async and has callbacks (look at `uv.read_start` callback).

Mu suggestions is first read and understand coroutines more deeply so you know exactly when to call `yield` and when to call `resume` in the context of `libuv.spawn` and processing stdout output from commands like `rg`.

Once you have that nailed down the rest should be easier although I can't really comment about the rest of your bullet points regarding fzf/fzy-native and nvim-cmp as I haven't experimented with said projects yet.

**Comment by ibhagwan** [comment]
@sandangel, FYI this was just implemented in https://github.com/ibhagwan/fzf-lua/commit/0bfae9b9552998f3be0e887bb4c154c8befd9809.

See the README and https://github.com/ibhagwan/fzf-lua/issues/688#issuecomment-1475424890 for more info.

**Comment by sandangel** [comment]
Oh wow, thanks a lot. Definitely try that out
