### ISSUE TITLE
FzfLua Tags very slow with bat/cat previewer

### ISSUE THREAD

**Issue by mikesart** [ibhagwan/fzf-lua#355]
### Info

- Operating System: Debian Testing
- Shell: Bash 5.1.16
- Terminal: xfce4-terminal 0.8.10 (Xfce 4.16)
- `nvim --version`: NVIM v0.6.1
- `fzf --version`: 0.29.0 (dc975e8)

When I do this:

```
tags = {
    previewer         = "builtin",
    prompt            = 'Tags❯ ',
    ctags_file        = "tags",
    git_icons         = true,       -- show git icons?
    file_icons        = true,       -- show file icons?
    color_icons       = true,       -- colorize file|git icons
  },
```

Opening up the tags window is very fast. When I switch previewer to "bat", it's incredibly slow as if it's running bat on every file as it loads the tags file?

And actually, on a project like UnrealEditor with a *lot* of tags (13,175,744) even the builtin previewer is unusable. The fzf ":Tags" command takes a few seconds, but ":FzfLua tags" takes forever and then shows nothing. This repros if I comment out my tags section above as well.

Below is my previewers section. Is this by design or am I doing something wrong here? Thank you!

```
  previewers = {
    bat = {
      cmd             = "batcat",
      args            = "--style=numbers,changes,header --color always",
      theme           = 'Dracula',  -- bat preview theme (bat --list-themes)
      config          = nil,        -- nil uses $BAT_CONFIG_PATH
    },
    builtin = {
      syntax          = true,       -- preview syntax highlight?
      syntax_limit_l  = 50,         -- syntax limit (lines), 0=nolimit
      syntax_limit_b  = 1024*1024,  -- syntax limit (bytes), 0=nolimit
    },
  },
```

**Comment by ibhagwan** [comment]
>Opening up the tags window is very fast. When I switch previewer to "bat", it's incredibly slow as if it's running bat on every file as it loads the tags file?

Unfortunately that's "by design", when using a previewer that isn't `builtin` fzf-lua needs to supply line number of the tag to the fzf entry (line), without it `fzf` won't know what line offset to display in the preview window, to do that it has to `rg` every single tag entry to find the right line and that's why it's so slow.

Althought I can find the line number and supply it to `bat` "on demand" I couldn't find a way provide the preview offset (i.e. "we loaded a 300 line preview and the match is at line 250") on demand, it needs to exist in the entry and provided using the fzf `FIELD INDEX EXPRESSION`.

I'm sure if I insist hard enough there's a way to make it work faster with previewers other than `builtin` but most users prefer the `builtin` anyways so I didn't bother.

**Comment by mikesart** [comment]
Well, I'm totally fine with builtin for tags, but even when using that:

1) With `junegunn/fzf`, it takes ~20 seconds for fzf ":Tags" to load all 12,416,043 tags.
2) After hitting enter on ":FzfLua tags" it takes about 6-8 seconds for the dialog to show up.
3) It then takes ~3 minutes to load 7,714,689 tags. There must be a hard limit it's hitting and not loading more?

Linux source is another good test. I've got 5,269,065 symbols there and it takes 1:40 to load them with FzfLua and 8 seconds with ":Tags".

So with bat or builtin it's for sure not handling tag files of these sizes well at all right now. :)

Definitely not a big deal - I use files and oldfiles far more often and FzfLua is working *great* for that right now. Just that I like your interface far more so at some point I'm going to take a crack at getting "FzfLua tags" working for me.

For what it's worth, I'm also using my own fork of `vim-gutentags` to regen tags when files change and for large projects I think using that and storing line numbers in the tagfile is going to be a more viable performant solution.

If you have time and are interested I'm more than happy to sponsor this project as well. Really appreciate your work on this - I like lua about a billion times more than vimscript. :)

**Comment by ibhagwan** [comment]
>Definitely not a big deal - I use files and oldfiles far more often and FzfLua is working great for that right now. Just that I like your interface far more so at some point I'm going to take a crack at getting "FzfLua tags" working for me.

TBH, `tags` isn't widely used (most people use `LSP` instead) so I never bothered with optimizing it as well as `files`, `grep` etc, only recently I converted from the `rg` every line approach (#245), so there's loads of room for improvement.

Not sure if you got to this level of detail of `fzf-lua` but files, grep and git all use `multiprocess` option where an `nvim --headless` instance is run externally (piped to fzf at the shell level) to prevent bottlenecks and lags and that's how fzf-lua handles extremley large datasets without issues (all while parsing the entries for icons, etc), if I were to do so for tags as well it would make a world of difference, there was no demand for this until now.

With the number of tags you're describing there's just no way the current single thereaded lua code can handle without lag, done right it will have to be the multiprocess approach.

>If you have time and are interested I'm more than happy to sponsor this project as well. Really appreciate your work on this - I like lua about a billion times more than vimscript. :)

Tysm, this is exactly how I felt and the main reason I embarked on this project, vimscript may be alright but I could never bring myself to write more than the absolute basics with it. Also, thank you for the offer but I don't plan on taking $ for this project.

**Comment by ibhagwan** [comment]
Also, I looked into how `fzf.vim` does the tag preview, due to the inability to get the correct offset inside the preview file it only previews the line range the tag resides in:

[tagpreview.sh:51](https://github.com/junegunn/fzf.vim/blob/1f7bfa4007043c30027b2cd79625e8aac5cff1f9/bin/tagpreview.sh#L51-L61)

Personally, I prefer to have proper before/after context (scrolling the preview up/down) but this might be a variable alternative for tags with bat/cat previewers.

**Comment by ibhagwan** [comment]
@mikesart, can you try the latest commit https://github.com/ibhagwan/fzf-lua/commit/95b82e7973861aae9db8dd3be2924af158d64f02?

I reworked the `tags|btags` code for the `multiprocess` approach explained in my earlier comments, test on the Linux kernel source code, I was able to open ~6M entries in under 60 seconds with the UI being responsive at all times:

![image](https://user-images.githubusercontent.com/59988195/156692954-a31057c8-fd3b-4ce2-b833-1e635612bf44.png)


I still didn't make the adjustments for parsing the entries with your custom tags coniguration, I will get to that later.

**Comment by mikesart** [comment]
This is far better. It takes a little while to load, as you point out, but the UI is responsive the entire time. Thank you!!!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/daf4f638192176c75c7399daddffea622ad69149

Just committed another change to better handle line numbers when those appear, tested it by generating my tags with:
```sh
ctags -R --c++-kinds=+p --fields=+iaS --extras=+q --excmd=combine
```

You can now use the `bat|cat` previewer with `tags|btags`, should work including proper line highlting and preview file offset:
```lua
-- both commands are the same
:FzfLua tags previewer=bat
:lua require'fzf-lua'.tags({ previewer="bat" })
```

The only thing left to solve is native previewer when the ctags file does not contain line numbers, I'm still thinking about it as I don't really love the idea of previwing only the relevant section of the file (which is what `fzf.vim` does).

**Comment by mikesart** [comment]
This is fantastic. Works so well. Thank you so much and please set up a sponsor link!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/fc77943cdf8e2a5e5431eef11f4ee4053f1c4dde

The above commit enables bat previews for ctags **without line numbers**, as previously noted since I cannot use the fzf field index expression to determine the correct offset I used the approach taken by `fzf.vim` which is to display a limited context of the preview file using `bat --line-range=<start>:<end>`

If you do have line numbers in your `ctags` the functionality remains the same, i.e. the entire file will be loaded into the preview and the correct offset will be displayed so if you don't mind the limited context (and inability to scroll the preview up/down) you can disable line numbers in your ctags.

Hopefully it works well for you too and we can conclude this issue :-)

**Comment by ibhagwan** [comment]
Btw, I must note that using `previewer=builtin` with tags is wrong, although it will appear to work (the correct file is loaded in the preview) it won't display the correct offset as it's expecting a (non-existent) line number in the entry, in order to use the builtin-tags viewer, delete the `previewer=` line or set it to `previewer=nil` so it will use the default internal previewer.

Below is how it should look like when working as expected.

> `previewer=nil` (default, note the tag match highlight)

![image](https://user-images.githubusercontent.com/59988195/156715821-a73ccb21-3448-4769-aaf7-509674e65d84.png)


> `previewer="bat"`

![image](https://user-images.githubusercontent.com/59988195/156715745-cf90fb37-e8a2-43b8-b7ed-77fccc2df134.png)

**Comment by mikesart** [comment]
Can you search for `G7_2` in the linux source tags? It looks like the code is trying to find `53;/^#define G7_2` as a file?

That might be unrelated to this issue though, so happy to close this one and create a new one. Thanks again!

**Comment by ibhagwan** [comment]
The line with `G7_2` has a tab between the macro and it's definition, due to the regex code using greedy matching (error on my part) it was failing to split the fields properly.

https://github.com/ibhagwan/fzf-lua/commit/b98bb2618c985733d1e51daeef9b4c02a570fd62 - this commit includes fixes for when the tag names contain slashes or tabs as well as ignoring the ctag comments (anything past `;"`), tested with `G7_2` and it now works with both the bultin preview and `bat`.

**Comment by mikesart** [comment]
Works great. Thank you!!

**Comment by ibhagwan** [comment]
Ty for the update and have a great weekend :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/af6d6c3785213079bb59bcdbfeea062fe33244a6 - FYI, latest commit adds a new provider `tags_grep`.

With huge `tags` file such as discussed in this thread fuzzy matching still takes a long time due to fzf having to index so many entries as evident when trying to search for `G7_2` in the linux kernel.

`tags_grep` aims to reduce that significantly in the cases where you roughly know what you're after, so the process now would be to run `tags_grep` and enter `G7` which will open `tags` limited to only entries which contain `G7` (only ~3k matches, almost instant using `rg|grep`), from there you can fuzzy match `G7_2`, all in less than a second.

Note that `tags_grep` is a shortcut to `tags({ search ='<query>' })` so if you wish to automate this you don't need to wait for the `Grep For>` input prompt and run the command directly instead:
```lua
-- both cmds below are the same
:FzfLua tags search=G7
:lua require'fzf-lua'.tags({search='G7'})
```

**Comment by mikesart** [comment]
There is a "bug" in universal ctags where it's duplicating entries:

https://github.com/universal-ctags/ctags/issues/1186

I wrote a de-duplicator app and am running it via g:gutentags_ctags_post_process_cmd.

It brings the tags for UnrealEditor from 2.6GB -> 1.5GB, but as you can guess 1.5GB of tags is still 7 million tags and still *really* slow. :)

This tags_grep fixes all of that. It's brilliant and so much more usable now. Thank you very, very much!!

**Comment by ibhagwan** [comment]
> I wrote a de-duplicator app and am running it via g:gutentags_ctags_post_process_cmd.
> It brings the tags for UnrealEditor from 2.6GB -> 1.5GB, but as you can guess 1.5GB of tags is still 7 million tags and still really slow. :)

That’s one big tags file, even after the dedup :)

And that was my logic, after a certain size it’s simply not usable to load everything into fzf each time you want to search for a tag, even 30 seconds is too long…

> This tags_grep fixes all of that. It's brilliant and so much more usable now. Thank you very, very much!!

Ty!

After you’ve used it for a while, if you feel you have some improvements/suggestions don’t hesitate to open an issue.

**Comment by mikesart** [comment]
I've got the below in my .vimrc now, so I can just type `:tagsgrep` and hit enter to search the current word, or `:tagsgrep blah`.

This is my "work in progress" symbol de-duper. (Linux only at the moment.) Definitely going to keep using this because it helps trim a lot of duplicate ctag symbols out of the namespace.

https://gist.github.com/mikesart/376fbefaf7e90f49c0e614677ecc145b

This with your tags_grep is so fast and usable! I am one happy clam. Thanks again!!

```
function! TagsGrep(is_inter, ...)
    if a:0 > 0
      let l:args = join(a:000)
    else
      let l:args = expand('<cword>')
    endif

    if a:is_inter
      call feedkeys(":FzfLua tags_grep search=" . l:args . "\<CR>")
    else
      execute ":FzfLua tags_grep search=" . l:args . "<CR>"
    endif
  endfunction

  command! -nargs=* TagsGrep  call TagsGrep(1, <f-args>)
  cnorea <expr> tagsgrep getcmdtype() == ':' && getcmdline() ==# 'tagsgrep' ? 'TagsGrep' : 'tagsgrep'
```
also:
```
  tags = {
    previewer         = "bat",
    prompt            = 'Tags❯ ',
    multiprocess      = true,       -- run command in a separate process
    git_icons         = true,       -- show git icons?
    file_icons        = true,       -- show file icons?
    color_icons       = true,       -- colorize file|git icons
  },
```

**Comment by ibhagwan** [comment]
>This is my "work in progress" symbol de-duper. (Linux only at the moment.) Definitely going to keep using this because it helps trim a lot of duplicate ctag symbols out of the namespace.

This is really cool, I've been programming C/CPP for a long time and had no idea you could embed the compile shell script inside the `.cpp` file. I didn't read the code yet but it seems quite extensive work "just" to de-dup your tags, sounds like project I would have embarked on as well lol

>I've got the below in my .vimrc now, so I can just type :tagsgrep and hit enter to search the current word, or :tagsgrep blah.

Very nice! (I'm also a sucker for grep'ing visual selection, might be nice here too)

Now this brings me to the new commit - https://github.com/ibhagwan/fzf-lua/commit/9094065d7969a9e7d7210239bb538b513dfd469a

I gave it some more thought and I realized `live_grep` would be perfect here. Not sure if you've played with it already but you can [read about the difference vs `grep` in the wiki](https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep).

Basically, `fzf` fuzzy matching functionality is disabled and `fzf` is turned into a ui selector only with each keystroke generating a new command, this is perfect for the use case where you rougly remeber the tag you're after but not it's exact spelling, with `tags_grep` you'd have to run multiple queries until you hone in on the right search term.

With `live_grep` (and now `tags_live_grep`) each keystroke runs a new `rg` (or `grep`) command with the typed query, tested it on the linux source code and it's extremley fast and very usable (use `debug=true` if you wish to see how the underlying command is generated) below I searched for `G7_D`, result was almost instantanous:

>`:lua require'fzf-lua'.tags_live_grep({debug=true})`
> see `tags.rg_opts` or `tags.grep_opts` if you wish to modify the command flags
![image](https://user-images.githubusercontent.com/59988195/156911872-fb4ed81d-92c6-483a-a7a3-c8a2db9b2c66.png)

Note that you can also start `tags_live_grep` with a query using the `search` option:
```lua
:lua require'fzf-lua'.tags_live_grep({search='G7_D'})
```

From here, you either found exactly what you're after or you can open `tags_grep` for further refinement using fuzzy matching.

**Comment by ibhagwan** [comment]
Alright, becuse why not I also added (thus matching the `grep_` feature-set: `tags_grep_cword`, `tags_grep_CWORD`, `tags_grep_visual`.

Also added proper display of the search term in the header (simiar to `grep`):
![image](https://user-images.githubusercontent.com/59988195/156916012-1df06195-dfea-4dbb-af8a-4bda45b6ef67.png)

**Comment by mikesart** [comment]
> This is really cool, I've been programming C/CPP for a long time and had no idea you could embed the compile shell script inside the .cpp file. I didn't read the code yet but it seems quite extensive work "just" to de-dup your tags, sounds like project I would have embarked on as well lol

It works great for something fairly small like this. Iteration times are just save and run. And yeah... only experienced your work on this so far, but I can for see you going after things and getting them done fast and right. Very cool! I'm at the point where ctags is taking 35 seconds and the de-duper 7. Probably need to parallelize ctags before spending more time speeding up anything else. :) I'm feeding ctags a list of files from ripgrep right now though. Ie:

```
rg --follow --files --no-ignore --hidden --no-follow --ignore-file ~/.rgignore_tags > "tags.files"
ctags -f "tags.temp" -L "tags.files"
```

Should be able to break that tags.files up into multiple and then coalesce them with the de-duper afterwards. I'm gone the next two weeks to Palm Springs for some tennis but will take a look at that when I return.

Your work and this de-duper thing has made tagging work really well on this massive codebase. Searching for something simple was incredibly slow and produced too much noise with several with __anon or no namespaces. I'd just wind up ripgrep'ing all the time. This live_grep thing is like lightning with the right data, and even tags_grep is super fast when I have a solid idea of what I'm searching for. Chefs kiss.

So I've got a question for you, if you don't mind. Here is my .vimrc:

https://gist.github.com/mikesart/40db01e70e60d4df7ed787f321be6768

A) There is that `:rg` function in there. I use it quite a bit by typing `:rg foobar` or just `:rg` over a cword and hit <enter>.

At that point, I have `RgRaw -S -F -- foobar` on the command prompt, I can hit Ctrl+F and add `-g "*.h"` or `-w` or `-t cpp` or whatever, then hit enter and have the results pop up in fzf then what I select in my quicklist after that.

Is there a similar thing with FzfLua?

B) I have `<leader>s` display a shortcuts popup, which you can see defined at the bottom of the .vimrc. It uses fzf to let me search the description or shortcut commands, hit enter, and have it fed to the command prompt where I can modify and then execute with enter.

It has no color and is fairly bland + rudimentary but I find it kinda useful to remind and search for vim commands I don't always remember.

Just throwing this idea out there in case you think it's kinda useful and get the itch to do something similar + way better. I mean, you've got a very nice cheatsheet already up on github but having it _inside_ vim ready to go tagged and fzf searchable??? :)

I need to spend some time learning lua as well. I did some stuff with vimscript, even got a commit into vim / neovim, but really really disliked it. You're busting butt on this very quickly with lua and it's inspiring. Not to mention super useful. Thanks again!

**Comment by ibhagwan** [comment]
> At that point, I have RgRaw -S -F -- foobar on the command prompt, I can hit Ctrl+F and add -g "*.h" or -w or -t cpp or whatever, then hit enter and have the results pop up in fzf then what I select in my quicklist after that.
> Is there a similar thing with FzfLua?

Absolutely! From the wiki: [Can I use ripgrep's `--glob|iglob` option with live_grep?](https://github.com/ibhagwan/fzf-lua/wiki#can-i-use-ripgreps---globiglob-option-with-live_grep)

The way you’d do it with `fzf-lua` is first run `:FzfLua live_grep_glob search=foobar`, from there you need to add the “glob separator” (default is ` --` (space,minus,minus), configurable) and then add the glob(s), to get the result you want either type what I just described or term or run directly:
```lua
:lua require'fzf-lua'.live_grep_glob({ search = 'foobar -- *.h' })
```
> B) I have <leader>s display a shortcuts popup, which you can see defined at the bottom of the .vimrc. It uses fzf to let me search the description or shortcut commands, hit enter, and have it fed to the command prompt where I can modify and then execute with enter.

I read the README of your plugin, that’s a great idea, not sure if that answers the same need but for my shortcuts I use [which-key.nvim](https://github.com/folke/which-key.nvim) with [this config](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/which_key.lua), what’s really cook about it is it knows to pause before the next press (as you describe), so say I want to run an fzf-lua shortcut I press `<leader>f` and if timeout reaches it will display a menu with all the continuation binds to `<leader>f`, so for example  if I then press `l` it will be as if I pressed `<leader>fl` and run `live_grep`, I’ll upload a screenshot of it below in a min from the computer so you can see what it looks like. You can even use for builtin keys (for new vimmmers) so it can complete basics like `de`, etc.


> I need to spend some time learning lua as well. I did some stuff with vimscript, even got a commit into vim / neovim, but really really disliked it. You're busting butt on this very quickly with lua and it's inspiring. Not to mention super useful. Thanks again!

I felt exactly the same with vimscript, I find it so unintuitive and not fun… but once I started playing with lua it all changed, I’m 100% sure you’ll feel the same, the best way to go about it is simply to embark on the project of converting your into from vim to lua, it might take a while to do properly with all your customizations but it’s totally worth it, I barely change [my neovim config](https://github.com/ibhagwan/nvim-lua) nowadays, it just works :)

**Comment by mikesart** [comment]
Awesome. Thanks again ibhagwan!

**Comment by ibhagwan** [comment]
Added a new feature to `grep|live_grep` as well as `tags_grep|live_grep` (since both using the same code) that you might find helpful, the ability to switch toggle between `grep` and `live_grep` on demand (by default with `ctrl-i` for "interactive", can be modified) while maintaining the same grep string:

Notice what happens in the below recording:
- open `tags` (no grep string)
- press `ctrl-i` to switch to `tags_live_grep`
- Input `g7_d` as the search term
- press `ctrl-i` again to go back to `tags` (which is now `tags({ search ='g7_d' })`)
- Input "data" which is now fuzzy matched on top of the results of the grep `g7_d`
- Press `ctrl-i` to go back to `live_grep` and modify the grep string to `g7_b`
- press `ctrl-i` to go back to `tags({ search = 'g7_b' })`
- Input "mark" which is now fuzzy matched on top of the results of the grep `g7_b`

>Btw, if the headers are annoying you, they can be be controlled with 2 options:
>- `no_header`: disables the header completley
>- `no_header_i`: disables only the `press <ctrl-i>` section of the header

![Peek 2022-03-08 22-58](https://user-images.githubusercontent.com/59988195/157390058-fabe3c10-2541-42df-bc92-bec4239587d0.gif)

**Comment by mikesart** [comment]
Ok, just got a chance to try this. It's really cool - love the ability to toggle between the two. Thanks & great work!
