### ISSUE TITLE
feature: utilize window width instead of #cols for flex layout threashold

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#356]
current, setting `flip_columns` in settings is a threshold against `vim.o.columns`.
This behavior is okay when fzf is opened in a float, but when it is using splits instead (something like `belowright new`), then the FZF window is opened inside the buffer, who's width may be less than the `#columns` of the vim window. 

For example, in this screenshot, I have two files open on a 14" laptop screen, full screened vim. Any meaningful preview is obstructed from view as it goes off the screen, but `flip_columns` doesn't deal with this as `vim.o.columns` is `201` in this case. 
(`vim.api.nvim_win_get_width(0)` is 100).

<img width="1512" alt="Screen Shot 2022-03-07 at 21 00 06" src="https://user-images.githubusercontent.com/16427330/157169356-4c5ac213-d917-4b37-9199-6a59b2385731.png">

I suggest changing `flip_columns` to utilize window width instead of columns. Or maybe an additional option for split users.

**Comment by ibhagwan** [comment]
It's already possible, you just need to create your own function that overrides `winopts`.

Turns out there was a bug in overriding the layout in native previewers so make sure to update to this commit https://github.com/ibhagwan/fzf-lua/commit/ffbb331c265a09a629c1683b4edbb98a49d470a6.

Add the below to your `setup` function (verified working with `split = "belowright new"`):

```lua
require'fzf-lua'.setup {
  winopts_fn = function()
    return {
      preview = {
        -- conditionally override the layout paramter thus overriding the 'flex' layout
        layout = vim.api.nvim_win_get_width(0)<100 and 'vertical' or 'horizontal'
      }
    }
  end
}
```

**Comment by ViRu-ThE-ViRuS** [comment]
perfect! thanks for the quick fix!
