### ISSUE TITLE
tags: Could no pop stack error

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#361]
<img width="1512" alt="Screen Shot 2022-03-10 at 05 08 53" src="https://user-images.githubusercontent.com/16427330/157668396-18d2a996-bd0f-4374-9884-8aaa684e5083.png">

found this bug while using `tags`, this just happens for the very specific search word `Field` in my configs colder. I dont know of other strings/folder content setups which end in this crash, buts its 100% reproducible using this query in my configs folder. 

please advise how to investigate this further

**Comment by ibhagwan** [comment]
Downloaded your configs file and tried with both `0.6.1` and the nightly and couldn't reproduce but this seems to be some internal neovim error returning from `vim.fn.search` or `vim.fn.clearmatches`.

https://github.com/ibhagwan/fzf-lua/commit/dd9db4cab96fe122767ea17cd83cff0abe214123 - latest commit wraps this section of the code in a `pcall` so the error should be prevented regardless, can you try and let me know if this solves it for you?

Make sure you're using the default previewer because this part of the code doesn't get called with `bat` previewer.

**Comment by ViRu-ThE-ViRuS** [comment]
yup! latest pull doesn't give me the error anymore. Ill switch to using `bat` for this though, because as you said, I prefer that XD

**Comment by ibhagwan** [comment]
> yup! latest pull doesn't give me the error anymore. Ill switch to using `bat` for this though, because as you said, I prefer that XD

Before you do that, can you please confirm that "double border" issue is also gone with the builtin previewer?
