### ISSUE TITLE
Allow Lua function as previewer

### ISSUE THREAD

**Issue by m42e** [ibhagwan/fzf-lua#367]
I would like to utilise fzf-lua in https://github.com/m42e/vim-lgh and I would like to utilise the preview. Currently I had a hard time, to get the preview working, as there is a lot of stuff happening in the background that needs to be understood. 

I would like to provide a Lua function as previewer and get the selected entry and provide the content to display as return value.

Do you think this is possible? Did I completely overlook the possibility?

**Comment by ibhagwan** [comment]
> Do you think this is possible? Did I completely overlook the possibility?

You did not overlook the possibility, supplying a function directly will not work but it’s also not that complex to achieve, the documentation is a lacking when it comes to extending FzfLua as I never got to writing that part properly, always preferred investing my time in new functionality and improvements.

That said, it’s not hard either and I can help you with this, the first thing we need to do is decide is which previewer to use:
- The “builtin” neovim previewer: a neovim window/buffer, can do pretty much anything you can do in neovim and is the default previewer for most providers
- Fzf “native” previewer: delegate the previewer to Fzf, can be used for anything but better suited for external shell commands (git commits, branches, status) use the native Fzf previewer with external shell utilities. Note that it can also accept custom data, not just shell commands.

If you can let me know which of the above you’d like to use for your preview and how you’d like to format the content we’ll take it from there.

> I would like to provide a Lua function as previewer and get the selected entry and provide the content to display as return value.

If you wish to use the neovim previewer and just want to have plain, non-colored lines in the preview window I can very easily add this type of functionality but usually when you want a custom preview it always comes with some other nuances, colors, special settings for the window (numbered lines yes/no? Highlight a specific line? Etc).

**Comment by m42e** [comment]
Thanks a lot.

Ok, tried what you mentioned with the `preview`. and managed to get it working. had to put extra `"` around the command to make it work.

I am rewriting my plugin in lua.

And one other thing. I do not list filenames (but just timestamps, as it represent the history of a single file) but `selected` would aways be prepended with a path before the receiving function will be triggered.
Is there a way around this and receive only the plain selection of fzf?

**Comment by ibhagwan** [comment]
> had to put extra " around the command to make it work.

To provide full control over the argument it is passed as is to the command line, I’d recommend wrapping your command with `vim.fn.shellescape` (instead of manually wrapping with `”`), it can take care of special characters in filenames that would otherwise break your command.

> And one other thing. I do not list filenames (but just timestamps, as it represent the history of a single file) but selected would aways be prepended with a path before the receiving function will be triggered.
Is there a way around this and receive only the plain selection of fzf?

If you don’t need file names just call `core.fzf` or better yet `core.fzf_wrap`, the latter is better as it saves all your options and selection processing function so you can call `:FzfLua resume` with your custom extension.

> Both `core.fzf|wrap` are exported by the main module so you can call `require'fzf.lua'.fzf_wrap(…)` directly.

https://github.com/ibhagwan/fzf-lua/blob/ab23fb6569166a6ba1416e78a8c3380bc2d44351/lua/fzf-lua/core.lua#L40-L48

For a minimal code example, take a look at the implementation of the `filetype` provider:

https://github.com/ibhagwan/fzf-lua/blob/ab23fb6569166a6ba1416e78a8c3380bc2d44351/lua/fzf-lua/providers/nvim.lua#L369-L387

**Comment by ibhagwan** [comment]
https://github.com/m42e/lgh.nvim/blob/d414ddbee695cfa2e40468cc062b82d38ec35ba6/lua/lgh.lua#L87-L112

Looks like you're all sorted out for now :-)

Closing, feel free to reopen if you need more help or changes to FzfLua's code to accomodate your plugin and I'll be happy to help.

**Comment by m42e** [comment]
Thanks a lot for your assistance :)
