### ISSUE TITLE
`cwd = subdir` set to a sub-directory of the current directory results in a erroneous new file being opened with a redundant prefix of `subdir`

### ISSUE THREAD

**Issue by zijian-x** [ibhagwan/fzf-lua#375]
### Info

- Operating System: Linux 5.17.1
- Shell: zsh 5.8.1 (x86_64-pc-linux-gnu)
- Terminal: alacritty
- `nvim --version`: `NVIM v0.7.0-dev+1376-g973e91007`
- `fzf --version`: `0.29.0 (dc975e8)`

- [x] The issue is reproducible with `minimal_init.lua`

### Description 
example directory tree:
```
root
.
| --- tmp
| --- . --- file
```
- launch `nvim` in `root` directory and run `FzfLua files cwd=tmp`
- select the only entry, which is `file`
- file with name `tmp/tmp/./file` is opened
- set `cwd =` option to a directory outside of `root` opens the correct file, only upon setting the path to a sub-directory from the cwd fails

**Comment by ibhagwan** [comment]
Ty for this report @zijian-x, this used to work properly but since the addtion of `multiprocess` it stopped working for relative paths since the external process had no awareness of the current working directory.

https://github.com/ibhagwan/fzf-lua/commit/92f063632e8b446101b0e2c991e9b7565faf1854 - this makes sure `cwd` is always converted to full path for the external process and then converted back to relative for the `cwd=` header display.
