### ISSUE TITLE
[Question] How to change the fzf statusline

### ISSUE THREAD

**Issue by ivanddm** [ibhagwan/fzf-lua#378]
Sorry to bother you again. I'm wondering if there is a way to change the fzf statusline colors (I know there is a setting in fzf.vim for this) or better yet just to get rid of it completely in the sense that it shows the default status line in terminal mode.

BTW, your `workdirs` function in your config, which is also mentioned in #194 is quite brilliant, yet simple. At the moment I'm using auto-session and session-lens for this but I just wanted a simpler solution to save the paths of my projects and be able to switch to them easily, and I think that your solution is quite good, so will try to implement in my config as well. It would be great if I could also save the working directory into the `workdirs.lua` file with a simple command, instead of entering the path manually, or save it automatically if I open neovim while in that directory in the terminal. Will try to come out with a script for this 🤞🏻.

Thanks in advance!

**Comment by ibhagwan** [comment]
> Sorry to bother you again. I'm wondering if there is a way to change the fzf statusline colors (I know there is a setting in fzf.vim for this) or better yet just to get rid of it completely in the sense that it shows the default status line in terminal mode.

Do you mean the neovim status line? If so that would depend on your status line plugin (I.e. lualine/feline/etc), almost all of them have a setting to exclude the status line for certain file types which people use to exclude (or use a minimal line) plugins like [packer](https://github.com/wbthomason/packer.nvim) or [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua). All you have to do is add `fzf` to the excluded file types.

Personally I used both feline and lualine but [ended up settling on `express_line.nvim`](https://github.com/tjdevries/express_line.nvim/issues/62). You can see my filetype exclusion [here](https://github.com/ibhagwan/nvim-lua/blob/2e5d0a13ea6e669409413fb938cc1d0668ea1cb6/lua/plugins/statusline/init.lua#L18-L25).

If you are referring to the information appearing on top of your fzf prompt that is controlled by fzf’s `--info` flag which you can control via the `fzf_opts` setting.

>BTW, your workdirs function in your config, which is also mentioned in https://github.com/ibhagwan/fzf-lua/issues/194 is quite brilliant, yet simple. At the moment I'm using auto-session and session-lens for this but I just wanted a simpler solution to save the paths of my projects and be able to switch to them easily, and I think that your solution is quite good, so will try to implement in my config as well. It would be great if I could also save the working directory into the workdirs.lua file with a simple command, instead of entering the path manually, or save it automatically if I open neovim while in that directory in the terminal. Will try to come out with a script for this 🤞🏻.

If you wish to use `workdirs` make sure to [use my latest version](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/fzf-lua/init.lua#L351) as the implementation link in #194 doesn’t support `:FzfLua resume` properly.

Let me know if you need help with your script, lua is easy and fun I’m sure you’ll enjoy creating it :)

**Comment by ivanddm** [comment]
Thanks a lot for guiding me in the right direction and answering my questions. I will come back to you regarding the `workdirs` implementation if needed then 👍🏻.

**Comment by ivanddm** [comment]
Hi again,

So far I implemented your `workdirs` function with a few tweaking when setting the working directory, using your original `set_cwd` function, namely, having the option to open a new tab with the selected directory, and use `lcd` instead of `cd`. I also want to trigger `FzfLua files` whenever I select a directory, however when I add this command in `set_cwd`, `fzf-lua` gets triggered but opens up in normal mode (so I have to go to insert mode to start typing...). This is my `set_cwd` function so far:

```lua
local function set_cwd(pwd, new_tab)
  if not pwd then
    local parent = vim.fn.expand("%:h")
    pwd = M.git_root(parent, true) or parent
  end

  if vim.loop.fs_stat(pwd) then
    if new_tab then
      vim.cmd("tabnew")
    end
    vim.cmd("lcd " .. pwd)
    require("fzf-lua").files()
    print(("Workingdir set to %s"):format(vim.fn.shellescape(pwd)))
  else
    print(("Unable to set wd to %s, directory is not accessible"):format(vim.fn.shellescape(pwd)))
  end
end
```

Do you know how I can trigger `require("fzf-lua").files()` so it opens the `fzf-lua` window in insert mode right after setting the working dir?

Thanks in advance!

**Comment by ibhagwan** [comment]
> Do you know how I can trigger require("fzf-lua").files() so it opens the fzf-lua window in insert mode right after setting the working dir?


Running a new terminal from within terminal opens in terminal insert mode, you can call `require'fzf-lua.actions'.ensure_insert_mode()` after opening the interface (which is what I use after running a command from the `builtin` provider).

**Comment by ivanddm** [comment]
> -- vim.cmd("startinsert") doesn't start INSERT mode 

Exactly! Thanks a lot!, `require'fzf-lua.actions'.ensure_insert_mode()` works like a charm!

**Comment by ibhagwan** [comment]
First things first, if it's working and you're happy with it then it's perfect and no changes are needed :-)

Now since you asked I'll provide my commentary:

I would replace native lua with neovim API where possible (not critical, just my preference):
- `os.getenv("HOME").."/.config/nvim/lua/paths.json"` -> `vim.fn.stdpath("config") .. "/lua/paths.json"`
- If you are to remain using `dkjson` (see my comment below) I would replace `io.XXX` with the [neovim libuv interface](https://github.com/luvit/luv/blob/master/docs.md), see the [file read sync sample code](https://github.com/luvit/luv/blob/master/docs.md#file-system-operations=):
```lua
local function readFileSync(path)
  local fd = assert(uv.fs_open(path, "r", 438))
  local stat = assert(uv.fs_fstat(fd))
  local data = assert(uv.fs_read(fd, stat.size, 0))
  assert(uv.fs_close(fd))
  return data
end

local data = readFileSync("workdirs.lua")
print("workdirs:", data)
```

>Since I'm not fluent in Lua, most likely I'm not reading and writing to the JSON file in the best way. The script does depend on the dkjson rock which is loaded using packer's use_rock. This might be an overkill as parsing the simple string array of paths should be somehow straight forward in Lua, but didn't have the time yet to look into it.

This is probably the biggest one, doesn't seem like you're actually using the JSON part of the library at all, that means a simple lua table should suffice and will also make reading and writing the table from file super easy.

Let's start with the file below named `workdirs.lua` located under `~/.config/nvim/lua`:
```lua
return {
  "dirA",
  "dirB",
  "dirC"
}
```

All you need to do to read the file directly into a table is call
```lua
-- this loads the entire table into the `dirs` local variable
-- assuming `workdirs.lua` exists directly under the `~/.config/nvim/lua` folder
local dirs = require("workdirs")
```

For the fault tolerant version (incase the file doesn't exist or has formatting issues):
```lua
local ok, dirs = pcall(require, "workdirs")
-- if loadings fails `dirs` will contain the error message
if not ok then print("error loading:", dirs) end
```

The above made reading/loading super simple and leaves us to write the code for the saving only. There are many ways to go about serialzing a lua table into a file, the first and easiest one I can think of is using `vim.inspect` which can format the table for you into a pretty human readble format (`:help vim.inspect`).

Again, assuming the above `workdirs.lua` file:
```lua
:lua print(vim.inspect(require("workdirs")))
-- should output
{ "dirA", "dirB", "dirC" }
```

So now all you have to do is use libuv's [`fs_write`](https://github.com/luvit/luv/blob/master/docs.md#uvfs_writefd-data-offset-callback=) to save the `vim.inspect` output:
```lua
local function writeFileSync(path, data)
  local fd = assert(uv.fs_open(path, "w", -1))
  uv.fs_write(fd, data.."\n", nil, function(_)
    uv.fs_close(fd)
  end)
end

writeFileSync("workdirs.lua", "return " .. vim.inspect(require("workdirs")))
```

This isn't your only option, if you still wish to use `json` (probably more robust that `vim.inspect`?) you can `vim.json.encode` (&`decode`), I use it in `fzf-lua` to write the `ueberzug` json command into the named pipe (using `uv.fs_write`, see below:
https://github.com/ibhagwan/fzf-lua/blob/58320a257957e4083f866cc6458b04a72493df33/lua/fzf-lua/previewer/builtin.lua#L354-L374

Hopefully this helps, good luck!

>P.S. Forgive me if there are errors here and there, these are all sketches I haven't tested the proposed code.

**Comment by ivanddm** [comment]
Thanks a lot for taking the time to write such awesome feedback and comments. I'm looking forward to implementing them in my scripts.

Yes you are completely right, at the current state, using a Lua table instead to store the paths is much better, and your approach on how to do that is great. The reason I started using json in the first place is because it will make it easy to store some extra info I would like to save in the future per path, such as a score of the numbers of visits to sort by that, and also the last buffer opened under that directory. In any case, your advice on using `vim.json` is really good (I didn't know it was available) instead of using an external library. So I will explore that route as well.

Thanks again!

**Comment by ibhagwan** [comment]
> The reason I started using json in the first place is because it will make it easy to store some extra info I would like to save in the future per path, such as a score of the numbers of visits to sort by that, and also the last buffer opened under that directory.

If you still prefer the lua table approach you can still so that with a key/value map in your `workdirs.lua`:
```lua

return {
  ["dirA"] = { [“key1”] = “val1”, [“key2”] = “val2” },
  ["dirB"] = { [“key1”] = “val1”, [“key2”] = “val2” },
  ["dirC"] = { [“key1”] = “val1”, [“key2”] = “val2” }
}
```

**Comment by ivanddm** [comment]
You are right. I think I will go for that option instead of using json. Thanks again!

**Comment by ivanddm** [comment]
You are right. I think I will go for that option instead of using json. Thanks again!
