### ISSUE TITLE
Not able to search in a director using live_grep_glob

### ISSUE THREAD

**Issue by tarunsharma20** [ibhagwan/fzf-lua#381]
### Info

- Operating System: macOS Monterey
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`: 0.6.1
- `fzf --version`: 0.30.0

- [x] The issue is reproducible with `minimal_init.lua`

```require('fzf-lua').setup``` is exactly same mentioned in README
</details>

### Description 
I am trying to search in couple of directories in my project with  ```live_grep_glob```. It's not working for me, but working fine for other cases.

#### Things not working for me are:
``` js
TODO -- foo    // Expecting to search only in 'foo' directory 
TODO -- foo bar    // Expecting to search only in 'foo' and 'bar' directory 
```

#### Things working fine for me:
``` js
TODO -- !*.jsx !*.js    // remove '.jsx' and '.js' file from search result
TODO -- !*.jsx *.md    // search in only '.md' files
TODO -- *.js    // search only in '.js' files
TODO -- !foo !bar    // don't search in 'foo' and 'bar' directory
```

Apart from it some times I'm facing a long delay/freeze while applying ```glob```  for something. It's random, might be when i am getting a file have huge content in search result. Have to restart nvim in that case.

Also is there a way to ignore some directories or files through ```glob``` for everything(```Files```, ```Grep```, ```Live_grep_glob```, etc.), and stuff defined through ```Live_grep_glob``` for ```glob``` will apply on top of that?

**Comment by ibhagwan** [comment]
The glob functionality matching is controlled by `rg`, fzf-lua is merly constructing the command for you, in order to debug this run `live_grep_glob({ debug = true })` and look at the first lines with `[DEBUG]`, then copy the `rg` command and run it in a terminal and find out why the glob doesn't work as you expect, i.e. for `<search> -- foo bar` the underlying command should look like:
![image](https://user-images.githubusercontent.com/59988195/162446906-fc82ac2e-1917-49a3-9286-7fa2f22ed883.png)

>Apart from it some times I'm facing a long delay/freeze while applying glob for something. It's random, might be when i am getting a file have huge content in search result. Have to restart nvim in that case.

Try to run it without a previewer and see if it freezes (it probably won't), then find it which are the problmatic files and we can either disable syntax highlighting for them or prevent them from being previewed using the `previewers.builtin` options:
```lua
    builtin = {
      syntax          = true,
      syntax_delay    = 0,
      syntax_limit_l  = 0,
      syntax_limit_b  = 1024*1024,    -- 1MB
      limit_b         = 1024*1024*10, -- 10MB
    }
```

**Comment by tarunsharma20** [comment]
Thanks :)

I was trying to use
```TODO -- foo```

Rg getting command below:
```rg --column --line-number --no-heading --color=always --smart-case --max-columns=512 --glob='foo' 'TODO'```

I should use
```TODO -- **/foo/**```

So that Rg will get:
```rg --column --line-number --no-heading --color=always --smart-case --max-columns=512 --glob='**/foo/**' 'TODO'```

it's really weird it should behave same for negative flag as well, but it's how Ripgrep working.

Once again, Thanks for quick response and awesome plugin :)

**Comment by ibhagwan** [comment]
> it's really weird it should behave same for negative flag as well, but it's how Ripgrep working.

Good to know I had no idea :)

**Comment by ibhagwan** [comment]
Btw, if you’re still having issues with previewing certain files due to neovim freezing you can always change the default previewer to `bat` (obviously you’ll need to install bat as well).

Neovim is single threaded so you’re always running the theoretical risk of something happening when neovim opens the preview buffer, by delegating the previewer to bat you’re moving that responsibility to fzf/terminal (different thread) so it will never get stuck, the only thing you’re losing is having to use a different highlight color scheme than your neovim one.

**Comment by tarunsharma20** [comment]
One more thing, can we append filters in ```glob``` instead of using multiple ```glob``` for example, I am trying to ignore some stuff globally. It's working fine as soon as i add new filters using ```Live_grep_glob```, it ignores previous filter. It's how ripgrep works.

### It's working fine
```rg --glob='!node_modules' 'TODO'```

### However when we add filter it'll be like (search in "foo" folder)
```rg --glob='!node_modules' --glob='**/foo/**' 'TODO'```

Now it'll also search "node_modules" inside "foo" folder, because it'll overwrite previous glob.

Can we do it like ```rg --glob='!node_modules, **/foo/**' 'TODO'```, where "node_modules" is in global config and "foo" added by ```Live_grep_glob```

_I know i am raising lot of issues, but it's because i have lot of expectations from this plugin. I was using FZF in vim previously. In neovim i was using telescope as they do have lot of features. However i realised, there are lot of issues even in basic things. I already replaced telescope with your plugin and it's really awesome 👍_

**Comment by ibhagwan** [comment]
> Can we do it like `rg --glob='!node_modules, **/foo/**' 'TODO'`, where "node_modules" is in global config and "foo" added by `live_grep_glob`

Anything is possible though that would create many other use cases that would need to be dealt with, for example the mixing of `glob` and `iglob` or globs defined with `-g` instead of double minus, just doesn’t seem very robust to me.

I have another idea, you can use the `filter` option to pipe an additional command to `rg` which acts as a filter, this is how it’s done with the `tags` provider to make sure the ctag headers are removed, you can exclude all lines containing a specific regex (using `-v` for invert match), the below works for both grep/live_grep.

>use `debug=true` to examine the piped command
```lua
require'fzf-lua'.live_grep({ filter = [[rg -v "node_modules"]] })
```

**Comment by ibhagwan** [comment]
> I know i am raising lot of issues, but it's because i have lot of expectations from this plugin. I was using FZF in vim previously. In neovim i was using telescope as they do have lot of features. However i realised, there are lot of issues even in basic things. I already replaced telescope with your plugin and it's really awesome 👍

As for this, please continue to raise the most complex issues, that’s is how this plugin gets better, latest example that I think you’ll find interesting is #373 (full control over glob option construction).

**Comment by ibhagwan** [comment]
Also, turns out that 2 weeks ago while implementing the solution for #373 I changed the way the glob parsing worked by a tiny bit which required the first glob to be typed after the separator for the search query to be adjusted (i.e. glob separator removed), https://github.com/ibhagwan/fzf-lua/commit/58320a257957e4083f866cc6458b04a72493df33 - latest commit restores the funcionality as it used to be, glob parsing now starts right after you type ` --` so you get results earlier without having to add any glob which makes it easier to decide what you want to filter out.

**Comment by tarunsharma20** [comment]
Thanks, That's what i was looking for

```map('n', '<leader>fl', '<cmd>lua require("fzf-lua").live_grep_glob({filter = [[rg --invert-match "node_modules|dist|lib|.git|package-lock.json|LICENSES.txt|LICENSES.json"]]})<cr>')```
