### ISSUE TITLE
When searching in home fzf uses 100% of cpu and stack overflows

### ISSUE THREAD

**Issue by zakissimo** [ibhagwan/fzf-lua#382]
### Info

```bash
~ ➜ uname -a
Linux desk 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux
~ ➜ kitty --version                
kitty 0.24.4 created by Kovid Goyal
~ ➜ echo $SHELL
/bin/zsh
~ ➜ nvim --version
NVIM v0.7.0-dev+1395-ge135adcb8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az243-81

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
~ ➜ fzf --version                    
0.30.0 (2093667)
```
- [ X] The issue is reproducible with `minimal_init.lua`

- I'm using default config

### Description 

![Peek 2022-04-09 02-40](https://user-images.githubusercontent.com/64891486/162549831-ca951cd0-078b-4cdc-a2c7-0d5388b98ddf.gif)

As you can see regular fzf loads relatively fast, cpu goes up to 40% and back down and finds around 200k files. But fzf-lua keeps finding more files ? Cpu is pinned to 100% and if left loading, the ram gets filled and linux freezes.

**Comment by ibhagwan** [comment]
>As you can see regular fzf loads relatively fast, cpu goes up to 40% and back down and finds around 200k files. But fzf-lua keeps finding more files ? Cpu is pinned to 100% and if left loading, the ram gets filled and linux freezes.

**First, why are there more files with `fzf-lua` than `fzf.vim`?**

That's probably due to your `fzf.vim` (or via `$FZF_DEFAULT_COMMAND`) using a different command than fzf-lua's default (which probably excldues many more files).

FzfLua's default command priortizes `fd` (which I assume you have installed) with the options confiurable under `files.fd_opts`:

```lua
fd_opts = "--color=never --type f --hidden --follow --exclude .git",
```

Once you find out what is the underlying command your `fzf.vim` uses you can configure fzf-lua to use the same options and the result will be the same.

**Second, regarding the speed/CPU load difference**, this is due to the extra processing required to parse the files and add the icons, if you wish to have the same performance and you're willing to dispose of the icons run the below and you'll get the same result:

```lua
:FzfLua cwd=~ files file_icons=false git_icons=false
```

Or the lua version:
```lua
:lua require'fzf-lua'.files({ cwd="~", file_icons=false, git_icons=false })
```

**Comment by ibhagwan** [comment]
Btw in order to test diferent options you don't necessarily need to configure anything, you can just run different commands using the `cmd` option:

```lua
:lua require'fzf-lua'.files({ cwd="~", file_icons=false, cmd="fd --type f" })
```

You can also enable `debug=true` and fzf-lua will show you the underlying command as the first result:
> you can use `find`, `ls`, `git ls-files` or whichever file-producing command you wish
```lua
:lua require'fzf-lua'.files({ cwd="~", cmd="fd --type f", debug=true })
```
Which will result in:
![image](https://user-images.githubusercontent.com/59988195/162551636-c90292e1-159d-42b5-a3ef-46e9393d8bdd.png)

**Comment by zakissimo** [comment]
First let me thank you for your patience and your detailed explanation it's in moments like this that learning becomes easy and enjoyable. Secondly, you were right (no surprise), I have in my .zshrc the following:

```bash
export FZF_DEFAULT_COMMAND="rg --files --hidden -g '!{**/node_modules/*,**/.git/*}'"
```

So  I started playing with commands as you suggested and with the following I get output I'm familiar with. 

```lua
:lua require'fzf-lua'.files({ cwd="~", '!{**/node_modules/*,**/.git/*}', cmd="fd --type f --hidden" })
 ```
And I don't even have to disable icons!
Thanks again for the support!

**Comment by ibhagwan** [comment]
Ty for the kind words @zakissimo!

Don’t hesitate to ask anything / open new issues.

Also note that if you wish to “match” your `fzf.vim` config with `fzf-lua` and not have to send `cmd` with each call you can define it inside setup under `files` and you’ll get the same result, I.e.:

```lua
require'fzf-lua'.setup {
  files = {
    cmd = "rg --files --hidden -g '!{**/node_modules/*,**/.git/*}'"
  }
}
```
