### ISSUE TITLE
Issues with LSP code actions + null-ls

### ISSUE THREAD

**Issue by jose-elias-alvarez** [ibhagwan/fzf-lua#39]
Hello! Thanks for the great plugin – it's great to have fzf + Lua with sensible out-of-the-box functionality and easy configuration. 

I'm the author of [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim), which (among other things) allows injecting code actions from within Neovim. To correctly generate actions, null-ls relies on checking the filetype of the current buffer at the time the request is sent, but due to how fzf-lua is structured, the request is sent from within an fzf buffer, so the check fails. (For reference, everything works as expected with Telescope and lspfuzzy).

This isn't an issue with actual language servers, but both lspfuzzy and Telescope support null-ls code actions, so I wonder if it's possible to support them here, too. One option is to use `buf_request_sync` to get code actions before opening the picker, which is what [Telescope does](https://github.com/nvim-telescope/telescope.nvim/blob/2c573b9d12f421cec74a215f79b25591fe083352/lua/telescope/builtin/lsp.lua#L148). Another advantage of this approach is that we'd know whether code actions are available before opening fzf, which would avoid the current flickering effect when calling `:FzfLua lsp_code_actions` when no code actions are available. (Using `buf_request_sync` for other LSP requests would solve this issue elsewhere, too.)

Let me know what you think and if there's anything I can do to help.

**Comment by ibhagwan** [comment]
Hi and ty for letting me know.

Going with the LSP async functions was a design choice, I have no control over the LSP’s and they don’t always respond immediately (especially on larger requests such as workspace symbols), that can hang the UI and is the main reason I went with async everywhere.

That said, changing code action only to `buf_request_sync` shouldn’t be a big deal since the replies are always small, I’ll make the change later today.

For the record Telescope works differently, it runs only blocking LSP requests which isn’t optimal IMO, `lspfuzzy` is different as it replaces the default handlers which another option I opted against as I like to give the users an option to use the default actions should they choose (send to quick list, etc).

**Comment by ibhagwan** [comment]
I added the option to enable blocking LSP calls (i.e. use `buf_reqest_sync`) in all LSP providers, you can enable that globally by setting `async_or_timeout` option during `setup()` (the below sets the timeout to 3 seconds):

```lua
require'fzf-lua'.setup {
lsp = {
    async_or_timeout  = 3000,       -- set to timeout|false for blocking calls
  }
}
```

Or use the same option to set it individually each call (or keybind mapping):
```lua
:lua require('fzf-lua').lsp_definitions({ async_or_timeout = 5000 })
```

Alternatively you can just send `sync = true`, `async = false` or `async_or_timeout = false` to use the default `timeout = 5000`:
```lua
:lua require('fzf-lua').lsp_code_actions({ async = false })
```

If this solves your problem feel free to close the issue.

**Comment by jose-elias-alvarez** [comment]
Works perfectly, thank you! I really appreciate having the option to make all LSP requests synchronous.

**Comment by ibhagwan** [comment]
> Works perfectly, thank you! I really appreciate having the option to make all LSP requests synchronous.

Very happy this worked out, cheers :)
