### ISSUE TITLE
Select file (via `files()`) is opened in wrong split

### ISSUE THREAD

**Issue by WhyNotHugo** [ibhagwan/fzf-lua#397]
### Info

- Operating System: ArchLinux
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: v0.7.0
- `fzf --version`: 0.30.0 (2093667)

- [x] The issue is reproducible with `minimal_init.lua`

#### fzf-lua configuration

```lua
      -- replace the `config` line in the same with this:
      config = function()
        require"fzf-lua".setup({
          winopts = {
            split = "belowright new",
          }
        })
      end,
```

### Steps to reproduce 

- Start out with two splits (a top and bottom one).
- Focus the top one
- Run `require"fzf-lua".files()`.
- Pick a file

### Description

The picked file is **always** opened on the bottom split, but I want it to open on the previously focused split.

I have `belowright new` in my config because I want the `fzf` split itself to be opened below the current one -- but after I pick a file, I want it to open on the previously focused split, not always on the bottom one.

Is this a bug, or am I doing something wrong?

**Comment by ibhagwan** [comment]
Just tested this with my nvim config and it worked as expected but not when using `minimal_init.lua` **with the `split`** setting.

This is caused due to the default neovim split behavior, if you have two splits open, while focusing on the top window use `:belowright new` and then quit the new window  with `<C-w>q` the focused window is now the bottom window.

https://github.com/ibhagwan/fzf-lua/commit/36278656faa7b63e88f68f387f9f231683a1a01d - makes sure to switch back to the correct source window.

**Comment by WhyNotHugo** [comment]
Oh, that makes sense. Thanks for the quick fix.
