### ISSUE TITLE
feature: utilize field type information, when using tags

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#406]
universal-ctags has the option "--fields=+K" which writes type of the tag as well in the tags file for each tag.

this can be useful when searching through tags: 
consider the case where you have entries `SYS_WRITE` and `sys_write`, one is a macro/variable/const, one is a function. When I search for `sys_write` in `tags`, both options show up, and `SYS_WRITE` is the one actively selected ( I dont have any custom ordering arguments anywhere ).

this issue, is a feature request to be able to type `sys_write function` or `write function` to be able to narrow down type and name. 

The way it works right now allows fuzzy matching through both file names and the tags, this would just add another word on the line which we can fuzzy match against.

**Comment by ibhagwan** [comment]
Due to Fzf limitations the only way this could be done is through a modification of grep arguments in the same way `live_grep_glob` is parsing the query arguments after the separator and forming a new `rg` query from it.

Perhaps you can achieve what you want using a custom `rg_glob_fn` together with with `opts.filename` to limit the search only to the `tags` file (essentially what `tags_live_grep` does), see how to write a custom query handler in #373.

If you go down this route also look how tags builds it’s arguments for `live_grep` it’s pretty simple:

https://github.com/ibhagwan/fzf-lua/blob/5fbbc3b6536bd3a02d5b7b5b62e038f084ad957b/lua/fzf-lua/providers/tags.lua#L93-L103
