### ISSUE TITLE
[Bug] Live grep prompt repetition

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#434]
### Info

- Operating System: arch
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.7
- `fzf --version`: 0.30.0

- [ x] The issue is reproducible with `minimal_init.lua`

<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    fzf_args = '--prompt="> "'
})
```

### Description 
1. Run `FzfLua live_grep`
2. Type 'hi'
3. Press escape
4. Run `FzfLua resume`
5. Prompt is populated with '> hi' rather than solely hi

This only occurs with live_grep, not with files.

**Comment by ibhagwan** [comment]
This happens because you are sending the prompt via `fzf_args`, in order to get the resume string fzf-lua reads the first line from the fzf buffer and then removes the prompt part but since you used `fzf_args` directly it doesn’t know the prompt length.

Does the same happen if you use `lua require'fzf-lua'.live_grep ({ prompt = '> ' })`?

**Comment by barrett-ruth** [comment]
That resolves the issue. Still, I am curious as to why `files` is not affected by `fzf_args`, while other pickers such as `buffers` and `live_grep` are.

**Comment by barrett-ruth** [comment]
That makes sense. The pace you work at, especially for a well established plugin, is incredible. Thank you!

**Comment by ibhagwan** [comment]
> That makes sense. The pace you work at, especially for a well established plugin, is incredible. Thank you!

Ty @barrett-ruth!

Please make sure to update to the latest commit, I forced pushed a couple to make sure this fix doesn't break when using `--prompt` without any surrounding quotes or double quotes. so if you don't care about the post space you can specify `--prompt=>` (instead of `--prompt=">"`).

**Comment by ibhagwan** [comment]
It is also worth noting that `live_grep` will prefix `*` to your prompt, that is by design, it is meant to help the user differentiate between having to use regex in `live_grep` vs the fuzzy matching in `grep` (or any other provider), this is especially helpful when using `<C-G>` to switch back and forth between live grep and grep.
