### ISSUE TITLE
Loving this plugin ❤️ 

### ISSUE THREAD

**Issue by alextes** [ibhagwan/fzf-lua#437]
I find fzf.vim a bit user-unfriendly sometimes. Or put more generously, aimed at power users that prefer to spend a couple of hours hand integrating the plugin to gel well with their existing setup.

I prefer a plugin with sane defaults that you update if something doesn't gel well with your existing setup. This plugin is 👌  for that.

After a couple of days, I can say this is pretty amazing. I'm especially enjoying, but also still learning how to apply this double grep that seems to let you grep your grep 😂 ? Anyhow, it's useful considering live grep doesn't let you use globs/regex.

Thanks for a great plugin!

**Comment by ibhagwan** [comment]
Thank you for the kind words @alextes.

One goal of this plugin was to make it work out of the box without having to fiddle with every little option (while still keeping the “power users” customizability), I’m happy to learn it serves this purpose.

Now regarding the “grep your grep”, I suggest you read both these entries from the Wiki:
https://github.com/ibhagwan/fzf-lua/wiki#whats-the-difference-between-grep-and-live_grep
https://github.com/ibhagwan/fzf-lua/wiki#can-i-use-ripgreps---globiglob-option-with-live_grep

> Anyhow, it's useful considering live grep doesn't let you use globs/regex.

You got it the other way around, `grep` is just a fuzzy match on top of previously grep’d lines, `live_grep` on the other hand is a very powerful tool that **enables you to use regex/globs** (and even custom `rg` flags if you’re willing to go the extra mile with custom handlers), read issues #167 and #373 and play around with `:FzfLua live_grep_glob debug=true` and you’ll learn a few helpful tricks.

Summarized, `live_grep` is meant to perform an **exact match** regex+glob search which is then followed by `grep` (using `<C-g>` or `grep_last`) in order to further refine the results **with fuzzy matching**.

Don’t hesitate to ask anything or open issues if you need help, even for seemingly minor issues.

**Comment by alextes** [comment]
Oh I see, awesome! I'll go read those pages. Thanks ibhagwan!

**Comment by nyngwang** [comment]
Lol, why is the heart so big on macOS. Anyway, let me leave a comment here so I will remember to find time to read the links!
