### ISSUE TITLE
Preview or opening files generated via `set backup` doesn't work properly

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#453]
### Info

- Operating System: MacOS
- Shell: fish
- Terminal: kitty
- `nvim --version`: NVIM v0.7.0
- `fzf --version`: 0.30.0 (brew)

- [x] The issue is reproducible with `minimal_init.lua`

### Description 

I've enabled vim to create backup files that looks something like this in my config

```lua
-- Enable backups
vim.opt.backup = true
-- Ensure filename uniqueness with //
vim.opt.backupdir = { vim.fn.stdpath('data') .. '/backup//'}

vim.api.nvim_create_autocmd('BufWritePre', {
  pattern = { '*' },
  callback = function()
    vim.cmd [[let &bex = '@' . strftime("%F.%H:%M")]]
  end,
  desc = 'Rename backup files',
})
```

The problem is that if I try to `:FzfLua files`, it can't seem to preview the files correctly nor open them.

It works with Telescope and Snap and also regular fzf so I'm not sure what's wrong.

Here's a video

https://user-images.githubusercontent.com/10972027/174489391-2597a8de-16af-438c-9f35-a5036cf0b736.mp4

**Comment by ibhagwan** [comment]
From first glance I suspect it has something to do with the `%` in the name as it might interfere with lua string pattern operations, I’ll check.

**Comment by ibhagwan** [comment]
The issue is having `:` as the **last part (after the extension)** which fzf-lua uses as an indicator for the result containing `:line:col:` (used in anything that has lines/columns, i.e. `grep`, `lsp_xxx`, `quickfix`, etc).

While I can quickly "hack" the code to ignore parsing of this part for `files` this still won't solve the issue for the other providers which need to use lines/columns in the previewer.

Consider filename `file.c:123` with the following contents (removed indent spaces on purpose):
```c
line 1: switch (a) {
line 2: case foo: ...
line 3: case bar: ...
line 4: }
```

Now run a `rg --vimgrep case`:
```
❯ rg --vimgrep case
file.c:123:2:1:case foo: ...
file.c:123:3:1:case bar: ...
```

- How do you determine (based on `:` as delimiter) with finality the lines/columns of the match?
- What if the filename is `file.c:123:456` instead?
- What if the code text also contains a pattern similar to `:x:y:`?

This would require some more thought on my end to solve properly, for the moment, the simplest workaround would be to remove the `:` from the backup file format (if at all possible to control the format?).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/466dccca5c878385be342768c9f0ddb7d02e2675 - should work now.

**Comment by yujinyuz** [comment]
Thanks for the immediate action @ibhagwan really appreciate it

**Comment by ibhagwan** [comment]
My pleasure @yujinyuz :-)
