### ISSUE TITLE
help_tags could change window sizes 

### ISSUE THREAD

**Issue by monkoose** [ibhagwan/fzf-lua#457]
As I understood correctly by design `FzfLua help_tags` preopen help window, but if you cancel fzf with `Esc/C-c` etc without opeing help, this could change the window sizes - a little bit annoying. 

**Consider to remember window sizes before opening `FzfLua help_tags` with `:h winrestcmd()` and on cancel restore their sizes.**

Also if there is already opened help window on cancel it will close it (can't be restored with `winrestcmd()` because it can't restore sizes if window numbers were changed by closing or opening new). Maybe workaround can be found?

And i use it more like fuzzy-searcher through help, don't care much about preview. But it behaves the same even with disabled preview (but this preopened window as I understood required only for preview), maybe it can be configured too, if it wouldn't complicate the logic too much?

**Comment by ibhagwan** [comment]
Not a big fan of adding further complications to what is already not straight forward behavior.

This behavior is due to the fact I wanted to avoid having to save all the help tags in memory with their corresponding help file.

I’ll give it another look for a more optimized solution.

> And i use it more like fuzzy-searcher through help, don't care much about preview. But it behaves the same even with disabled preview (but this preopened window as I understood required only for preview), maybe it can be configured too, if it wouldn't complicate the logic too much?

Opening the help window is only required for the previewer, disable the previewer and you can use it as a fuzzy finder only interface.

You can use `:FzfLua help_tags previewer=false` or during setup:

```lua
helptags = { previewer = { _ctor = false } }
```

**Comment by monkoose** [comment]
> You can use :FzfLua help_tags previewer=false or during setup

Thank you, seems like I tested this wrong. Now it doesn't preopen help window without preview.

**Comment by ibhagwan** [comment]
@monkoose, try it out now, new help tag previewer (now default) that uses the corresponding help file and highlights the tag in similar fasion to the way `ctags` previewer works.

Let me know if this works well for you?

**Comment by monkoose** [comment]
@ibhagwan works great, thank you.
