### ISSUE TITLE
icons not working

### ISSUE THREAD

**Issue by tmnvanderberg** [ibhagwan/fzf-lua#484]
### Info

- Operating System: Ubuntu 20.04
- Shell: bash
- Terminal: konsole, xterm
- `nvim --version`:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `fzf --version`:
`0.29.0 (dc975e8)`

- [x] The issue is reproducible with `minimal_init.lua`

### Description 
Squares instead of icons show up:

![image](https://user-images.githubusercontent.com/3397413/180462436-85f95be6-e302-4b38-8390-38a6cbd3b03c.png)

**Comment by ibhagwan** [comment]
You need to have a [patched nerd font](https://www.nerdfonts.com/) installed and configured to be used by your terminal to be able to see icons.

**Comment by tmnvanderberg** [comment]
Thanks for your reply and the great work on the plugin. :)

I have the 
```
	use { 'ibhagwan/fzf-lua',
	  -- optional for icon support
	  requires = { 'kyazdani42/nvim-web-devicons' }
	}
```
recommended in the documentation, should that not be sufficient?

**Comment by ibhagwan** [comment]
> recommended in the documentation, should that not be sufficient?

Unfortunately not, this just enables icons in the plugin but you need a proper font configured in order to display the glyphs, you’ll encounter the exact same behavior in any other icon-enabled plugin (nvim-tree, etc), without having the proper glyphs in the font the terminal can’t display them.

> Alternatively, is there a way to just disable the icons?

Yes, either uninstall `nvim- web-devicons` or you add `global_file_icons = false` to the setup call, alternatively you can disable them per call `:FzfLua files file_icons=false`.

**Comment by tmnvanderberg** [comment]
Thanks a lot for your explanation, that makes sense.
