### ISSUE TITLE
Can I merge oldfiles (cwd only) and git_files, with no duplication?

### ISSUE THREAD

**Issue by shiradofu** [ibhagwan/fzf-lua#485]
Thanks for developing a great plugin!
I love fzf, I love fzf-lua!

I'd like to use somthing like 'Project MRU'.
When I was using fzf.vim, I made custom functions below.

```vim
  function! s:project_mru_files() abort
    let old=map(
    \ filter(extend([expand('#:p')], copy(v:oldfiles)),
    \   'v:val =~ getcwd() . "/"'
    \  . ' && filereadable(v:val)'
    \  . ' && v:val !~# ".*/\.git/index$"'
    \  . ' && v:val !~# ".*/\.git/COMMIT_EDITMSG$"'
    \ ),
    \ 'fnamemodify(v:val, ":.")'
    \ )
    let fd = split(system('fd --type f --hidden -E ".git"'))
    return fzf#vim#_uniq(old + fd)
  endfunction

  function! g:ProjectMru() abort
    call fzf#run(fzf#wrap('gfiles', fzf#vim#with_preview({
      \ 'source': s:project_mru_files(),
      \ 'options': ['--prompt', 'MRU> ']
      \ })))
  endfunction

command! -nargs=0 ProjectMru call ProjectMru()
```

I tried to do the same thing with this plugin, read `providers/oldfiles.lua` and `providers/git.lua`, but I didn't get what is the best way to merge those (function-based `contents` and string-based `contents`) results.

Can I achieve this with fzf-lua?

Thank you!

**Comment by shiradofu** [comment]
Sorry for the late reply.
Thank you for advising me!

A bit slow startup, but synchronous version works well!

```lua
-- synchronous
local contents = function(cb)
  local git_files = vim.fn.systemlist(
    'fd --type f --absolute-path --color=never --hidden --follow --exclude .git'
  )

  coroutine.wrap(function()
    local co = coroutine.running()

    -- process oldfiles...

    for _, file in ipairs(git_files) do
      -- dup check
      if not files_memo[file] then
        x = make_entry.file(x, opts)
        if not x then
          return
        end
        cb(x, function(err)
          coroutine.resume(co)
          if err then
            cb(nil)
          end
        end)
        coroutine.yield()
      end
    end

    cb(nil)
  end)()
end

```

Now I'm working on async version and made 3 kinds of implementation.

1: using `jobstart`, adding files to fzf in the `on_event` callback, and doing nothing in coroutine
(I don't understand the relationships between `jobstart` and lua coroutine, but calling `jobstart` inside the coroutine happens nothing...)
```lua
local contents = function(cb)
  local function on_event(_, data, event)
    if event == 'stdout' then
      for _, file in ipairs(data) do
        if file ~= '' and not files_memo[file] then
          cb(make_entry.file(file, opts))
        end
      end
    elseif event == 'stderr' then
      vim.cmd 'echohl Error'
      vim.cmd('echomsg "' .. table.concat(data, '') .. '"')
      vim.cmd 'echohl None'
      cb(nil)
    elseif event == 'exit' then
      cb(nil)
    end
  end

  local fd_cmd = 'fd --type f --absolute-path  --color=never --hidden --follow --exclude .git'
  local jobid = vim.fn.jobstart(fd_cmd, {
    on_stderr = on_event,
    on_stdout = on_event,
    on_exit = on_event,
    cwd = cwd,
  })

  coroutine.wrap(function()
    -- process oldfiles...
  end)()
end
```

2: using `vim.loop.spawn`,  adding files to fzf inside the `vim.loop.read_start` callback without `coroutine.yield`
```lua
-- async 1
local contents = function(cb)
  local stdout = vim.loop.new_pipe(false)
  local stderr = vim.loop.new_pipe(false)

  _FD_HANDLE = vim.loop.spawn('fd', {
    args = { '--type', 'f', '--absolute-path', '--color=never', '--hidden', '--follow', '--exclude', '.git' },
    stdio = { nil, stdout, stderr },
  }, function()
    stdout:read_stop()
    stderr:read_stop()
    stdout:close()
    stderr:close()
    _FD_HANDLE:close()
    cb(nil)
  end)

  coroutine.wrap(function()
    local co = coroutine.running()

    -- process oldfiles...

    vim.loop.read_start(stdout, function(_, data)
      if data then
        local files = vim.split(data, '\n')
        for _, file in ipairs(files) do
          if file ~= '' and not files_memo[file] then
            cb(make_entry.file(file, opts))
          end
        end
      end
    end)
    vim.loop.read_start(stderr, function(err, _)
      print(vim.inspect(err))
      cb(nil)
    end)

  end)()
end
```

3: using `vim.loop.spawn`,  adding files to a table in `vim.loop.read_start` callback, looping the table and adding files to fzf with `coroutine.yield`
```lua
-- async 2
local contents = function(cb)
  local stdout = vim.loop.new_pipe(false)
  local stderr = vim.loop.new_pipe(false)
  local git_files_tbls = {}
  local fd_done = false

  _FD_HANDLE = vim.loop.spawn('fd', {
    args = {
      '--type',
      'f',
      '--absolute-path',
      unpack(opts.fd_additional_opts),
    },
    stdio = { nil, stdout, stderr },
  }, function()
    stdout:read_stop()
    stderr:read_stop()
    stdout:close()
    stderr:close()
    _FD_HANDLE:close()
    fd_done = true
  end)

  vim.loop.read_start(stdout, function(_, data)
    if data then
      local files = vim.split(data, '\n')
      git_files_tbls[#git_files_tbls + 1] = files
    end
  end)
  vim.loop.read_start(stderr, function(err, _)
    print(vim.inspect(err))
  end)

  coroutine.wrap(function()
    local co = coroutine.running()

    -- process oldfiles...

    local i = 1
    while not fd_done or git_files_tbls[i] do
      local files = git_files_tbls[i]
      if files then
        for _, file in ipairs(files) do
          if file ~= '' and not files_memo[file] then
            local entry = make_entry.file(entry, opts)
            if not entry then
              return
            end
            cb(entry, function(err)
              coroutine.resume(co)
              if err then
                cb(nil)
              end
            end)
            coroutine.yield()
          end
        end
        i = i + 1
      end
    end

    cb(nil)
  end)()
end
```

At first, I tried something like combination of 2 and 3, but calling `coroutine.yield()` inside `vim.loop.read_start` callback raise an error: `attempt to yield across C-call boundary`. I'm new to lua, coroutine, and libuv,  so I couldn't solve it by myself...

Which one is better, or is there better way over those?

**Comment by ibhagwan** [comment]
> 1: using jobstart, adding files to fzf in the on_event callback, and doing nothing in coroutine
(I don't understand the relationships between jobstart and lua coroutine, but calling jobstart inside the coroutine happens nothing...)

Lua coroutines are pretty simple once understood, what you need to do is wrap the call to `jobstart` and then call `coroutine.yield()` in order to wait for events:
```lua
local contents = function(cb)

  coroutine.wrap(function()
    local co = coroutine.running()

    local function on_event(_, data, event)
      if event == 'stdout' then
        for _, file in ipairs(data) do
          cb(require'fzf-lua'.make_entry.file(file, {}), function() coroutine.resume(co, 0) end)
        end
      elseif event == 'stderr' then
        vim.cmd 'echohl Error'
        vim.cmd('echomsg "' .. table.concat(data, '') .. '"')
        vim.cmd 'echohl None'
        coroutine.resume(co, 2)
      elseif event == 'exit' then
        coroutine.resume(co, 1)
      end
    end

    local fd_cmd = 'fd --type f --absolute-path  --color=never --hidden --follow --exclude .git'
    vim.fn.jobstart(fd_cmd, {
      on_stderr = on_event,
      on_stdout = on_event,
      on_exit = on_event,
      -- cwd = cwd,
    })

    repeat
      -- waiting for a call to 'resume'
      local ret = coroutine.yield()
      print("yielded", ret)
    until ret ~= 0

    -- process oldfiles

    -- only when done procesing we call EOF once
    cb(nil)
  end)()
end

require'fzf-lua'.fzf_exec(contents)
```

> 2: using vim.loop.spawn, adding files to fzf inside the vim.loop.read_start callback without coroutine.yield

That's ok since `read_start` is async anyways.

> 3: using vim.loop.spawn, adding files to a table in vim.loop.read_start callback, looping the table and adding files to fzf with coroutine.yield

That's ok too but I don't think you're getting much here, maybe you get a tiny bit more responsiveness as you release the UI in between line feeds but not needed IMO.

> At first, I tried something like combination of 2 and 3, but calling coroutine.yield() inside vim.loop.read_start callback raise an error: attempt to yield across C-call boundary. I'm new to lua, coroutine, and libuv, so I couldn't solve it by myself...

Unfortunately that's not solveable without many workaround hacks as once you use `libuv` you're out of the lua boundry and can't use coroutines directly in the callbacks (you can use different thread to feed to exit the libuv context but it's ugly and hacky :-)

> Which one is better, or is there better way over those?

I think the `jobstart` with the additional modifications I posted above does the job but since you're seem to be a great coder we can take it one step further :-)

All the above approaches have one fatal flaw and that is they're running within neovim's main thread, you can slice and dice it however you want it, it will never provide the same performance as running an external process and piping it into fzf, it took me a while to get to this solution but that is eventually what fzf-lua does (for most commands):

Running an external neovim process using `neovim --headless` (and supplying it with the different arguments), then using `libuv.spawn` to run the shell command **in the external process** and printing the output to stdout and then piped into fzf (technically using a temp `$FZF_DEFAULT_COMMAND`).

You can read a little bit about it in [the wiki: What does `multiprocess` do?](https://github.com/ibhagwan/fzf-lua/wiki#what-does-multiprocess-do).

If you managed to follow up to here and wish to explore this further (absolute best performance/responsivness), you can run `:FzfLua files debug=true` and then run `:messages` to see the external command, you can then copy the command, remove the `_G._fzf_lua_server` variable and you can actually run the command in the shell outside of neovim and receive an iconized output of `fd`, `rg`, etc. The code for it is inside [libuv.lua](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/libuv.lua) and is pretty simple so if you wanted you can customize it to your liking and add a post processing function that also prints `oldfiles` to stdout using `io.stdout:write`.

Good luck!

**Comment by shiradofu** [comment]
Thank you for really detailed explanation!!
I use `jobstart` version you suggested for a while, and it's very comforatble!

I'm interested in the way of multiprocessing, but I don't have much time now 😔
I looked at it a little, and I have one question:

In the `nvim` command for multiprocessing, `--clean` option is used, and nvim command is passed throught `--cmd` option.
I assume this contribute a lot to performance, but when it comes to using `oldfiles`, we have to use `-c` option for passing the command without `--clean` option to load shada file. This might hurt performance at initial loading.
On the other hand, in the main nvim process, `oldfiles` is already loaded, so there's no need to worry about it.

So I'm afraid that multiprocessing does not bring big performance improvement when dealing with `oldfiles`. However, I didn't try it nor time it, so I don't have much confidence.
Is my thinking correct?

**Comment by ibhagwan** [comment]
TBH, I’m not sure, it was just an idea and an explanation of the different strategies used by fzf-lua, I would assume having to load the shada file would have a bit of an overload but using an external command would still have the benefit of being independent of the main instance.

Having said that, for what you’re after the job approach is sufficient IMO.

**Comment by shiradofu** [comment]
Yes, for now I'm happy with `job` version, so I'm going to keep using it.

Thank you for taking your time!
