### ISSUE TITLE
bug: random detach from LSP with: [Fzf-lua] LSP: no client attached

### ISSUE THREAD

**Issue by arsham** [ibhagwan/fzf-lua#490]
### Info

- Operating System: `Arch Linux`
- Shell: `zsh`
- Terminal: `alacritty`
- `nvim --version`: `v0.8.0-dev-708-g57ce6c2b8f-dirty`
- `fzf --version`: `0.31 (devel)`

### Description 

Hi there!
Sometimes, and randomly, fzf-lua detaches from the LSP. This happens once or twice a week, but when it happens the only way to fix it is to restart vim. Even restarting LSP doesn't help.

For example the `lsp_definitions` command gives me `[Fzf-lua] LSP: no client attached`, but the `:lua vim.lsp.buf.definition()` works on the same buffer in the same session:

![fzf-lua](https://user-images.githubusercontent.com/428611/181228357-1c95fb6a-4827-4d7f-8857-c2c94a06a806.gif)

Please let me know if I can provide more information.

**Comment by ibhagwan** [comment]
I looked at the code and have a suspect, in order to support resumed actions properly the code only updates the origin buffer once the UI was closed properly, that part may have a bug, the next time this happens can you run:
```lua
:lua print("fzf win:", require'fzf-lua'.utils.fzf_winobj())
```
The check the output in `:messages`, the output should be `fzf win: nil` when an fzf-lua window isn't visible and  `fzf win: table: 0x405453d0` if you run this when an fzf-lua window is visible. I suspect something causes it to not get cleared properly in your case.

**Comment by ibhagwan** [comment]
@arsham, actually I think this was a different issue, the origin buffer wasn't being set before checking for attached clients, pretty confident https://github.com/ibhagwan/fzf-lua/commit/c3b23be371b75a1aa54adfc64a9bc268c29cb2c3 should solve it, let me know if otherwise?

**Comment by arsham** [comment]
Thanks for the quick response, and always!
