### ISSUE TITLE
FR: Consider adding "--scheme=path" to fzf_opts

### ISSUE THREAD

**Issue by Diablo-D3** [ibhagwan/fzf-lua#517]
fzf 0.33.0 recently added a `--scheme` argument, relevant quote from the changelog

>* Added `--scheme=[default|path|history]` option to choose scoring scheme
(Experimental)
>    * We updated the scoring algorithm in 0.32.0, however we have learned that
this new scheme (`default`) is not always giving the optimal result
>    * `path`: Additional bonus point is only given to the the characters after
path separator. You might want to choose this scheme if you have many
files with spaces in their paths.
>*    `history`: No additional bonus points are given so that we give more
weight to the chronological ordering. This is equivalent to the scoring
scheme before 0.32.0. This also sets `--tiebreak=index`.

`files = { fzf_opts = { ['--scheme'] = "path" } }` seems to subtly produce better results in complex projects, and maybe should be default for pickers that involve files. Also, possibly, `history` for pickers that involve chronological order.

**Comment by ibhagwan** [comment]
The scheme might be slightly better optimized but adding this to the defaults would require raising the fzf min requirement to `0.3.3`. Not everyone use a rolling release or keep all their binaries updated, this is a big change from requiring `0.2.7`.

Another option would be to add this conditionally when version >=`0.3.3` but then you’d also need to add another option to disable the default should someone prefer not to use it (esp since defined “experimental”).

Overall I don’t think it’s worth it at this point, we can revisit once this becomes more mainstream.

**Comment by ibhagwan** [comment]
Closing this issue for now as this might take a while to become relevant.
