### ISSUE TITLE
bug(gopls): method not supported: callHierarchy/incomingCalls

### ISSUE THREAD

**Issue by arsham** [ibhagwan/fzf-lua#525]
### Info

- Operating System: `Arch Linux`
- Shell: `zsh`
- Terminal: `alacritty`
- `nvim --version`:  `v0.8.0-dev-1132-g37a71d1f28-dirty`
- `fzf --version`: `0.33.0 (e03ac31)`

### Description 
When requesting incoming calls I get this error:
```
[Fzf-lua] Error executing 'callHierarchy/incomingCalls': RPC[Error] code_name = MethodNotFound, message = "method not supported: callHierarchy/incomingCalls"
```

I can confirm that the `vim.lsp.buf.incoming_calls()` populates the quickfix list.

Please let me know if you need more information.

**Comment by ibhagwan** [comment]
Just tested this with the latest nightly `NVIM v0.8.0-dev-1132-g37a71d1f2` and gopls `0.9.5` with a simple go test file and it worked.

- What version of `gopls` do you have installed?
- Do other LSP calls in the same project work (symbols/refs/defs/etc)?
- Do you have other LSP servers for go installed?
- Are you also using `null-ls`?

![image](https://user-images.githubusercontent.com/59988195/191547364-f70eeb26-d4e7-4ca8-8ee4-12b99aa67614.png)

**Comment by ibhagwan** [comment]
I recall we worked on this in the past in #399 and got `callHierarchy` to work, I wonder what changed.

**Comment by arsham** [comment]
Sorry for the delay. So your hit was correct. It wasn't null-ls though, it was `golangci_lint_ls`. I think it was hijacking the calls but didn't know what to do with it. Once I removed it everything was back to normal.

As always, thank you for your prompt response.

**Comment by ibhagwan** [comment]
> Sorry for the delay. So your hit was correct. It wasn't null-ls though, it was `golangci_lint_ls`. I think it was hijacking the calls but didn't know what to do with it. Once I removed it everything was back to normal.
> 
> As always, thank you for your prompt response.

We can still work towards solving this if you wish, the LSP code checks for number of available clients supporting the functionality and then waits for all of them to return (ref: https://github.com/ibhagwan/fzf-lua/commit/4ac0092a4cc7dcd6da1572f9fd76ee564940fb52), so I'm not sure how it even got to execute  `callHierarchy/incomingCalls` on `golangci_lint_ls`.

Let me know if you wanna drop this or try to solve it.

**Comment by ibhagwan** [comment]
I just installed `golangci_lint_ls` v0.0.7 in parallel with `gopls`, the issue only happens when using the async LSP interface (with `async_or_timeout=true` or `async=true`, it works as expected with `async=false`.

For some reason this only happens with `callHierarchy` incoming & outgoing calls, the request is being sent by neovim to `golangci_lint_ls` by the call to `vim.lsp.buf_request` even though `golangci` is not showing support for this method via `server_capabilities`, that creates a situation where the expected number of callbacks is 1 (gopls) but the actual returned calls are 2, one with the RPC error (which causes fzf to exit) and another with the incoming call result set.

I suspect this is a neovim bug with the async LSP API `vim.lsp.buf_request` as the request should never be sent to a server that doesn't support the method so I'm going to leave this for now.

In the meantime if you do decided to reinstall `golangci_lint_ls` use `:FzfLua lsp_incoming_calls async=false`.
