### ISSUE TITLE
Suggestion: Go to lsp references or implementation directly when there is only 1 result

### ISSUE THREAD

**Issue by TisnKu** [ibhagwan/fzf-lua#529]
When `lsp_implementations` and `lsp_references` have many results, using fzf to preview and select is great. When there is only one result, could it just jump to it directly?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/wiki#lsp-jump-to-location-for-single-result

**Comment by starpact** [comment]
@ibhagwan I think this should be relevant so I directly ask here.
Is it possble to exclude the current line for `lsp_references`?  imo generally what we want is "other" references, like the [include_current_line](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L1425) option of telescope.

**Comment by ibhagwan** [comment]
> @ibhagwan I think this should be relevant so I directly ask here. Is it possble to exclude the current line for `lsp_references`? imo generally what we want is "other" references, like the [include_current_line](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L1425) option of telescope.

Update to https://github.com/ibhagwan/fzf-lua/commit/5abf66f63bf08121dd4e917488b59ccb693eee12 and use the new `ignore_current_line` option:
```lua
:lua require'fzf-lua'.lsp_references({ ignore_current_line = true })
```
**Note:** given the maturity of this project I prefer to keep things as they are and add a new option rather than modify the exisiting behavior and have a new option "restore the old functionality", this is why I chose `ignore_current_line` as opposed to `include_current_line`.

**Comment by ibhagwan** [comment]
New wiki entry: https://github.com/ibhagwan/fzf-lua/wiki#lsp-ignore-current-line

**Comment by starpact** [comment]
> I prefer to keep things as they are and add a new option rather than modify the exisiting behavior and have a new option "restore the old functionality"

Make sense. Thank you so much!
