### ISSUE TITLE
Column number not shown by Fuzzy Search

### ISSUE THREAD

**Issue by davxy** [ibhagwan/fzf-lua#533]
Looks like `--column` is ignored by `rg` when using `grep_visual`.

Expected result:

```
> FILENAME:L:C:   <TEXT>
```

Actual result:

```
> FILENAME:L:   <TEXT>
```

The column number is instead shown when using `live_grep`

Note: if from `live_grep` I press `CTRL-G` to switch to Fuzzy Search (that as far as I understood is the same as `grep_visual` then column number is shown.

---

My configuration (neovim 0.8.0 nightly)

```
require('fzf-lua').setup({
    winopts = {
        preview = {
            layout = 'vertical',
        }
    },
    fzf_opts = {
        -- Case sensitive match
        -- ['+i'] = '',
        -- Enable exact-match (can be disabled by prefixing the word with ')
        ['--exact'] = '',
        -- Do not sort the result.
        -- Sort already performed by grep.
        ['--no-sort'] = '',
    },
    files = {
        -- Changes to the defaults.
        -- Added: --sort method
        rg_opts = "--color=never --files --hidden --follow -g '!.git' --sort path",
    },
    blines = {
        fzf_opts = {
            -- Sort results
            ['-s'] = '',
            -- Case sensitive
            ['+i'] = '',
        }
    },
    grep = {
        -- Changes to the defaults.
        -- Added: --sort method
        -- Removed: --smart-case
        rg_opts = "--column --line-number --no-heading --color=always --sort path",
    }
})
```

**Comment by davxy** [comment]
Maybe something to do with this?

https://github.com/ibhagwan/fzf-lua/blob/316879662ff9c33ae4b1072f8238e4bba2999e0a/lua/fzf-lua/providers/grep.lua#L87-L89

**Comment by ibhagwan** [comment]
You can always add `no_column_hide=true` under `grep` (or call `:FzfLua grep_project no_column_hide=true`) to work around this but I'm trying to figure out what went wrong in your case.

**Comment by davxy** [comment]
Mmm... something strange happens.

---

`FzfLua grep_visual no_column_hide=true` shows the column field. But it is set as 1 in all the lines.
 So this is the wrong value

---

I explain the steps to make it work with the correct value instead (may help finding the cause):
1. start `grep_visual` (`FzfLua grep_visual`) => no columns are showed
2. I've not typed anything  yet, so at the end of the `DEBUG` string I see a `' '`
3. If I type anything e.g. "HELLO", the `DEBUG` string disappears, so I can't see what is its value now...
4. At this point I go on and switch to regex search (pressing `ctrl-g`)
5. Now the `DEBUG` string appers again with the message "HELLO". Also the columns numbers are shown correctly.
6. At this point I switch back to "fuzzy search" mode (pressing `ctrl-g`)
7. Now the `DEBUG` string is visible in this mode as well and also the columns are shown correctly.

So the workaround here is: search in fuzzy mode + `ctrl-g` + `ctrl-g`

**Comment by ibhagwan** [comment]
What you’re describing is exactly how it should behave, first you need to understand the difference between live_grep and all the rest:
https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep

> `FzfLua grep_visual no_column_hide=true shows` the column field.
But it is set all the columns as 1. So this is the wrong value

That is also why it makes no sense to not display column numbers, your visual selection was empty (or bugged?) and running `rg` with no search term returns all lines of all files with columns set to `1`, try it in the shell and see for yourself.

The reason the debug line “disappears” is because in fuzzy match it doesn’t change anymore, it is run once and then Fzf does fuzzy matching on top, if you try to type `[DEBUG]` you’d notice the match highlighting and that the command doesn’t change, the command only changes per keystroke with live_grep (read the link I posted).

The only potential bug I see here is why your visual selection returns an empty string, in order to run ‘grep_visual_select` properly you need to create a visual mode mapping for it, select something in visual mode and then press your bind, otherwise you’re just running an empty string search, at which case the code is behaving as expected.

**Comment by ibhagwan** [comment]
This is how it should look like on a successful `grep_visual`, If you don’t see the “Grep string” header it means your visual selection turned out empty (in which case column numbers should be removed or they all appear as `1`)
> also notice the search term at the end of the `rg` command (debug)
![F68DBD16-22F8-4474-9CC4-A526A9482006](https://user-images.githubusercontent.com/59988195/193081924-19f329a6-0315-4eda-b299-19d4d9d34fa0.jpeg)

**Comment by davxy** [comment]
Nice. Let me read that `live_grep` chapter and then I'll eventually close this.
Ty
