### ISSUE TITLE
Preview page hotkeys not working after preview is modified mid query

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#557]
### Info

- Operating System:
- Shell: bash
- Terminal: iterm2
- `nvim --version`: 0.7.2
- `fzf --version`: 0.30.0

Relevant config (I didn't want to post the entire config as it's large but posted relevant piece below):

```lua
require('fzf-lua').setup({
  keymap = {
    -- These override the default tables completely
    -- no need to set to `false` to disable a bind
    -- delete or modify is sufficient
    builtin = {
      ["<C-]>"]        = "toggle-preview-cw",
    },
    fzf = {
     -- fzf '--bind=' options
      ["ctrl-f"]      = "half-page-down",
      ["ctrl-b"]      = "half-page-up",
      ["ctrl-a"]      = "beginning-of-line",
      ["ctrl-e"]      = "end-of-line",
      ["ctrl-d"]      = "preview-page-down",
      ["ctrl-u"]      = "preview-page-up",
    },
  },
})
```
</details>

### Description 

When I go into `files` and hit the `toggle-preview-cw` button, I am unable to use my hotkey for `preview-page-down` or `up`. Those keys get "unbind" so to speak. Is this intentional?

**Comment by ibhagwan** [comment]
> When I go into files and hit the toggle-preview-cw button, I am unable to use my hotkey for preview-page-down or up. Those keys get "unbind" so to speak. Is this intentional?

When using the keymap table the default options don't get merged with your table, that's intentional due to keymaps being a highly customizable and personal perference, this helps prevent the need to specify `[<bind>] =false` to disable a default bind.

FzfLua has 2 different previewer types, "builtin", which uses neovim's builtin window and "fzf" which uses fzf's native previewer functionality inside the terminal, that's why you have 2 different keybind sets, depending on the one you use you'll can have different binds (that's also why the different format in their config, one set is neovim style binds and the other is fzf binary style binds).

The fact you're able to use `toggle-preview-cw` tells me you're using one of the "builtin" previewers with a neovim window as this funcionality isn't implemented for native fzf previewers.

In the above config you posted there are no binds for preview page up|down for the builtin previewers, that's why it doesn't work and is unrelated to pressing the bind for`toggle-preview-cw`, to restore this functionality also specify the preview up|down binds under `keymap.builtin`:
```lua
require('fzf-lua').setup({
  keymap = {
    builtin = {
      ["<C-]>"]  = "toggle-preview-cw",
      ["<C-d>"]  = "preview-page-down",  -- Add this lines
      ["<C-u>"]  = "preview-page-up",    -- Add this line
    },
    fzf = {
        -- these stay the same as you use them for example with `git_` providers
    },
  },
})
```

**Comment by hqkhan** [comment]
Oh, I'm following now. Thank you so much. That makes a lot of sense.
