### ISSUE TITLE
ftdetect files don't execute on preview buffers

### ISSUE THREAD

**Issue by JosefLitos** [ibhagwan/fzf-lua#587]
use `:FzfLua files` and look for any files that have their filetype set by `ftdetect` files.

I use i3, but the `i3conf` extension is not loaded, because the preview buffers don't fire a `BufRead`, nor `BufNewFile` which all `ftdetect` files use for detecting the filetype. Would it be possible to fire that event manually, or would that cause unwanted behaviour?

Screenshot:
![image](https://user-images.githubusercontent.com/54900518/209122124-df10d2b6-5e21-49c2-b0c1-d9de6adeab61.png)

When Trying to set the filetype on `BufFilePost` it doesn't work either when the file is recognized by some vim internals (like `.gitconfig` for which I usually use custom toml highlight).

`BufFilePost` does set the filetype as wanted, but gets overriden when vim has its own intentions,
but otherwise, my `ft` stays:
![image](https://user-images.githubusercontent.com/54900518/209123265-6bde69cc-1bdc-4d26-80aa-799824bc3de8.png)

**Comment by ibhagwan** [comment]
Due to the reasons you mentioned, the preview buffer actually calls `filetype detect` :
https://github.com/ibhagwan/fzf-lua/blob/5abf66f63bf08121dd4e917488b59ccb693eee12/lua/fzf-lua/previewer/builtin.lua#L587-L595

I’m not familiar with `i3conf` extension, why do you believe the wrong file type is detected?
Perhaps there is  another way to make sure the file is properly detected with a `modeline`?

**Comment by JosefLitos** [comment]
Thank you, I solved it by adding the autocommands from all custom ftdetect plugins to `filetypedetect` group.
