### ISSUE TITLE
Prevent starting nvim-jdtls LSP  due to preview buffer

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#626]
Hi,

i'm not sure if this is related to fzf-lua or i missed some other LSP config, but how can i prevent neovim from starting f.e. JDTLS when i simply wanna grep something? I figured the preview window is just a regular buffer, so opening it will cause the according LSP to get started..... i don't want that. 

Any idea?

Regards

**Comment by ibhagwan** [comment]
You’re correct, the preview behaves like a regular buffer.

The solution would have to come from the LSP config side, perhaps a condition in the LSP `on_attach` function preventing load for floating windows?

Another workaround would be to use bat previewer.

**Comment by abenz1267** [comment]
thanks for the hint!

**Comment by ibhagwan** [comment]
@abenz1267, did you manage to find a solution for this?

@asmodeus812 just mentioned something similar in connection with nvim-jdtls.

**Comment by abenz1267** [comment]
Hey, I've simply switched to bat for the previewer, as you mentioned. More a workaround than a solution. Haha.

**Comment by asmodeus812** [comment]
@ibhagwan is there a way to detect if we are in fzf lua default previewer or something like that, that could let us by pass on attach. What is more strange is that if you preview other types of buffers like c or rust files for which i also have lsp clients, they don't get attached until i open the buffer (i.e accept/select) it from the picker. So i am wondering why is on_attach not getting triggered for those. (that should work like that)

**Comment by ibhagwan** [comment]
> @ibhagwan is there a way to detect if we are in fzf lua default previewer or something like that, that could let us by pass on attach.

You can get the buffer name with `vim.api.nvim_buf_get_name` and then check if the first part of the name contains the buffer number (i.e. `123/path/to/file`), alternatively, I can add a buffer local var.

> What is more strange is that if you preview other types of buffers like c or rust files for which i also have lsp clients, they don't get attached until i open the buffer (i.e accept/select) it from the picker. So i am wondering why is on_attach not getting triggered for those. (that should work like that)

Not sure I follow, can you pin point exactly when do you have the issue of buffers being LSP attached and when not?

**Comment by asmodeus812** [comment]
@ibhagwan the issue is only with the way nvim-jdtls works, it expects auto command for java file types to be configured, so it does on attach its clunky indeed, the rest work just fine, the ones that are configured normally through nvim-lspconfig. The on attach callback is triggered for those only when you actually explore the buffer, not right away from the previewer. 
I was just curious as to why, if we use native buffer preview, the regular on attach is not triggered, there must be something else going on. I assume the built in previewer does not jsut :e <buffer> to visualise it ? It must be doing some magic.

**Comment by ibhagwan** [comment]
> The on attach callback is triggered for those only when you actually explore the buffer, not right away from the previewer.
> I was just curious as to why, if we use native buffer preview, the regular on attach is not triggered, there must be something else going on. I assume the built in previewer does not jsut :e to visualise it ? It must be doing some magic.

The neovim preview buffer (i.e. "builtin") is a normal buffer with the same filetype (so you can get proper syntax highlighting), it also calls `filetype detect` in order to fill the gap for previewing files that it cannot highlight just by extension (e.g. git config, vimdoc that have a `txt` extension, etc), and in that case I would assume the nvim-jdtls attach happens and I'm really not sure what I can do from fzf-lua's end to avoid that.

**Comment by asmodeus812** [comment]
@ibhagwan I am not saying anything should be done by fzf lua, i am just trying to understand a bit more on how this works internally since it is interesting, i assume the preview is happening in a headless instance.
> I was just curious as to why, if we use native buffer preview, the regular on attach is not triggered, there must be something else going on. I assume the built in previewer does not jsut :e to visualise it ? It must be doing some magic. <

On another note, what is the best way to detect the current buffer is the preview buffer of fzf lua so i can add a check to that in the auto command ? And is there a way to tell apart the main fzf terminal (showing the list of items to filter) buffer itself too, to skip a few keybinds for that buffer when i am doing terminal mappings.

**Comment by ibhagwan** [comment]
> On another note, what is the best way to detect the current buffer is the preview buffer of fzf lua so i can add a check to that in the auto command ? And is there a way to tell apart the main fzf terminal (showing the list of items to filter) buffer itself too, to skip a few keybinds for that buffer when i am doing terminal mappings.

https://github.com/ibhagwan/fzf-lua/issues/626#issuecomment-1426787403

> You can get the buffer name with `vim.api.nvim_buf_get_name` and then check if the first part of the name contains the buffer number (i.e. `123/path/to/file`), alternatively, I can add a buffer local var.

You can still test this by checking if the first file part matches the buffer number, if you manage to fix this issue with the autocmd I’ll add a buffer local var so it’s easier.

**Comment by asmodeus812** [comment]
> And is there a way to tell apart the main fzf terminal (showing the list of items to filter) buffer itself too, to skip a few keybinds for that buffer when i am doing terminal mappings.

Great thanks, will have a look and update you, the same applies to this too ?

**Comment by ibhagwan** [comment]
> > And is there a way to tell apart the main fzf terminal (showing the list of items to filter) buffer itself too, to skip a few keybinds for that buffer when i am doing terminal mappings.
> 
> Great thanks, will have a look and update you, the same applies to this too ?

The detect the main fzf terminal is possible in two ways (use one or both):
1. Test for `wininfo.terminal` property:
```lua
-- Use the correct `winnr` if `nvim_get_current_win` doesn't apply here
local wininfo = vim.fn.getwininfo(vim.api.nvim_get_current_win())[1]
if wininfo.terminal == 1 then
  ...
end
```
2. Test for `filetype=fzf` using `vim.bo.ft == 'fzf'` or with buffer number `vim.bo[bufnr].ft == 'fzf'`

**Comment by asmodeus812** [comment]
For the preview buffer since that is another nvin process maybe we can have something even better than a buffer local var. Maybe when the process is spawning we can set some sort of env vars or startup args to be picked up by that process. Not sure, but from what i saw the same / current dotfiles get loaded in the headless, ?

**Comment by ibhagwan** [comment]
> For the preview buffer since that is another nvin process maybe we can have something even better than a buffer local var. Maybe when the process is spawning we can set some sort of env vars or startup args to be picked up by that process. Not sure, but from what i saw the same / current dotfiles get loaded in the headless, ?

Not sure what you mean, the previewer is not an external process, new process is only used to feed input into fzf with external commands `rg`, `fd`, `git`. Also, the LSP calls are not an external process.

**Comment by asmodeus812** [comment]
What i meant is that you spawn a new neovim headless proecess for multiprocessing the entries to fzf when you string.format them  for example, i assumed you do something like that for the fzf preview otherwise. Therefore i assumed the builtin previewer is a standalone neovim process, like other previwers, bu if that is not the case like it is for multiprocess then bufvar seeks okay, thje only concern i havr is that  it might be a good idea to allow such fzflua state/flag variable names  (i am sure more will popup) to br defined by the user or default to somthing sane. Otherwise its hard to track teir usage down in big dotfiles. I am still not sure if a callback before previwer loads ( letting the user set some custom state etc) or smth like that might not be a better idea, i just want to avoid heavy config coupling like that for example between lsp - fzf in this case

**Comment by ibhagwan** [comment]
> What i meant is that i saw fzflua spawns a new neovim headless proecess for multiprocessing the entries to fzf when you string.format them for example, i assumed we do something like that for the fzf preview otherwise. 

The preview is fed with lines directly, no external process is used.

> I am still not sure if a callback before previwer loads ( letting the user set some custom state etc) or smth like that might not be a better idea, i just want to avoid heavy config coupling like that for example between lsp - fzf in this case

I couldn’t find a way to “mark”  a file to avoid LSP start , if there was such a way that would obviously be better.

Given this issue is isolated to nvim-jdtls (correct me if I’m wrong), the solution will come from exploring nvim-jdtls code, understanding what it does differently, when it starts the LSP and finding a way to avoid that.

Let me know what you find out and if there’s away to prevent the LSP from loading without user intervention or custom patches I’ll add it to fzf-lua.

**Comment by asmodeus812** [comment]
Issue is isolated indeed, i was mostly talking about getting a more general solution to a problem which might happen elsewhere, for example i have default keymaps in regular vim terminals which were overshadowing the native fzf ones. Below is what i did, maybe something similar can be integrated with fzf lua's api. The filetype event will trigger after we set fzf ft (tried on_create but couldn't make it work with keymap.del, not sure at what stage on_create is called maybe too early), and the close event will make sure to cleanup the state. 

```lua
    local id = vim.api.nvim_create_augroup("fzf", { clear = true })
    vim.api.nvim_create_autocmd({ "FileType" }, {
        group = id,
        pattern = "fzf",
        callback = function()
            pcall(vim.keymap.del, "t", "<C-c>")
            pcall(vim.keymap.del, "t", "<C-a>")
            pcall(vim.keymap.del, "t", "<C-j>")
            pcall(vim.keymap.del, "t", "<C-k>")
            pcall(vim.keymap.del, "t", "<C-h>")
            pcall(vim.keymap.del, "t", "<C-l>")

            if vim.bo.ft == "fzf" then
                vim.g.__lsp_disabled = true
            end
        end,
        desc = "Setting up general state on fzf-open",
    })

    vim.api.nvim_create_autocmd({ "TermClose" }, {
        group = id,
        pattern = "term://*",
        callback = function()
            if vim.bo.ft == "fzf" then
                vim.g.__lsp_disabled = false
            end
        end,
        desc = "Cleaning up state on fzf-close",
    })

```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/6be3ba4620ed44b29abc1562ecf67e4fdfb48d20 - Can you check if this commit solves this issue as well?

Thanks to #643 (and Telescope code) I learned you can disable autocmds when attaching buffers to windows.

**Comment by asmodeus812** [comment]
Hi, thanks for the quick turnaround, i was also considering maybe disabling autocmds for preview window, i tried that but seems like it is not working as expected, the FileType cmd i have registered for jdtls is still getting called.

**Comment by ibhagwan** [comment]
> the FileType cmd i have registered for jdtls is still getting called.

`filetype=fzf` is the main terminal window, the previewer window has the same file type as the previewed file.

> Maybe the ft for the preview buffer is set before the autocmds are disabled with eventignore, just a thought.

I disabled autocmds no both `nvim_open_win` as well as `nvim_win_set_buf` - how is it possible it’s still getting called, maybe it’s something else starting the LSP and not the previewer autocmd?

**Comment by ibhagwan** [comment]
Can you pin point a specific autocmd in nvim-jdtls that starts the LSP?

If you can link the exact line(s) of code from nvim-jdtls I’m sure I will be able to avoid it but as it stands now it’s shooting in the dark.

**Comment by ibhagwan** [comment]
I just looked how nvim-jdtls does the setup using `after/ftplugin/java.lua`, with the latest commit I was able to add one line at the top that solves this issue using the win local var:
```lua
if vim.w.fzf_lua_preview then return end
if not pcall(require, "jdtls") then
  return
end
…
```
I’ll do some more research tomorrow how to avoid loading the ftplugin since autocmd ignore doesn’t work here,  in the meantime can you test the above and see if this solves your issue?

**Comment by asmodeus812** [comment]
I am not really following the default setup guide for jdtls using ftplugin, rather as i mentioned i have an autocmd which essentially does tthe same. The way i have set it up on my side for jdtls is like that. So what happens is when i open nvim in home dir and immediately opoen recent files (oldfiles) and i start selecting/picking from the list of files the moment i go over a java file i can see the jdtls startup logs in the messages below. Now if i do LspInfo i can see that Jdtls is attached, but the bufnr array is empty actually which is weird, see picture below. And the workind dir for the jdtls is the user home folder which is the one where i opened nvim from. If i uncomment the flag state below __lsp_disabled that i made with the example from my prev posts, it is picked up correctly and attach is not reached. 

```lua
        local id = vim.api.nvim_create_augroup("jdtls", { clear = true })
        vim.api.nvim_create_autocmd({ "FileType" }, {
            group = id,
            pattern = "java",
            callback = function()
               -- commented out to test the autocmd disable !
               -- if vim.g.__lsp_disabled == true then return end

                local root_loc = utils.get_workdir('jdtls')

                if not root_loc or #root_loc == 0 then
                    -- default to something sane
                    opts = vim.fn.deepcopy(opts)
                    opts.cmd = lsp_command_create()
                elseif not PROJECT_CONFIGS[root_loc] then
                    -- cache the config for this workdir
                    PROJECT_CONFIGS[root_loc] = vim.tbl_deep_extend("force", opts, {
                        cmd = lsp_command_create(root_loc),
                        root_dir = root_loc,
                        format = {
                            settings = {
                                profile = "default", -- defined in format stylesheet
                                url = string.format("%s/%s", root_loc, CODE_FORMATTER)
                            }
                        }
                    })
                    -- read from the cached configs
                    opts = PROJECT_CONFIGS[root_loc]
                else
                    -- read from the cached configs
                    opts = PROJECT_CONFIGS[root_loc]
                end
                 -- This line actually starts the jdtls server or attaches to existing jdtls instance
                require("jdtls").start_or_attach(opts)
            end,
            desc = "Start or attach custom java lang server",
        })

```

![image](https://user-images.githubusercontent.com/15955811/218671067-ac75c463-3ca9-43a8-b6ab-b6bace14e7e3.png)

**Comment by nyngwang** [comment]
FYI: I think I encountered this issue when I was fine-tuning my setup for `nvim-treesitter/nvim-treesitter`. Since I have the following config:

```lua
require('nvim-treesitter.configs').setup {
  auto_install = true,
  -- omitted.
}
```

And I noticed that some messages of "Treesitter parser for XXX has been installed" were shown when I was scrolling the list of `:FzfLua files`.

**Comment by ibhagwan** [comment]
> I am not really following the default setup guide for jdtls that is using ftplugin, rather as i mentioned i have an autocmd which essentially doest the same. The way i have set it up on my side for jdtls is like that.
So to test the recent commit you added for the autocmd disable what i do is when i open nvim in home dir and immediately open recent files (oldfiles) and i start selecting/picking from the list of files the moment i go over a java file i can see the jdtls startup logs in the messages below. Now if i do LspInfo i can see that Jdtls is attached, but the bufnr array is empty actually which is weird, see picture below. And the working dir for the jdtls is the user home folder, which is the one where i opened nvim from. If i uncomment the flag state below __lsp_disabled that i made with the example from my prev posts, it is picked up correctly and attach is not reached.

What if instead of:
```lua
-- commented out to test the autocmd disable !
if vim.g.__lsp_disabled == true then return end
```

You do:
```lua
if vim.w.fzf_lua_preview then return end
```
Have you tried it?

> And I noticed that some messages of "Treesitter parser for XXX has been installed" were shown when I was scrolling the list of :FzfLua files. (Well, since these are just treesitter stuffs and it will only happen once per programming language so I didn't report it. On the other hand, finding a solution for heavy-weight LSPs does sound like a good optimization.)

@nyngwang - yes, this is the same issue, what’s causing it is running `filetype detect` (or `set ft=…`) on the preview buffer to enable syntax highlighting.

I looked into Telescope and I saw it doesn’t do that,  instead it enables treesitter syntax highlighting manually, I will look into doing the same which will solve this issue, Telescope detects the filetype using plenary.nvim, I’d like to avoid adding dependencies to this plug-in just for that, I will look into it.

**Comment by ibhagwan** [comment]
Happy to announce this was completed in https://github.com/ibhagwan/fzf-lua/commit/a0734e023053b2a334abd0fc1ebbbc724d6a7e04 - turns out I could avoid the `plenary.nvim` dependency by using the new `vim.filetype.match` introduced with neovim 0.7.

No buffer auto commands or `ftplugin` handlers should be executed now (previewer highlights now work exacltly as telescope) - let me know if this solves your issues?

**Comment by nyngwang** [comment]
I just tested with 1df9249, which is two commits later than a0734e0, and it works well :) Thank you for taking care of this little but important part. (I also realized that I should use your style of writing well-documented commit messages on important(?) commit. I was always thinking about who(including myself) will understand my basically unreadable commit messages without context.)

**Comment by ibhagwan** [comment]
> I just tested (on the TS-parser part, but this should suffice for closing the entire issue) with HEAD https://github.com/ibhagwan/fzf-lua/commit/1df92492201ff9bf081a276c3c773a36cfee66a0, which is two commits later than https://github.com/ibhagwan/fzf-lua/commit/a0734e023053b2a334abd0fc1ebbbc724d6a7e04, and it works well :) Thank you for taking care of this little but important part.

Ty @nyngwang! I'm confident this sorts this issue out but we'll wait for confirmation regarding nvim-jdtls from either @abenz1267 or @asmodeus812 before closing :-)

**Comment by abenz1267** [comment]
Just tested: is fixed!

**Comment by asmodeus812** [comment]
@ibhagwan thanks for the quick and hard work, i will try to test as soon as i can, will update you today on that, but it looks great.

**Comment by ibhagwan** [comment]
> @ibhagwan thanks for the quick and hard work, i will try to test as soon as i can, will update you today on that, but it looks great.

Ty everyone!

np @asmodeus812, I suspect it will work for you as well since @abenz1267 was also using jdtls, let me know I’d otherwise.

**Comment by asmodeus812** [comment]
@ibhagwan yep, all is good now, had some time to test it out.

**Comment by ibhagwan** [comment]
> @ibhagwan yep, all is good now, had some time to test it out.

Ty for the update @asmodeus812!
