### ISSUE TITLE
Question: Technical question regarding the inner workings of multiprocess

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#655]
Hi, @ibhagwan this is purely a technical question not related to an issue or a feature request. I am trying to leverage the same technique you are using with spawning additional nvim processes to offload processing. What i am trying to do is a find/replace with ripgrep.

Say we open the grep picker, grep for a string, mark a few lines with fzf, confirm, then filter on the unique files among the selection (and collect the relevant line numbers for which to do the replacement for each file from the selection) from the selection and i want to pass those line numbers and offload a rg --replace to a separate neovim instance for each unique file. In that neovim instance parsing the ripgrep --replace's line numbers do some more work on the output data, but the final goal is to eventually run substitute on the file to replace only on the  target lines. 

The api seems mostly open so i can either use the one fzf provides or whip something up, but i am kinof confused as to how it is all glued together, never really had to deal with rpc and server nvim instance. Any help will be greatly appreciated ! Thanks !

Very interested in this part, as to how the require here works when we are spawning --clean instance ? (That is excerpt from the wrap_spawn_stdio)
<img width="707" alt="image" src="https://user-images.githubusercontent.com/15955811/219677081-7da9d97f-c8e2-4c76-b4a1-6ac7e287a456.png">

**Comment by ibhagwan** [comment]
> The api seems mostly open so i can either use the one fzf provides or whip something up, but i am kinof confused as to how it is all glued together, never really had to deal with rpc and server nvim instance. Any help will be greatly appreciated ! Thanks !

You’re correct, it’s pretty open and should work with any command, you can test it easily by running `:FzfLua files debug=true`, then look at `:messages` and copy the headless command and you can modify what it runs inside the `[[ command ]] `, **make sure to remove the `_G.fzf_lua_server` variable**  as it’s used to query config options from the main thread which will get stuck used without a neovim instance to connect to, without it, config defaults are used.



> Very interested in this part, as to how the require here works when we are spawning --clean instance ? (That is excerpt from the wrap_spawn_stdio)


The `require` works by hacking require and converting the string to something that would be found in the runtime, see this:
https://github.com/ibhagwan/fzf-lua/blob/e0dba1ab12c987a173254c39b8b7ba026cf5d164/lua/fzf-lua/libuv.lua#L19-L22

If your file (the one you wish to load and contains  the processing code)  isn’t in any path that would work using a `require` you can use `dofile(<fullpath>)` instead, as long as you understand the difference between require and dofile and your file can be loaded independently, it can work :)

**Comment by asmodeus812** [comment]
> **make sure to remove the `_G.fzf_lua_server` variable** as it’s used to query

That is interesting, what exactly do you mean by that ? 

> The require works by hacking require and converting the string to something that would be found in the runtime, see this:

To avoid that hack, wouldn't it be possible to do double head on fnamemodify to go one level further up the tree ? 
```lua
  local tmpdir = vim.fn.fnamemodify(vim.fn.tempname(), ":h") -- this would load the fzf-lua module as root so i guess if you do another :h you won't need to do the gsub in require ?
```

And regarding communicating to stdout to the main instance, does that happen in the pipes ?

**Comment by ibhagwan** [comment]
> > **make sure to remove the `_G.fzf_lua_server` variable** as it’s used to query
> 
> That is interesting, what exactly do you mean by that ?

You have to remove it from the command line arguments, sometime I wish to run the libuv wrapper command from the shell even when neovim isn't running at all, at this point you want this code part to not execute:


For example, this is what I use to test the `--headless` command:
> The below  wraps `rg --files` and iconifies the output (like fzf-lua)
```sh
#!/bin/sh
nvim -n --headless --clean --cmd 'lua loadfile([[/home/bhagwan/Sources/nvim/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio\
  ({debug=false,cmd=[[rg --files]],git_icons=false,file_icons=true,color_icons=true,cwd=nil,stderr_to_stdout=false},\
  [[_G._devicons_path='\''/home/bhagwan/.local/share/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua'\'';\
  _G._devicons_setup='\''~/.config/nvim/lua/plugins/devicons.lua'\'';
  return require("make_entry").file]],[[return require("make_entry").preprocess]])'
```

Notice that towards the end of the command I send global variables to the headless instance, for exmaple `_G._devicons_setup` which is used for custom devicons overrides (see #657 and https://github.com/ibhagwan/fzf-lua/wiki#how-can-i-use-custom-devicons-with-multiprocess).

Because I use this little script outside of fzf-lua I make sure it doesn't specify the global `_G.fzf_lua_server`, if you look at other commands generated when using `debug=true` you will see it there, it's used to query configuration parameters from the main instance via a pipe, which you probaby want to avoid in your use case (unless you need to query the config from fzf-lua):
https://github.com/ibhagwan/fzf-lua/blob/a0cb70ff4a154b34defc14ce7fbe58eb9b188373/lua/fzf-lua/make_entry.lua#L34-L60
 
As for:

> > The require works by hacking require and converting the string to something that would be found in the runtime, see this:
> 
> To avoid that hack, wouldn't it be possible to do double head on fnamemodify to go one level further up the tree ?
> 

It's possible, I don't recal if I tested it or not, once it was working for all users on different systems there was no point in further changes, it is such a sensitive part of the plugin that a small change could break all functionality, for example, fzf-lua doesn't work anymore with `VimR` due to it's internal neovim build segfaulting on `--headless --cmd`, see #651.

> And regarding communicating to the main instance, does that happen in the pipes ?
Yes, using `vim.fn.sockconnect`, only required for querying custom config values specified by the user, otherwise the wrapper is totally independent.

**Comment by ibhagwan** [comment]
Closing, feel feee to reopen if you need more help.
