### ISSUE TITLE
feat: icon colors respect the highlight groups of nvm-web-devicons

### ISSUE THREAD

**Issue by mikesmithgh** [ibhagwan/fzf-lua#657]
### Info

- Operating System: OSX
- Shell: Bash
- Terminal: Kitty
- `nvim --version`: NVIM v0.9.0-dev-958+g264fb6945-dirty
- `fzf --version`: 0.38.0 (brew)

- [x] The issue is reproducible with `mini.sh`
### Steps to reproduce
- `:hi DevIconTxt guifg=red`
- `:FzfLua files`
- Expected: txt file icon to be red
- Actual: txt file is green

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description

I have some modifications to the highlight groups of https://github.com/nvim-tree/nvim-web-devicons. I'd like the color of the icons to be displayed in FzfLua, however, it appears FzfLua is reading directly from nvim-web-devicons. I see FzfLua is pulling the hex color and converting to ANSI escape sequences. I tried to modify the source to pull highlight groups but did not have any luck, I think it may be due to remote calls which I am not familiar with.

This feature request is to have the icon colors respect the highlight groups of nvm-web-devicons.

Please let me know if you need any additional information.

Thanks!

**Comment by ibhagwan** [comment]
You're correct, for performance reasons, fzf-lua spawns the command processing in an external neovim process (AKA `multiprocess`) which manually loads `nvim-web-devicons` in which all customizations are lost.

It is possible however to override it, see
https://github.com/ibhagwan/fzf-lua/wiki#how-can-i-use-custom-devicons-with-multiprocess

For example in my own config I have:
> https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/fzf-lua/setup.lua#L159-L165
```lua
M.setup = function()
  -- custom devicons setup file to be loaded when `multiprocess = true`
  fzf_lua.config._devicons_setup = "~/.config/nvim/lua/plugins/devicons.lua"
  ...
```
And a separate devicons customizations file:
> https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/devicons.lua
```lua
function M.config()
  require("nvim-web-devicons").setup({
    override = {
      sol = {
        icon = "♦",
        color = "#a074c4",
        name = "Sol"
      },
      sh = {
        icon = "",
        color = "#89e051",
        cterm_color = "113",
        name = "Sh",
      }
    };
  })
end
```
> 
Due to the limiations of loading the file externally directly, make sure you don't have any additional `require` statements that would fail when called outside of scope.

**Comment by ibhagwan** [comment]
Closing, if you’re still struggling to set this up feel free to reopen.

**Comment by ibhagwan** [comment]
FYI, https://github.com/ibhagwan/fzf-lua/commit/604eadfcf69b90cf9e508767ad217107520ce4d4 - this commit makes the additional setup step unnecesary, overrides should works seamlessly now.

**Comment by mikesmithgh** [comment]
Great thank you! I'll let you know if I have any issues.
