### ISSUE TITLE
Cwd header not updating on resume

### ISSUE THREAD

**Issue by WolfeCub** [ibhagwan/fzf-lua#660]
### Info

- Operating System: MacOS Ventura 13.2.1
- Shell: Zsh
- Terminal: Kity
- `nvim --version`: 0.8.3
- `fzf --version`: 0.37.0 (brew)

- [X] The issue is reproducible with `mini.sh`

### Description 

You can reproduce the issue with the following call:
```lua
require('fzf-lua').files(function()
    return {
        show_cwd_header = true,
        actions = {
            ["ctrl-w"] = {
                function(_selected)
                    vim.api.nvim_set_current_dir('..')
                end,
                require('fzf-lua.actions').resume,
            },
        },
    }
end)
```
Pressing `<C-w>` changes the directory and the files refresh accordingly but the cwd header (nor the cwd prompt) updates to reflect the change.

**Comment by ibhagwan** [comment]
That's probably because `opts.cwd` is cached in within the resume data, I'll have to think of a clean way to refresh it, in the meantime why don't you use this instead?

> You don't need to call `resume`, just call files directly again, as long as the action is wrapped in a table (`{}`)  the window will be reused and you won't have a "flash" of recreating the window

```lua
_G.my_files = function()
  require('fzf-lua').files({
    show_cwd_header = true,
    actions = {
      ["ctrl-w"] = {
        function()
          vim.api.nvim_set_current_dir('..')
          _G.my_files()
        end
      },
    },
  })
end
```

**Comment by ibhagwan** [comment]
I looked into it, it's happening because the call to `set_header` doesn't happen with the resume, setting the header is part of "preparing the opts" part, I could fix it but it would be a bit hacky and doesn't necessarily make sense.

What you're trying to achieve here is not a resume, you're not really resuming your last files operation, you're techincally opening `files` with a new folder, I'd rather we work to achieve the desired result for you "the right way" other than hacking `resume` for this specific use-case.
