### ISSUE TITLE
feature: add `autocmd` picker?

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#662]
Do you think it makes sense to add a picker for `autocmd` or do you think it is too much of a narrow use case? I see that, especially in the [Misc section](https://github.com/ibhagwan/fzf-lua#misc), `fzf-lua` provides more or less all vim internals, thus I was wondering why not consider the list of autocommands as well (I find myself very often browsing them, especially these days that plugins are popping up like mushrooms there are dozens of autocommands that trigger on each event).

**Comment by ibhagwan** [comment]
Should be pretty easy with `vim.api.nvim_get_autocmds`, just have to decided on how to display it in a way that makese sense that would also match something you're looking for (filetypes, patters, etc).

**Comment by gennaro-tedesco** [comment]
Looking at the output of `vim.api.nvim_get_autocmds` I see it contains, among other things, group name, event and pattern: it should be good enough! Though looking at the output of vim `:autocmd` it also displays the location the autocommand was defined (strangely enough it isn't included in the corresponding neovim api).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8d17cb970ede3832a5bbbae06466308cf6aa917f.

I was able to acquire the calling function location using `debug.getinfo`, much better than hack parsing the output of `:autocmd`.

The new provider includesa previewer which will display the lua callback if available or the vimL command otherwise.

Lua callback (note the lua functions in red):
![image](https://user-images.githubusercontent.com/59988195/220214464-e68be575-7ca2-4e66-a120-8930d047a192.png)

VimL command:
![image](https://user-images.githubusercontent.com/59988195/220214421-a32d68db-ecad-4e8a-8f62-23f4eb5ace77.png)

**Comment by nyngwang** [comment]
@ibhagwan Not sure whether this can be added or not: either the content of `vim.v.event` being set or `args` passed to the callback. Will be extremely helpful in debugging!

**Comment by ibhagwan** [comment]
@nyngwang, this is not possible, this provider is merely the reflection of the output of `vim.api.nvim_get_autocmds({})`, the args/events only appear when you call the functions.

**Comment by gennaro-tedesco** [comment]
Wooow this is fantastic work, it looks amazing. And the preview that points to the definition of the callbacks!

This is useful a lot to debug one's configuration and for plugin development! 🚀 ❤️
