### ISSUE TITLE
lsp_definitions not working on jdtls

### ISSUE THREAD

**Issue by y1rn** [ibhagwan/fzf-lua#771]
### Info

- Operating System: Archlinux (WSL2)
- Shell: zsh
- Terminal: windows terminal
- `nvim --version`: NVIM v0.10.0-dev-411+g9dd48f783
- `fzf --version`: 0.40

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
`require"fzf-lua".lsp_definitions({})` show message: `[Fzf-lua] LSP: server does not support definitionProvider`
`vim.lsp.buf.definition()` works fine

**Comment by ibhagwan** [comment]
@y1rn, I’m not sure how to fix this, there seem to be some larger issues with `jdtls` and unfortunately I can’t see to set it up properly on my machine and it seems I’m not the only one:
https://github.com/mfussenegger/nvim-jdtls/issues/459#issuecomment-1510452408

Also related are #728 and https://github.com/mfussenegger/nvim-jdtls/issues/478.

The call to `textDocument/definition` is equivalent to any other “location” call which makes this issue a bit more confusing:
https://github.com/ibhagwan/fzf-lua/blob/bc5110738d44c16655cf1b23534343aaade855a2/lua/fzf-lua/providers/lsp.lua#L554-L557

I’d welcome a PR if you find what the issue is, otherwise it will have to wait for me to be able to setup jdtls.

**Comment by y1rn** [comment]
neovim v0.10.0 looks support `textDocument.definition.dynamicRegistration` but [jdtls](https://github.com/eclipse/eclipse.jdt.ls/blob/3ba04d16d4f19c5020ba253f1040357f031f9005/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#LL163C1-L163C1) dosen't.
I try to add `config.capabilities.textDocument.definition.dynamicRegistration = nil` in [nvim-jdtls,](https://github.com/mfussenegger/nvim-jdtls/blob/365811ecf97a08d0e2055fba210d65017344fd15/lua/jdtls/setup.lua#L278) and it works.

**Comment by y1rn** [comment]
> neovim v0.10.0 looks support `textDocument.definition.dynamicRegistration` but [jdtls](https://github.com/eclipse/eclipse.jdt.ls/blob/3ba04d16d4f19c5020ba253f1040357f031f9005/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#LL163C1-L163C1) dosen't. I try to add `config.capabilities.textDocument.definition.dynamicRegistration = nil` in [nvim-jdtls,](https://github.com/mfussenegger/nvim-jdtls/blob/365811ecf97a08d0e2055fba210d65017344fd15/lua/jdtls/setup.lua#L278) and it works.

This is not and fzf-lua issue.

**Comment by ibhagwan** [comment]
Ty for the update @y1rn !
