### ISSUE TITLE
Could we have a default highlight group for the titles of `:FzfLua tabs`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#780]
### Description 

Specifically, I use this keymap:

```lua
vim.keymap.set('n', '<C-b>', function () require('fzf-lua').tabs {
  tab_title = {
    function (tab_idx, is_current)
      local tabnr = vim.api.nvim_list_tabpages()[tab_idx]
      return string.format('Tab #%s: %s', tabnr, require('tabby.feature.tab_name').get_raw(tabnr))
    end,
    'FzfLuaTabTitle',
  },
} end)
```

But then I need to create the highlight group `FzfLuaTabTitle`.

Another related problem of this is that: I cannot just define `hi FzfLuaTabTitle ...` as a colorscheme author since I cannot assume that the user is also using the `FzfLuaTabTitle` as the highlight group name.

**Comment by ibhagwan** [comment]
This will require some more changes as the default hls for the tab title/marker aren't currently neovim highlights (hardcoded term colors), in order to do what you want I'd have to permanently link the hl group to another group (or color).

While not a big deal I'd like to do it right as this issue potentially opens up a bigger issue for other terminal highlights such as marker colors in `buffers`, `keymaps`, etc.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8b6181b3977ad16cb5ca9d8f14b0849c8d1d708a

@nyngwang, took a while as I wanted to think about future highlight groups instead of harcoded colors in some providers, the above commit is the start of this process.

I made sure this doesn't change any of the customization nuances you requested in #622, however, setting a highlight via the `tab_title` option will override the default highlight group `FzfLuaTabTitle` (same for the marker variant), but if the highlight isn't specified you can now use:
```
:hi! link FzfLuaTabMarker IncSearch
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/bf17ef4c-f411-4c9d-a047-11a3138f539f)


Which also works when calling:
```lua
:lua require("fzf-lua").tabs({ tab_marker = "<<< CURRENT" })
-- or
:lua require("fzf-lua").tabs({ tab_marker = { "<<< CURRENT" } })
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/6adaa360-a792-4784-9f26-db7790477f79)

But will **get overwritten** when using:
```lua
:lua require("fzf-lua").tabs({ tab_marker = { "<<< CURRENT", "CurSearch" } })
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/d2fbee13-d841-4629-a50d-dec9a55d688c)

**Comment by nyngwang** [comment]
@ibhagwan Great work! I was busy, just got time to try it :)

**Comment by ibhagwan** [comment]
Thanks @nyngwang :)
