### ISSUE TITLE
yank list support?

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#784]
Any yank list support? or any indention to add that?

**Comment by ibhagwan** [comment]
Not directly, you can use [neoclip](https://github.com/AckslD/nvim-neoclip.lua) which stores the yank list and supports fzf-lua as it’s UI.

Another alternative is to yank into tmux and use `:FzfLua tmux_buffers` to view yank history (which is what I personally use), in order to manage yanking into tmux buffers you can use another plugin of mime [smartyank.nvim](https://github.com/ibhagwan/smartyank.nvim).

**Comment by GreenSleeper** [comment]
Thanks, I'll&nbsp; look into it.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 13, 2023 12:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ibhagwan/fzf-lua] yank list support? (Issue #784)




 
Not directly, you can use neoclip which stores the yank list and supports fzf-lua as it’s UI.
 
Another alternative is to yank into tmux and use :FzfLua tmux_buffers to view yank history (which is what I personally use), in order to manage yanking into tmux buffers you can use another plugin of mime smartyank.nvim.
