### ISSUE TITLE
Equivalent to fzf.vim "Rg: [PATTERN]" command ? 

### ISSUE THREAD

**Issue by aphecetche** [ibhagwan/fzf-lua#792]
Hi,

I'm trying to move from vim to Neovim w/ Lua (and Lua only if possible).  One of the command I'm using the most in my day-to-day work is the `fzf.vim` `Rg: [PATTERN]` one. Can this be replicated with `fzf-lua` ?

**Comment by ibhagwan** [comment]
With the default setup you can use:
```lua
:lua require('fzf-lua').grep({ search = <text> })
-- or
:FzfLua grep search=text
```

Alternatively you can recreate the `Rg` command with:
```lua
vim.api.nvim_create_user_command('Rg',
  function(opts)
    require('fzf-lua').grep({ search = opts.fargs[1] })
  end,
  { nargs = "*" }
)
```

**Comment by aphecetche** [comment]
@ibhagwan thanks for the super fast answer !
I went with the recreate `Rg` route. For the record, and for those using `lazy.nvim`, here's what I ended up with : 

```
cat $HOME/.config/nvim/lua/plugins/fzf.lua

return {
	{ 'junegunn/fzf', build = './install --bin', },
	{ 'ibhagwan/fzf-lua',
	   dependencies = { 'nvim-tree/nvim-web-devicons' },
           keys={
		   {"<c-p>",function() require('fzf-lua').files() end,}
	   },
	   cmd = "Rg",
	   config = function()
		   vim.api.nvim_create_user_command('Rg',
                     function(opts)
                       require('fzf-lua').grep({ search = opts.fargs[1] })
                     end,
                     { nargs = "*" })
	   end,
   }
}

```

**Comment by ibhagwan** [comment]
Ty for the update @aphecetche, looks great.

Edited your post to add lua syntax highlighting, closing :)

**Comment by ibhagwan** [comment]
Also, for those coming from fzf.vim I’d highly recommend reading both wiki entries below:
https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep
https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob

These functionalities are fzf-lua extensions that don’t come with fzf.vim, understanding the difference between simple fuzzy matching (`grep`, `grep_project`) and regex (`live_grep`, `live_grep_glob`) and switching between the modes using `ctrl-g` in order to refine result sets is a very powerful tool. Combing that with `rg` globs (limiting search scope to certain files/directories) makes it irreplaceable IMHO.

**Comment by ibhagwan** [comment]
FYI, you can now use [fzf-vim profile](https://github.com/ibhagwan/fzf-lua#profiles) or `:FzfLua setup_fzfvim_cmds`  to create an fzf-lua backed version of the fzf.vim user commands, `:Files`, `:Rg`, etc.
