### ISSUE TITLE
Question about auto sizing for vim.ui.select.

### ISSUE THREAD

**Issue by EmreDogann** [ibhagwan/fzf-lua#793]
This is not a bug report or issue,
I wanted to know if it was possible to have the height of fzf-lua's `vim.ui.select` menu fit the content.

The way I do it now is as follows:

```lua
require("fzf-lua").register_ui_select({
	winopts = {
		height = 0.3,
		width = 0.2,
		row = 0.5,
		col = 0.5,
	},
	fzf_opts = {
		["--layout"] = "reverse-list",
		["--info"] = "hidden",
	},
})
```

This is what it looks like using `cmake-tools.nvim`:
![image](https://github.com/ibhagwan/fzf-lua/assets/48212096/278fe306-167c-461f-a31f-87a1e35d6a51)
As can be seen above, there is a lot of space due to the `height = 0.3` option.

Would it be possible to have an 'auto height' kind of feature so the height of the window is set to the maximum size of the content? Maybe this is already possible and I missed it?

**Comment by ibhagwan** [comment]
> Would it be possible to have an 'auto height' kind of feature so the height of the window is set to the maximum size of the content? Maybe this is already possible and I missed it?

You didn’t miss anything, it’s not possible ATM, not hard to implement, I’ll look into it.

**Comment by ibhagwan** [comment]
I struggled a bit to come up with the exact solution for this, not because it's hard but because there are many options:

- Should we take into consideration min/max height?
- As long as we're willing to take the performance penalty (enumerating all items), why not have adjustable width too?
- Line padding (do you wish to have the exact length or a few lines extra?)
- Other nuances...

I decided the best solution would be to add the ui select `items` to the **already existing options callback**, this way each user can customize this to their liking, as for the request in the OP, below is what I came up with:

**Make sure to update to https://github.com/ibhagwan/fzf-lua/commit/f9056ffb687f474834505f0fe2998878f993901a or the below won't work**

> - min height of 0.15
> - max height of 0.70
> - 4 lines of padding (prompt/query line, borders and one extra empty line)
```lua
  require("fzf-lua").register_ui_select(function(_, items)
    local min_h, max_h = 0.15, 0.70
    local h = (#items + 4) / vim.o.lines
    if h < min_h then
      h = min_h
    elseif h > max_h then
      h = max_h
    end
    return { winopts = { height = h, width = 0.60, row = 0.40 } }
  end)
```

Test with different length items using:
```lua
-- `:=` is equal to `:lua` since neovim 0.9
:= vim.ui.select({1,2}, {}, function() end)
:= vim.ui.select({1,2,3,4,5,6,7,8,9}, {}, function() end)
```

**Comment by ibhagwan** [comment]
I also eat my own dogfood :-)

https://github.com/ibhagwan/nvim-lua/blob/cffed8810e29664213611d634e4c83b6b0ea0896/lua/plugins/fzf-lua/init.lua#L15-L24

**Comment by EmreDogann** [comment]
Just played around with it and it seems to work no problem! Thanks a lot!

![image](https://github.com/ibhagwan/fzf-lua/assets/48212096/02244e4a-b56c-48e6-893e-044a857af97a)

```lua
require("fzf-lua").register_ui_select(function(_, items)
	-- Auto-height
	local min_h, max_h = 0.15, 0.70
	local h = (#items + 2) / vim.o.lines
	if h < min_h then
		h = min_h
	elseif h > max_h then
		h = max_h
	end

	-- Auto-width
	-- if (#items < 10000) then	-- Maybe disable auto-width on large results?
	local min_w, max_w = 0.05, 0.70
	local longest = 0
	for i, v in ipairs(items) do
		local length = #v
		if length > longest then
			longest = length
		end
	end
	-- needs minimum 7 in my case due to the extra stuff fzf adds on the left side (markers, numbers, extra padding, etc).
	local w = (longest + 9) / vim.o.columns
	if w < min_w then
		w = min_w
	elseif w > max_w then
		w = max_w
	end
	-- end

	return {
		winopts = {
			height = h,
			width = w,
			row = 0.5,
			col = 0.5,
		},
		fzf_opts = {
			["--layout"] = "reverse-list",
			["--info"] = "hidden",
		},
	}
end)
```

The only problem I see here is that the auto-width cannot adjust for the extra items taken up by the left side of the fzf window (markers/prompts, numbers, etc). Not a huge deal but it was something I noticed.

> * Should we take into consideration min/max height?
> * As long as we're willing to take the performance penalty (enumerating all items), why not have adjustable width too?
> * Line padding (do you wish to have the exact length or a few lines extra?)
> * Other nuances...
> 
> I decided the best solution would be to add the ui select `items` to the **already existing options callback**, this way each user can customize this to their liking, as for the request in the OP, below is what I came up with:

Yeah, I was wondering about those questions as well before. I think this is the best of both worlds, otherwise yeah so many edge cases to get this to work. This solution also follows similarly with the example in the wiki on dynamic resizing of the windows so things are more consistent.

Now that I think about it, this approach might also work for `winopts_fn` although to be honest I see it being less useful there.

**Comment by ibhagwan** [comment]
> Now that I think about it, this approach might also work for winopts_fn although to be honest I see it being less useful there.


If you take a look at the Wiki’s advanced API you’d notice three types of content: table, function and string - this can work only for table contents when you know the number of items in advance, the other types generate async contents (for performance and UX).

**Comment by EmreDogann** [comment]
Ah I see, that makes sense. Thanks.

**Comment by ibhagwan** [comment]
Now included in the wiki, ty @EmreDogann

https://github.com/ibhagwan/fzf-lua/wiki#ui-select-auto

**Comment by ibhagwan** [comment]
> The one above from @EmreDogann didn't work for me. I spent some time investigating, and the issue was that items parameter was not formatted here. I pre-formatted the string, and use the string length to resize it. It seems to be working:

@ShaolunWang, the snippet in the wiki only auto-adjusts the height, so you’re correct in the sense it wasn’t supposed to format the items and look at the width.

**Comment by joelostblom** [comment]
I'm failing when trying to use the snippet in the wiki to autosize the height of the `vim.ui.select window`. This is what the window looks like by default before trying to resize it:

<img width="736" height="930" alt="Image" src="https://github.com/user-attachments/assets/4b462e23-b32c-4bc8-af06-67bc4ae68c97" />

After applying the wiki snippet, the window now becomes too small so that not all the three lines are visible in code actions and almost nothing of the diff is visible:

<img width="742" height="707" alt="Image" src="https://github.com/user-attachments/assets/de76f232-fd9b-41b9-9639-1ad018b0ea15" />

What I was expecting was something like this where both the section for the code actions and the section for the diff preview autosized based on the number of lines inside each: 

<img width="726" height="711" alt="Image" src="https://github.com/user-attachments/assets/90decdc5-bc79-49fa-9f18-0f54f53663da" />

I tested on both neovim 11.5 and 12 nightly with the same result. Any idea of what might be going awry here?

**Comment by ibhagwan** [comment]
> I tested on both neovim 11.5 and 12 nightly with the same result. Any idea of what might be going awry here?

The snippet only takes into account the amount of entires, for code preview you have to add a few more lines for the preview, increase height until it looks like what you want.

**Comment by joelostblom** [comment]
Thanks for the quick reply! The issue with just increasing the number of lines is that the extra vertical space seems to be divided evenly between between the two boxes in the pop up. So if I add extra lines to fit the output from the diff, it leads to several blank lines below the code actions, which pushes the diff preview further down on the screen:

<img width="726" height="841" alt="Image" src="https://github.com/user-attachments/assets/d0f50d78-c469-4142-9901-fdf96765eca9" />

The desired output would be something like this where each box is autosized to its content:

<img width="726" height="711" alt="Image" src="https://github.com/user-attachments/assets/2ba7cc65-57c6-47aa-a13d-f96a5a97d0a5" />

**Comment by ibhagwan** [comment]
> The issue with just increasing the number of lines is that the extra vertical space seems to be divided evenly between between the two boxes in the pop up. So if I add extra lines to fit the output from the diff, it leads to several blank lines below the code actions, which pushes the diff preview further down on the screen:

The issue here is that the dynamic sizing in ui.select wiki wasn’t meant for code actions with previews, the preview size is a percentage of the total window, if you want this to fit perfectly you’ll need to adjust the code for code actions differently (you can use the `ui_opts.kind` to determine the type of interface) and reverse calculate the total size of window height needed for both the items+preview.
