### ISSUE TITLE
Is there a `path_shorten` option for live_grep?

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#819]
I know a `path_shorten` option exists for `files`, but seems not for `grep`.
So when I have a super long path like the one below, I can't see the result I'm searching for.
What else can I do besides turning off the preview or rotating the preview window?
![image](https://github.com/ibhagwan/fzf-lua/assets/95287687/39f7dbdc-cb60-4213-83ee-2e68a8e167db)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/02535c9a216ed0e4d80f6451c807620335be7a53

@GreenSleeper, I was avoiding this on purpose when the output of `rg` was colored (`--color=always`) due to performance reasons (havign to extract the filename without color and then replace the inner string) but we can give this a go and hopefully the impact on perfomrnace isn't that terrible.

Note that this will not work when using `live_grep_native` as the native version does not perform any processing at all as it's meant to be as performant as possible and passes the information directly to fzf.

**Comment by GreenSleeper** [comment]
I just tried it in a large codebase, and I feel no noticeable performance issue, works great.

**Comment by ibhagwan** [comment]
> I just tried it in a large codebase, and I feel no noticeable performance issue, works great.

Great! Ty for letting me know.
