### ISSUE TITLE
Shorten nvim-jdtls `jdt://…` file entries

### ISSUE THREAD

**Issue by y1rn** [ibhagwan/fzf-lua#838]
### Info

- Operating System: Archlinux
- Shell: zsh
- Terminal: windows terminal
- `nvim --version`: v0.10.0-dev-766+gef44e5972
- `fzf --version`: 0.41

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

`jdt://` files file path so long, is there any option to fetch info from jdt file path and display in view list, like:
```lua
if vim.startswith(b.name, 'jdt://') then
      local _, _, jar_file, _package ,class_name = string.find(b.name,"^.*/(.*jar)/.*/%%3C(.*).*%((.*class).*$")
      ...
end


```

**Comment by ibhagwan** [comment]
Good idea, I’ll look into it when I have more time.

**Comment by ibhagwan** [comment]
For regular files (not jdt links) you can use `path_shorten=true`.

> So it would be great if there was a hook of some sort to post-process the visible lines.

Unfortunately it’s not as easy as it sounds as fzf the binary is responsible for displaying the entries in an external terminal process, the only way to have “hidden” information is via entry data duplication and using `-nth` to hide certain parts which complicates things and also hurts performance (much more data to send to fzf).

**Comment by ibhagwan** [comment]
> Btw: Just switched from fzf.vim and already find this plugin awesome! Thanks a lot! 

And ty for the kinds words @mikehaertl!

**Comment by mikehaertl** [comment]
> For regular files (not jdt links) you can use path_shorten=true

Oh, that's already helpful. Any objections to create a PR to add this (and maybe others?) to `defaults.lua` and the default option section in the `README.md`?

**Comment by ibhagwan** [comment]
> Any objections to create a PR to add this (and maybe others?) to defaults.lua

I’m not sure if it makes sense for everyone, whoever wants it can add it, doesn’t have to necessarily be default.

**Comment by mikehaertl** [comment]
> I’m not sure if it makes sense for everyone, whoever wants it can add it, doesn’t have to necessarily be default.

I meant, adding `path_shorten = false` to the defaults. It's the file I was studying to find undocumented settings.

**Comment by ibhagwan** [comment]
> > I’m not sure if it makes sense for everyone, whoever wants it can add it, doesn’t have to necessarily be default.
> 
> I meant, adding `path_shorten = false` to the defaults. It's the file I was studying to find undocumented settings.

It does appear in the README but it applies to all file providers and it made no sense to duplicate it everywhere, if you wanna help document undocumented options the wiki is open edit :)

https://github.com/ibhagwan/fzf-lua/wiki/Options

**Comment by ibhagwan** [comment]
Tysm @mikehaertl for the wiki contributions!

**Comment by ibhagwan** [comment]
@y1rn, it's a bit unforunate but I can't find a proper way to shorten/expand the nvim-jdtls `jdt://...` links, while I can shorten the display based on the criteria you suggested in the OP without the ability to expand the entries you won't be able to preview the class or jump to the final location.

The only way to do this would be to attach text metadata to the entry and hide it using fzf's `--nth` option, while a viable option since the entries are mixed (both regular files and `jdt://` links) this would mean this change would have to be done globally for all LSP locations, ATM I don't think it's worth the overhead and potential complications (I'd have to rewrite a large part of the LSP display/parsing code).

If you can think of another solution or wish to take a stab at it with a PR feel free to reopen this issue.
