### ISSUE TITLE
lsp_workspace_symbols() in a TypeScript project does not work

### ISSUE THREAD

**Issue by raine** [ibhagwan/fzf-lua#840]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Alacritty 
- `nvim --version`: 0.9.1
- `fzf --version`: 0.42.0

### Description 

In a rust project, `:lua require'fzf-lua'.lsp_workspace_symbols()` works, but in a quite large TypeScript project the popover simply blinks briefly. However `lsp_live_workspace_symbols()` works.

I have basic understanding of the difference between these two. Primarily that the former does filtering with fzf and the latter runs the underlying command again on every keystroke. But any idea why `lsp_workspace_symbols()` works here and how might one debug this?

https://github.com/ibhagwan/fzf-lua/issues/468#issuecomment-1173138836

Perhaps that applies in this case?

Thanks.

edit: 

And by the way, what is the highlight group for the red text here? Need to tone it down and can't seem to find it.

![image](https://github.com/ibhagwan/fzf-lua/assets/11027/438be472-58d5-4cdb-8409-697e6401037d)

**Comment by ibhagwan** [comment]
> And by the way, what is the highlight group for the red text here? Need to tone it down and can't seem to find it.

see https://github.com/ibhagwan/fzf-lua#highlights, you're looking for `FzfLuaHeaderText`.

> In a rust project, :lua require'fzf-lua'.lsp_workspace_symbols() works, but in a quite large TypeScript project the popover simply blinks briefly. However lsp_live_workspace_symbols() works.

That's because it's not supported with typescript server, it doesn't work with an empty query thus only the "live" version works.

The reason it flashes and quickly disappears because it's run async by default, if you want to see a proper error message run `:FzfLua lsp_workspace_symbols async=false` or `:lua require'fzf-lua'.lsp_workspace_symbols({ async = false })`
