### ISSUE TITLE
[Feature] Show preview for lsp_code_action

### ISSUE THREAD

**Issue by mikehaertl** [ibhagwan/fzf-lua#850]
Plugins like [lspsaga](https://github.com/nvimdev/lspsaga.nvim) are able to show a preview for code actions:

![image](https://github.com/ibhagwan/fzf-lua/assets/675062/7b50b917-4880-4e07-812c-dd2720a42dcf)

So it seems this information is available from LSP. It would be cool to also see this implemented in the preview area with fzf-lua.

**Comment by ibhagwan** [comment]
As I mentioned in #849, code actions should be called only via `ui.select`, while previewing is still possible with the ui.select interface I wish to avoid this rabbit hole of code action previews as there are a lot of nuances with code actions.

I consider the value at adds minimal and prefer to avoid it, if it turns out to be simple and straight forward code I’d welcome a PR but as of now I don’t intend to add this myself.
