### ISSUE TITLE
How to scroll the preview pane

### ISSUE THREAD

**Issue by LinuxIsCool** [ibhagwan/fzf-lua#869]
Hi is it possible to scroll the preview?

Actually literally as I was writing the above sentence I noticed that mouse wheel scroll works on the preview pane. 

So is there a key binding to do that as well? I like ctrl-u and ctrl-d to scroll up and down. 

Thanks!

**Comment by ibhagwan** [comment]
Take a look at https://github.com/ibhagwan/fzf-lua#default-options, the default keybinds are `shift-up|down`, you can modify these under `keymap.builtin` and `keymap.fzf` (depends which previewer you’re using, the neovim bulltin buffer or fzf native terminal previewer.

**Comment by garrett361** [comment]
@ibhagwan related question: is it possible to automatically make the preview window cover the set of lines in which the result is found? 

I'm seeing that if I live grep for `test`, say, which is found several times in the same file, the previewer will just show the top however many lines of the file, instead of like showing the bit which contains each instance of `test`. Is that the expected behavior? Feel like I have something set up wrong.

**Comment by ibhagwan** [comment]
> I'm seeing that if I live grep for test, say, which is found several times in the same file, the previewer will just show the top however many lines of the file

It should cover the matched lines, you probably changed the `cmd` or `rg_opts` and you're missing `--column --line-number` arguments so the `rg` results are missing the line/column info, add these back to your `cmd` and you'll be fine.

> Just noticed your edit, you're in the right direction, add the above to your `cmd` arg.

**Comment by garrett361** [comment]
Ah yep! Thank you!

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help.
