### ISSUE TITLE
Ctrl-E keys cannot be used when I have a global tmap

### ISSUE THREAD

**Issue by wookayin** [ibhagwan/fzf-lua#871]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: iTerm
- `nvim --version`: v0.9.2 stable
- `fzf --version`: 0.39.0 (2023040)

### fzf-lua configuration

```lua
-- I have this keymap `tmap <c-e>` in my config because it allows scrolling window as in the normal mode.

vim.cmd [[
  " Double <ESC>: for debugging without leaving the terminal window
  tnoremap <silent> <C-[><C-[> <C-\><C-n>
  tnoremap <silent> <C-\><C-\> <C-\><C-n>

  " Ctrl-E, Ctrl-Y: Scroll window in terminal-normal mode
  tmap <silent> <C-e> <C-\><C-n><C-e>
  tmap <silent> <C-y> <C-\><C-n><C-y>
]]

require('fzf-lua').setup({
})
```

### Description

`:FzfLua command_history`

Press `CTRL-e`, and the default action (edit  won't trigger but my global keymap `<c-e>` is executed. This conflicts with a global keymap.

I thought all the keymap bindings used by fzf-lua should be done as a "buffer" keymap, but it appears it's not the case. How is the keymap implemented in fzf-lua buffers? I cannot find `<ctrl-e>` in the list of  `:tmap <buffer>` when I omit the global keymap setting so `<ctrl-e>` can work.

**Comment by ibhagwan** [comment]
> I thought all the keymap bindings used by fzf-lua should be done as a "buffer" keymap

Actions mappings aren't neovim mappings, the way actions work are via fzf's `--expect` flag which tells fzf to close the interface with the keybind **and print the trigger key into the terminal**, for example:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/545ee405-77bf-4fd2-9660-7680815e4a33)

As you can see above, the first line is the trigger key (assuming I pressed `ctrl-e`) and the second line is the selected item in the fzf interface, in your case, fzf-lua will then parse the terminal output and decide which action to trigger.

One way to workaround your issue is to remap `ctrl-e` to itself during the window `on_create` event:
```lua
require("fzf-lua").setup({
  winopts = {
    on_create = function()
        vim.keymap.set("t", "<C-e>", "<C-e>", { silent = true })
    end,
  }
})
```

Alternatively you can also create an autocmd for `filetype=fzf`:
```lua
local function augroup(name, fnc)
  fnc(vim.api.nvim_create_augroup(name, { clear = true }))
end

augroup("FzfLuaCtrlE", function(g)
  vim.api.nvim_create_autocmd("FileType",
    {
      group = g,
      pattern = "fzf",
      callback = function(e)
        vim.keymap.set("t", "<C-e>", "<C-e>", { buffer = e.buf, silent = true })
      end,
    })
end)
```

**Comment by wookayin** [comment]
I see, thanks for suggesting the workarounds and explaning how it works. Perhaps documentation could be improved, but if that's the way you designed I can understand it.

The way the keymap works sounds a bit confusing and unintuitive to me. Which action (on the neovim side) to be executed is done by *parsing* the first line of fzf's stdout (!). Since all the fzf keymaps might be caught first by global or buffer `tmap`'s; how about automatically adding such buffer keymaps that fzf-lua is expected to use?

**Comment by wookayin** [comment]
Yeah, that makes sense and sounds reasonable. Thank you!
