### ISSUE TITLE
Cursor position outside buffer

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#930]
![CleanShot 2023-11-14 at 15 33 36@2x](https://github.com/ibhagwan/fzf-lua/assets/1625373/073bdeee-7e88-4c72-a682-6e08aa7883ef)

Happens sometimes after grep or findfiles.

What can be the potential cause?

My config: https://github.com/kapral18/config.nvim/blob/f21dad9488fa5c78890237ffa2d7ba3076471806/lua/plugins/fzf.lua

**Comment by ibhagwan** [comment]
> Happens sometimes after grep or findfiles.

This looks like a bug but I need more info on how to reproduce this, can you provide more details on how you get to this state, what’s the originating buffer, what your search results look like and the entry you’re selecting before this happens?

> My config:

I don’t see any issue with your config but I’m also unsure why you copied the entire set of defaults from the docs into your setup function instead of changing only the options you wish to customize.

Although I’m not sure how this could be related it’s worthwhile trying with a clean setup call so we can rule out a config issue.

**Comment by kapral18** [comment]
> This looks like a bug but I need more info on how to reproduce this, can you provide more details on how you get to this 
state, what’s the originating buffer, what your search results look like and the entry you’re selecting before this happens?

Happens if mey neo-tree explorer is open and cursor is there and then I grep with fzflua and then hit enter.

> I don’t see any issue with your config but I’m also unsure why you copied the entire set of defaults from the docs into your setup function instead of changing only the options you wish to customize.

I copied fzflua setup from somewhere else, but one of the reasons could be to not constantly lookup defaults and instead just have them alongside your own setup

**Comment by ibhagwan** [comment]
> Happens if my neo-tree explorer is open and cursor is there and then I grep with fzflua and then hit enter.

I understand, so you’re opening grep while the active buffer is neo-tree?

If so that might explain it, fzf-lua will attempt to set the current buffer to the selected entry and then move the cursor to the match, I’m assuming both would fail.

**Comment by kapral18** [comment]
@ibhagwan it doesn't fail that's the problem, it still opens the selection but it shows this error and starts to lag. And sometimes it doesn't even show the error at all.

**Comment by ibhagwan** [comment]
> @ibhagwan it doesn't fail that's the problem, it still opens the selection but it shows this error additionally and starts to lag. Other times it works ok without showing the error

Alright I’ll do some testing, is fzf-lua able to switch the correct buffer (not the neotree) buffer to the correct one?

**Comment by kapral18** [comment]
@ibhagwan yes

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/640d6415baf6b12c20c16fdd177f106c5575d6c1

@kapral18, the above commit should get rid of the error by ignoring it, it's still not a proper fix as this will avoid setting the cursor at the match location, that's because of how neotree works (doesn't happen with nvim-tree), due to neotree's autocmds it's hard to guess which window will be the one where the buffer will be opened at (could be a few splits) so while I could hack my way with `vim.schedule` or an extra autocmd this will be quite ugly and I'd prefer to avoid it, perhaps this is better fixed properly from neotree's side?

I also tested Telescope and it seems the issue with neotree exists there as well when opening grep interface when neotree is the active buffer.

**Comment by kapral18** [comment]
@ibhagwan I see, thanks much
