### ISSUE TITLE
Attempt to index nil code action response

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#949]
### Info

- Operating System: Arch Linux
- Shell: Fish
- Terminal: Wezterm
- `nvim --version`: v0.10.0-dev-1792+g999e167a5
- `fzf --version`: 0.44.1

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  lsp = {
    code_actions = {
      previewer = 'codeaction_native',
      preview_pager = "delta --side-by-side --width=$FZF_PREVIEW_COLUMNS --hunk-header-style='omit' --file-style='omit'",
    },
  }
})
```
</details>

### Description 
I cannot pinpoint exactly when it happens, but sometimes when requesting code actions with `FzfLua lsp_code_actions` (using the above configuration), I obtain the following error message.

```
Error executing vim.schedule lua callback: ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeactio
n.lua:166: attempt to index local 'res' (a nil value)
stack traceback:
        ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:166: in function 'preview_act
ion_tuple'
        ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:232: in function 'fn'
        ...los/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:107: in function 'fn'
        ...los/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:71: in function <...los/.loca
l/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:70>
Error executing vim.schedule lua callback: ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeactio
n.lua:166: attempt to index local 'res' (a nil value)
stack traceback:
        ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:166: in function 'preview_act
ion_tuple'
        ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:232: in function 'fn'
        ...los/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:107: in function 'fn'
        ...los/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:71: in function <...los/.loca
l/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:70>
```

So far I've seen it happen with TypeScript's "Move to a new file" code action.

**Comment by ibhagwan** [comment]
> So far I've seen it happen with TypeScript's "Move to a new file" code action.

It seems the result from code action resolve request comes back `nil` from the LSP without a specific error, I can easily work around that by checking for nil but I’d like to see why the code action resolving fails even though the LSP indicates it supports resolving.

Can you let me know which LSP do I need to install and perhaps a code sample where I can have the same code action so I can test this?

**Comment by MariaSolOs** [comment]
Of course! I use [`typescript-tools`](https://github.com/pmizio/typescript-tools.nvim) for my TypeScript LSP setup.

This is [the plugin's config](https://github.com/MariaSolOs/dotfiles/blob/fef5fe3a8a18a282a37d9feeabf7e6e0ea0ed65a/.config/nvim/lua/plugins/typescript-tools.lua):

```lua
-- "Native" TSServer client.
return {
    {
        'pmizio/typescript-tools.nvim',
        event = { 'BufReadPre *.ts,*.tsx,*.js,*.jsx', 'BufNewFile *.ts,*.tsx,*.js,*.jsx' },
        dependencies = { 'nvim-lua/plenary.nvim', 'nvim-lspconfig' },
        opts = {
            settings = {
                tsserver_file_preferences = {
                    includeInlayParameterNameHints = 'literals',
                    includeInlayVariableTypeHints = true,
                    includeInlayFunctionLikeReturnTypeHints = true,
                },
            },
        },
    },
}
```

And this is my [code action command](https://github.com/MariaSolOs/dotfiles/blob/ee5c841bed36f9d1c539fce7446024dc98a46da7/.config/nvim/lua/lsp.lua#L59-L71):
```lua
   if client.supports_method(methods.textDocument_codeAction) then
        keymap('<leader>ca', function()
            require('fzf-lua').lsp_code_actions {
                winopts = {
                    relative = 'cursor',
                    width = 0.6,
                    height = 0.6,
                    row = 1,
                    preview = { vertical = 'up:70%' },
                },
            }
        end, 'Code actions', { 'n', 'v' })
    end
```

You can then run `npm i typescript` and the code action is offered with every snippet of TypeScript code, so something as simple as `function foo() { return 0; }` should work.

**Comment by ibhagwan** [comment]
Ty @MariaSolOs, I will attempt your setup.

In the meantime I improved the error handling of failed resolve queries, can you please update to https://github.com/ibhagwan/fzf-lua/commit/adc3dc23aff10bfca5495af57f7e22af28acf1e5 and lmk what the preview window displays on the (previously) failed actions?

If this still fails (very possible since the `res` object is `nil`) - Can you try running `:FzfLua lsp_code_actions previewer=codeaction`? Since the LSP request is async the error handling is a bit different perhaps the error returns a more meaningful message this way.

**Comment by ibhagwan** [comment]
I can already see a potential issue, I already had installed `typescript-language-server` which `typescript-tools.nvim` is a replacement for, the default implementation doesn't appear to support the `resolveProvider` LSP capability (which attempts resolving code actions that aren't already defined as "edit").

I suspect `typescript-tools.nvim` acts as if it does support  `resolveProvider`  but then fails when it queries `typescript-language-server`, I will install `typescript-tools.nvim` and see if this is indeed the issue.

**Comment by ibhagwan** [comment]
@MariaSolOs, can you try https://github.com/ibhagwan/fzf-lua/commit/372b643e42f3f4ed3dd66f88b9d8f9b3fed5d53e - I think it should solve the issue, it should display a similar message (from `typescript-language-server`):
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/dfa8c530-e8e3-426d-973b-b0b838aee5ea)

**Comment by MariaSolOs** [comment]
@ibhagwan commits tested and they work! It's a bit strange though because depending on the location the preview might be shown, but that's definitely an issue with TSServer and not `fzf-lua`.

As always, thank you for the impressibly fast fix <3

**Comment by MariaSolOs** [comment]
Also sorry for the slightly complex setup! I will try to provide proper minimal reproduction environments in the future.

**Comment by ibhagwan** [comment]
> depending on the location the preview might be shown, but that's definitely an issue with TSServer and not fzf-lua

Neovim uses `make_positional_params` which then correspond to the cursor location when the request is invoked, not much I can do about that indeed.

> Also sorry for the slightly complex setup! I will try to provide proper minimal reproduction environments in the future.

No worries, LSP setup in neovim can be quite involved.

**Comment by yavorski** [comment]
Hello, could you please provide some guidance on resolving or mitigating this error?
It operates smoothly during the initial activation of codeAction, but on the second attempt, it results in an error.
My configuration closely resembles Maria's. I'm sharing a video example along with the accompanying error that occurred.
Thank you!

Error:
```lua 
Error executing vim.schedule lua callback: ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:129: attempt to index local 'action' (a nil value)
stack traceback:
  ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:129: in function 'preview_action_tuple'
  ...e/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:283: in function 'fn'
  ...wrx/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:117: in function 'fn'
  ...wrx/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:76: in function <...wrx/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:75>
```
Video:

https://github.com/ibhagwan/fzf-lua/assets/3436517/42507c4a-60e2-431c-a37a-5bd11861788e

**Comment by ibhagwan** [comment]
> Hello, could you please provide some guidance on resolving or mitigating this error?
> It operates smoothly during the initial activation of codeAction, but on the second attempt, it results in an error.
> My configuration closely resembles Maria's. I'm sharing a video example along with the accompanying error that occurred.
Thank you!

@yavorski, this seems like it might be a new issue from recent changes related to #1057, there is a chance you may have been caught in bwteeen commits, can you please update to the latest commit and if the issue still persists open a new issue and we’ll tackle it there?

**Comment by yavorski** [comment]
Hi, Thanks a lot for your response! I've double-checked, and can confirm that I'm using the latest version. The issue seems to be sticking around quite consistently. Any insights or help would be awesome!

[`d68d1cf chore(tabs): move encoded tab_cwd to start of line (#1064) (2 days ago)`](https://github.com/ibhagwan/fzf-lua/commit/d68d1cfde9bf82061dfdfe35b83fb8636e03766d)

![image](https://github.com/ibhagwan/fzf-lua/assets/3436517/933cfca3-a3e8-4e3b-85e7-7026f8409c53)

**Comment by ibhagwan** [comment]
@yavorski , update to https://github.com/ibhagwan/fzf-lua/commit/404e7522d1cd8c57b305f0acf46647d8e0660ef3 - this commit validates the action returned from the LSP server is valid and **works around the error**.

However, the cause of this error is not fzf-lua but `typescript-tools.nvim`, I was able to reproduce this issue by installing `typescript-tools.nvim` and using the same setup found in your dotfiles (may or may not be relevant):
https://github.com/yavorski/dotfiles/blob/61c59ccf45252ad9b1b73d1f63fe4b2b22b07e8c/nvim/init.lua#L1538-L1573

In order to display the diff for the code action preview, if the action doesn't contain the workspace edit section, fzf-lua will send a `codeAction/resolve` request to the LSP server, the first call works (as you found out) but any subsequent call is bugged (and returns `nil`) with `typescript-tools.nvim`.

If fzf-lua sends a synchrounous request with:
```lua
:FzfLua lsp_code_actions previewer=codeaction_native
```
`typescript-tools.nvim` returns a nil action, with the latest commit, fzf-lua will fallback to the original unresolved action and display this message (no error but also no diff):
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/cf9b98b6-6985-4427-9ffd-05d73cabf702)

If using the neovim builtin (non-native) previewer, fzf-lau will send an async LSP request and waits for a callback which never returns, e.g.:
```lua
:FzfLua lsp_code_actions previewer=codeaction
```
Resulting in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/9e12af01-759b-4667-8b9c-d9d913c78a07)


Hopefully this is enough information for you to open an upstream issue with `typescript-tools.nvim`.

**Comment by yavorski** [comment]
@ibhagwan, my apologies for the delayed response. Just tested with latest commit https://github.com/ibhagwan/fzf-lua/issues/949 and it is working great now! Huge thanks for your awesome work!

**Comment by ibhagwan** [comment]
> @ibhagwan, my apologies for the delayed response. Just tested with latest commit #949 and it is working great now! Huge thanks for your awesome work!

It's working, but not "great" yet :-)

There's a bug in `typescript-tools.nvim` causing the 2nd call onward to not display the diff.

**Comment by yavorski** [comment]
There is already an existing issue at https://github.com/pmizio/typescript-tools.nvim/issues/231. I've forwarded your comment, and I'm happy to note that `codeActions` have significantly improved; at least they do not constantly throw errors now. Thank you once again for your assistance!

**Comment by ibhagwan** [comment]
> There is already an existing issue at [pmizio/typescript-tools.nvim#231](https://github.com/pmizio/typescript-tools.nvim/issues/231). I've forwarded your comment, and I'm happy to note that `codeActions` have significantly improved; at least they do not constantly throw errors now. Thank you once again for your assistance!

I see, added my 2 cents on that issue as well.
