### ISSUE TITLE
Would a PR trying to add windows support be welcomed?

### ISSUE THREAD

**Issue by TheLeoP** [ibhagwan/fzf-lua#954]
### Description 

I'll like to try adding windows support based on the work already done by #772. I can't promise anything, but since I'm mostly using windows and I've heard such nice things about fzf-lua, I'd like to give it a try.

**Comment by ibhagwan** [comment]
Go for it @TheLeoP, as long as it’s throughly tested it will be welcomed :)

**Comment by GitMurf** [comment]
I see this Issue was closed. A couple questions:

1. does this imply Windows support is now available? From digging around I do not think so yet, but wanted to validate.
2. if no Windows support yet, @TheLeoP it looks like you are taking on the task of trying to get Windows working? It would be nice if you created a GH Issue to follow the development similar to this one from the past (that was dropped): #751 
3. if you created an open "discussion/progress" Issue for windows support (as suggested in Item 2) I would be happy to follow along and help provide testing as I am a Windows user very interested in this.

Appreciate the hard work!

**Comment by ibhagwan** [comment]
> I see this Issue was closed. A couple questions:
> 
> 1. does this imply Windows support is now available? From digging around I do not think so yet, but wanted to validate.
> 2. if no Windows support yet, @TheLeoP it looks like you are taking on the task of trying to get Windows working? It would be nice if you created a GH Issue to follow the development similar to this one from the past (that was dropped): [Windows support ongoing questions #751](https://github.com/ibhagwan/fzf-lua/issues/751)
> 3. if you created an open "discussion/progress" Issue for windows support (as suggested in Item 2) I would be happy to follow along and help provide testing as I am a Windows user very interested in this.
> 
> Appreciate the hard work!

1. Correct, no windows support as of now.
2. A GH issue people can subscribe to get notifications is a good idea

**Comment by TheLeoP** [comment]
@GitMurf just in case you didn't get pinged, #961 is tracking the progress of adding windows support

**Comment by GitMurf** [comment]
@TheLeoP is this still being tracked? Did it land? It looks like the PR was closed without merge? Thanks in advance for any updates!

**Comment by ibhagwan** [comment]
> @TheLeoP is this still being tracked? Did it land? It looks like the PR was closed without merge? Thanks in advance for any updates!

Windows support was added long ago @GitMurf lol

https://github.com/ibhagwan/fzf-lua/pull/961

https://github.com/ibhagwan/fzf-lua/commit/a5b32c30ece070d0417c2f41751fa11248c4e5de

**Comment by GitMurf** [comment]
> > @TheLeoP is this still being tracked? Did it land? It looks like the PR was closed without merge? Thanks in advance for any updates!
> 
> 
> 
> Windows support was added long ago @GitMurf lol
> 
> 
> 
> https://github.com/ibhagwan/fzf-lua/pull/961
> 
> 
> 
> https://github.com/ibhagwan/fzf-lua/commit/a5b32c30ece070d0417c2f41751fa11248c4e5de

Haha awesome news! I only saw the red "closed" PR and thought maybe it was cancelled or something 🤷🏻‍♂️ thanks!
