### ISSUE TITLE
grep_project command can't be filtered by files 

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#964]
### Info

- Operating System: Archlinux
- Shell: zsh
- Terminal: st
- nvim --version: 0.9.4
- fzf --version: 0.44.1 (29e67d30)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description
here in wiki https://github.com/ibhagwan/fzf-lua/wiki#how-can-i-restrict-grep-search-to-certain-files is mentioned that enabling `rg_glob` can enable use of ` --` for every grep picker while `grep_project` is returning nothing after filtering files.

**Comment by ibhagwan** [comment]
This is not a bug, this is by design, grep project only does fuzzy matching on the output of a single `rg` command, globs can only be specified via the `search` arg (or `Grep For>`) prompt, once the interface is open you can only do fuzzy matching and need to use `ctrl-g` to change the search term (including globs).

**Comment by mortezadadgar** [comment]
thanks that clear it up.

**Comment by ibhagwan** [comment]
> thanks that clear it up.

Highly recommend reading the recent discussion I had in #542 about this, will help you understand and perhaps customize this for your needs.
