### ISSUE TITLE
fzf --info option does not apply to the commands files, grep and lsp symbols

### ISSUE THREAD

**Issue by gmr458** [ibhagwan/fzf-lua#981]
### Info

- Operating System: Fedora 39
- Shell: ZSH
- Terminal: Alacritty
- `nvim --version`: v0.10.0-dev-2000+g6fa0f303d
- `fzf --version`: 0.44.1

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    fzf_opts = {
        ['--info'] = 'right',
    },
})
```
</details>

### Description 
From what I understand, the options that I pass to the `fzf_opts` table should apply to all commands, but in particular this does not happen with the `--info` option to the commands `files`, `grep` and `lsp symbols`, so I have to repeat that configuration, I use other fzf options such as `--color`, `--scrollbar` and `--no-bold` and they do not have that problem.

**Comment by ibhagwan** [comment]
That's because some providers have specific `--info` defined in the defaults, for example `files`:
https://github.com/ibhagwan/fzf-lua/blob/949f3caadebfc9ba64ffb0e1a1d29bba01157cd4/lua/fzf-lua/defaults.lua#L220

I considered removing `--info` from the defaults altogether but since it's been like this for years now I avoided the breaking change.

You can do either:
```lua
require("fzf-lua").setup({
  files = {
    fzf_opts = { ['--info'] = 'right' },
  },
})
```

Or (negate the default, thus inheriting from root `fzf_opts`):
```lua
require("fzf-lua").setup({
  files = {
    fzf_opts = { ['--info'] = false },
  },
})
```
